### ISSUE TITLE
Certificate spec.commonName too long

### ISSUE THREAD

**Issue by Ghostbaby** [kubernetes-sigs/kubebuilder#1012]
```
Name:         elasticsearch-operator-serving-cert
Namespace:    elasticsearch-operator-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"certmanager.k8s.io/v1alpha1","kind":"Certificate","metadata":{"annotations":{},"name":"elasticsearch-operator-serving-cert"...
API Version:  certmanager.k8s.io/v1alpha1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2019-09-24T08:24:17Z
  Generation:          2
  Resource Version:    9178991
  Self Link:           /apis/certmanager.k8s.io/v1alpha1/namespaces/elasticsearch-operator-system/certificates/elasticsearch-operator-serving-cert
  UID:                 b33022cb-dea4-11e9-bb57-00163e0ce7c9
Spec:
  Common Name:  elasticsearch-operator-webhook-service.elasticsearch-operator-system.svc
  Dns Names:
    elasticsearch-operator-webhook-service.elasticsearch-operator-system.svc.cluster.local
  Issuer Ref:
    Kind:       Issuer
    Name:       elasticsearch-operator-selfsigned-issuer
  Secret Name:  webhook-server-cert
Status:
  Conditions:
    Last Transition Time:  2019-09-24T08:24:17Z
    Message:               Certificate does not exist
    Reason:                NotFound
    Status:                False
    Type:                  Ready
Events:
  Type     Reason     Age                  From          Message
  ----     ------     ----                 ----          -------
  Warning  BadConfig  3m4s (x4 over 3m4s)  cert-manager  Resource validation failed: spec.commonName: Too long: must have at most 64 characters

```
/kind bug

**Comment by DirectXMan12** [comment]
err... this is tough.  That's the shortest reasonable CN that we can issue without accidentally gitting the "service: google, namespace: com" issue.

@munnerz suggestions here?

Among other things (this is a bit of a bandaid), since we're aiming to scaffold in a namespace, we don't also have to name prefix (that's what a namespace is for) cc @mengqiy @droot

**Comment by mengqiy** [comment]
That may help and things should still work when the resources are namespaced.
But we do have some cluster-scoped resources, they may collide with others if we drop the name prefix in `kustomization.yaml`.

**Comment by munnerz** [comment]
So this is because the common name field is actually restricted to 64 characters in the x509 spec, which we recently started enforcing.

That said, in your case you've *not* specified a common name at all. You are still getting this error because cert-manager copies the first dnsName and uses it as the common name at the moment. This is because a long time ago when the project was first started, the Let's Encrypt ACME server also did this, and it made our 'is the certificate up to date' comparison easier.

In v0.11, we intend to change this behaviour and instead make our 'is the certificate up to date' logic more intelligent, which should in turn resolve this issue here too.

In the meantime, explicitly setting a shorter spec.commonName should resolve the problem, as cert-manager will *not* then override it with the specified dnsName.

**Comment by munnerz** [comment]
Ah, I see you *have* explicitly set a commonName, but it is still longer than 64 characters.

You'll want to specify *something* else as the commonName, perhaps the singular name of the Service? IIRC, Kubernetes already limits this to 64 characters 😅

**Comment by DirectXMan12** [comment]
just service-local seems like it's probably fine.  We want to avoid a situation where we sign for something that we don't have the authority to sign for.

Aside: I'm confused as to the logic behind the 64 character limit on the CN though -- isn't CN for serving certs usually domain name, in which case each subsection is 63 characters at most, and the whole is 250-something give-or-take?  I.e. `"a".repeat(63)+".com"` is a totally valid domain name (e.g. http://abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.com), but can't use its domain name as the CN.  I wonder what they're supposed to do?  Can you just make the CN whatever?  After a quick search (the most dangerous type), [rfc6125](https://tools.ietf.org/html/rfc6125#section-6.4.4) seems to imply that nothing should be checking CN  as a DNS name anyway, but I'm so very far from being an expert on this, so :woman_shrugging:

**Comment by munnerz** [comment]
This shouldn’t be an issue from v0.11 onwards so long as you only specify dnsNames on the Certificate resource. We no longer copy across dnsNames[0] to the commonName field.

**Comment by camilamacedo86** [comment]
So, could we close this one? @munnerz
