### ISSUE TITLE
Timer based reconciliation

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1015]
Hi folks, Does kubebuilder have any APIs for implementing a timer based entry of the reconcile loop (in addition to the resource watch based triggers..). I do follow that reconcile is "level" based as opposed to event driven and perhaps timer driven polling is out of scope, but have been wondering whether in some scenarios it would be more efficient to reconcile based on a timed poll rather than on level driven updates.

**Comment by camilamacedo86** [comment]
Hi @champak, 

If you check the main.go file you will find the following code.

```go
       mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:             scheme,
		MetricsBindAddress: metricsAddr,
		LeaderElection:     enableLeaderElection,
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}
```

This code will create the manager. Then, ee the Options Struct which is used to create the Manager of the project.  If you check its godocs you will find the following attribute. 

```go
	// SyncPeriod determines the minimum frequency at which watched resources are
	// reconciled. A lower period will correct entropy more quickly, but reduce
	// responsiveness to change if there are many watched resources. Change this
	// value only if you know what you are doing. Defaults to 10 hours if unset.
	SyncPeriod *time.Duration
```

So, by default, the reconcile will be trigged every 10 hours. However, I would not recommend you reduce this period unless as you can check in its documentation you really know what you are doing. 

Note that the reconcile should be trigged just when something controlled by was changed. In order to `watch` the objects and trigger the reconcile use the watch feature. See [here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/gopath/src/project/pkg/controller/firstmate/firstmate_controller.go#L62) an example and its documentation [here](https://book-v1.book.kubebuilder.io/beyond_basics/controller_watches.html).

**Comment by champak** [comment]
@camilamacedo86 Thanks for looking into this ! The comment in the Options structure seems to imply that this timer is a guarantee that reconcile shall get invoked within the specified time; that is a bit different from time based polling which would wake up the user reconcile irrespective of changes but can anyways be leveraged. Closing

**Comment by DirectXMan12** [comment]
FYI, we don't recommend using resync period, and instead reccomend `RequeueAfter` in `reconcile.Result`

**Comment by mazzy89** [comment]
In the case of Timer-based reconciliation, do you recommend to still watch resources?
