### ISSUE TITLE
Doc improvements: explain some quickstart steps better.

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1033]
in https://kubebuilder.io/quick-start.html#test-it-out-locally
- [ ] explain that you want to press `y` for `Create Resource [y/n]` and `Create Controller [y/n]`. 
- [ ] consider re-titleing section from _Test it out locally_ to _Test it out_. This is a confusing heading because it gives you the option to test with "KIND" or with a remote cluster.  When you use a remote cluster, it is not really local, for the CRD install step.  The controller is local.  
- [ ] After `make install` step, suggest a `make uninstall` step so that the cluster is left in its original state.  Having a CRD without a controller is a messy state to leave a cluster in.  See #1032.
- [ ] when it says _Run your controller_ explain that the controller is running on your local machine.  I know the section title is "Running it Locally", but if it is unclear what this means when I am using a "remote" cluster and installing my CRDs "remotely".  Then just the "controller" is local.  
- [ ] Add some text to the end of the _Test It Out Locally_ section to summarize what just happened.  See below for suggested text.
- [ ] The https://kubebuilder.io/quick-start.html#install-samples section is small and lonely.  Suggest merging into prior section. 

---
Suggested text for end of  _Test It Out Locally_ section

 You've now installed a CRD and a controller into your Kubernetes cluster.  Together, these constitute a new kind of resource.  Try listing this new resource, like this: `kubectl get $kind.$group.$groupdomain`.    Hmm.  There aren't any.  But, KubeBuilder automatically generates a sample resource for you.  These are in `config/samples/`

**Comment by camilamacedo86** [comment]
The suggestion `After make install step, suggest a make uninstall step so that the cluster is left in its original state. Having a CRD without a controller is a messy state to leave a cluster in. See #1032.` can just be applied when it https://github.com/kubernetes-sigs/kubebuilder/issues/1032 be implemented and should be part of it.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12 and @erictune, 

I think we can close it with the merge of PR: #1008. The quick was improved and may is not exactly as you suggested here but I think that it is covering now your main concerns raised here. WDYT? Can we close this one?

**Comment by erictune** [comment]
@camilamacedo86 
Which of the checkboxes in the top post of this issue do you think are fixed by #1008?

**Comment by camilamacedo86** [comment]
Hi @erictune, 

Following the points addressed.  

> - explain that you want to press y for Create Resource [y/n] and Create Controller [y/n].

Done: https://github.com/camilamacedo86/kubebuilder/blob/a9860545bb0e6bb56fc4973423eca7fb36d6e08d/docs/book/src/quick-start.md#press-options

I better explanation with an example was introduced as the links for the user be able to check its details in the tutorial. However, the user do not really need press y and do it in the quick start. For a further understand they will be redirect to the tutorial at the end of this doc as well.  

>- consider re-titleing section from Test it out locally to Test it out. This is a confusing heading  because it gives you the option to test with "KIND" or with a remote cluster. When you use a remote cluster, it is not really local, for the CRD install step. The controller is local.

Done here: https://github.com/camilamacedo86/kubebuilder/blob/a9860545bb0e6bb56fc4973423eca7fb36d6e08d/docs/book/src/quick-start.md#test-it-out

> - After make install step, suggest a make uninstall step so that the cluster is left in its original state. Having a CRD without a controller is a messy state to leave a cluster in. See #1032.

We have not the uninstall option so far, SO, IMHO it should be addressed with #1032 as described above. 

> - when it says Run your controller explain that the controller is running on your local machine. I know the section title is "Running it Locally", but if it is unclear what this means when I am using a "remote" cluster and installing my CRDs "remotely". Then just the "controller" is local.

> - Add some text to the end of the Test It Out Locally section to summarize what just happened. See below for suggested text.when it says Run your controller explain that the controller is running on your local machine. I know the section title is "Running it Locally", but if it is unclear what this means when I am using a "remote" cluster and installing my CRDs "remotely". Then just the "controller" is local.
> - Add some text to the end of the Test It Out Locally section to summarize what just happened. See below for suggested text.

IMHO the go is the user understands that it will run out of the cluster which shows clear here:  https://github.com/camilamacedo86/kubebuilder/blob/a9860545bb0e6bb56fc4973423eca7fb36d6e08d/docs/book/src/quick-start.md#test-it-out.

For a further understand they would need to follow up the tutorial as recommended at the end of the quick start. If we add too much info here it will no longer to be a quick start. In POV, the idea is just to show the macro view over how it works and for a better/deeper understanding they should follow the tutorial. 

> The https://kubebuilder.io/quick-start.html#install-samples section is small and lonely. Suggest merging into prior section.

It sofer few changes in order to make more intuitive what it actually does. See [here](https://github.com/camilamacedo86/kubebuilder/blob/a9860545bb0e6bb56fc4973423eca7fb36d6e08d/docs/book/src/quick-start.md#install-instances-of-custom-resources). Also, a better example over the changes was added in the above step which can clarify its goal. See [here in Click here to see an example. `(api/v1/guestbook_types.go)`](https://github.com/camilamacedo86/kubebuilder/blob/a9860545bb0e6bb56fc4973423eca7fb36d6e08d/docs/book/src/quick-start.md#press-options)

**Comment by camilamacedo86** [comment]
Hi @erictune, 

Also,I did a new PR to cover these points. Please, see #1076 and let me know if we can agree in close this one with or if it has anything else more that you would like to address.

**Comment by camilamacedo86** [comment]
Hi @erictune 

We can close this one now :-)
