### ISSUE TITLE
Invalid Additional Printer Column Examples in the Documentation

### ISSUE THREAD

**Issue by ephemeral** [kubernetes-sigs/kubebuilder#1114]
The JSONPath examples in the Generating CRD reference document need to be updated.

If someone tries to use JSONPath, running `make generate` will fail with `unknown argument "JSONPATH"` 

Quick fix: Update all ref to JSONPATH -> JSONPath

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @ephemeral,

It shows solved. Could you please close this one? 

Also, for the next ones if you add `Closes: #<number>` of the issue in the PR its closes automatically when the PR is merged.  Note, that also would be great to assign the issue when you are working on in the solution because others will be looking for the "assing to nobody" to know how to contribute with.

Really thank you for raising that and contribute with the great solution 🥇

**Comment by ephemeral** [comment]
Done, thanks for the info @camilamacedo86 :)
