### ISSUE TITLE
Missing import in scaffolded code

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1119]
# Bug description
Missing `"k8s.io/apimachinery/pkg/runtime"` import in controller scaffolding.
I think my IDE added the import automatically as I can't find it in the scaffold file.

https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/v2/controller.go#L71-L86

/kind bug

**Comment by Adirio** [comment]
@camilamacedo86

**Comment by mengqiy** [comment]
Yes, this is a bug.
Thanks for bringing this up.
/assign @camilamacedo86

**Comment by mengqiy** [comment]
It seems @Adirio has already started to work on this in #1120.

**Comment by droot** [comment]
@mengqiy I am wondering why isn't this caught by our tests ?

**Comment by camilamacedo86** [comment]
Hi @mengqiy, @droot and @Adirio, 

I tested it locally and I could not find any issue regards to it. The import will be added in the controller as it was done by the golden script [here](https://github.com/kubernetes-sigs/kubebuilder/blob/3103ad75279f83805495ace03095df88ee42af81/testdata/project-v2/controllers/captain_controller.go#L23) in the testdata.

Following the steps. 

```
$ mkdir example
$ cd example/
$ kubebuilder init --domain my.domain
$ kubebuilder create api --group webapp --version v1 --kind Guestbook
```

- Select y and y. 
- Then, let's check the controller by the vim in order to ensure that any IDE will not o the import automatically `vim controllers/guestbook_controller.go`

package controllers
    
```go
import (
        "context"
    
        "github.com/go-logr/logr"
        "k8s.io/apimachinery/pkg/runtime"
        ctrl "sigs.k8s.io/controller-runtime"
        "sigs.k8s.io/controller-runtime/pkg/client"

        webappv1 "sigs.k8s.io/example/api/v1"
)

// GuestbookReconciler reconciles a Guestbook object
type GuestbookReconciler struct {
        client.Client
        Log    logr.Logger
        Scheme *runtime.Scheme
}

```

See that `"k8s.io/apimachinery/pkg/runtime"`  is in the imports and it is what is used in ` Scheme *runtime.Scheme`.

**Comment by mengqiy** [comment]
The reason why missing import haven't cause us problem in test is that the generated go code go through goimport. After processing, goimports seems to quite smart to add the proper imports.
We should not rely on goimports to add that for us.

**Comment by droot** [comment]
Thanks @camilamacedo86 for the explanation.
