### ISSUE TITLE
Do we need a direct client for reliably accessing native resources ?

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1124]
I intermittently see issues with issuing Get() to check on k8 resources such as Pods. e.g. I get nothing back when kubectl reports presence of the named Pod. This could be because the manager client i am using is reading from a stale cache. Think I could be using a "direct" client (just off the client api) instead but do not see that in the docs. Also passing the direct client around seems tedious. Anyone else see these issues ? One odd issue is that List() works OK; not clear why if its really stale cache List() does not run into the same issue.

**Comment by camilamacedo86** [comment]
HI @champak, 

Could you provide more detailed information in the order we try to help you with? What is the issue/exception faced, could you add it here? Also, how we can reproduce this scenario? I mean, after follow up the Quick Start what is required to do for we face the same behaviour?

**Comment by functicons** [comment]
@champak, how do you know it reads from a cache? Sometimes when updating CR status, I encounter  error saying the CR is not up-to-date, I need to get the latest version first.

**Comment by camilamacedo86** [comment]
This error occurs because the CR was updated in the middle time between when it was fetched and when the platform received the request to update it. 
 
Note that the controller works as a loop like the following pseudo-code example. Then, what you need is ensure that your code implemetation is interpolant and it will just stop when all is in the expected state and values. 

```go
reconcile App {

   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
   
   // Check if a Service for the app exists, if not create one 
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   }  

   // Looking for Database CR/CRD 
   // Check the Database Deployments Replicas size
   // If deployment.replicas size != cr.size, then update it
   // Then, go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{Requeue: true}, nil
   }  
   ...
   
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil

}  
```

The following are possible return options to restart the Reconcile:

- With the error:
> return reconcile.Result{}, err

- Without an error:
> return reconcile.Result{Requeue: true}, nil

- Therefore, to stop the Reconcile, use:
> return reconcile.Result{}, nil

I hope that it helps you with.

**Comment by functicons** [comment]
@camilamacedo86 thanks for your information! But I am still unclear how "the CR was updated/changed in the middle time between when it was fetched and when the platform received the request to update it" could happen. I always update the status of the CR in my reconcile(), since reoncile requests are handled sequentially, I don't understand how the situation could happen.

**Comment by champak** [comment]
@functicons You can have multiple entities that concurrently attempting to update any K8 object and hence there must be some logic which backs off new updates when it determines the updates are on a stale base. That is more common for native k8 objects rather than CRDs. Things like annotations can I think get updated on the CRD outside your control.

**Comment by champak** [comment]
@camilamacedo86 I have not yet figured a generic way to recreate the issue with Get failing when List succeeds. I have just switched to using List on Pods.

**Comment by camilamacedo86** [comment]
Hi @champak,

Your question here shows answered. Regards the issue that you are facing if you be able to reproduce again could you please raise a new issue with it and its steps?  

Also, could you close this one? Or at least let us know what is missing to do this action regards the main question/subject of this issue?

Thank you.

**Comment by champak** [comment]
I concluded in some cases we must use a direct client. @camilamacedo86 thanks for looking into this. I cannot think of means for guaranteeing that the cached client the kubebuilder harness uses would always see the latest info. Closing.
