### ISSUE TITLE
Verify that AdmissionWebhooks impements File

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1214]
There is a (probably copy-paste related) small bug that doesn't verify if `AdmissionWebhooks` implements the `File` interface:

https://github.com/kubernetes-sigs/kubebuilder/blob/6121dd0a122f9be31ac6ec92eb0b444b0618b9f7/pkg/scaffold/v1/webhook/admissionwebhooks.go#L28

/kind bug

**Comment by camilamacedo86** [comment]
HI @Adirio, 

Did you try to use the feature or you are just assuming that it has an error because of the name? Could you provide the tests used to check it and the error faced?

**Comment by Adirio** [comment]
It (most probably) is a copy-paste error:

See how that line is the same as this other in another file:

https://github.com/kubernetes-sigs/kubebuilder/blob/6121dd0a122f9be31ac6ec92eb0b444b0618b9f7/pkg/scaffold/v1/webhook/server.go#L27

The rest of the files in that directory do it right, see for example:

https://github.com/kubernetes-sigs/kubebuilder/blob/6121dd0a122f9be31ac6ec92eb0b444b0618b9f7/pkg/scaffold/v1/webhook/add_admissionbuilder_handler.go#L28

**Comment by camilamacedo86** [comment]
Ok. I understand, however, before we do any change we need be sure that it is an error by: 

- Check how it works
- Test it locally
-  See the error which it will cause

Then, we can fix by:
- Solving the issue
- Adding a test to ensure that it will not happen again since the CI is not failing with the issue.  

Is it make sense?

**Comment by Adirio** [comment]
> * Check how it works

Interfaces in Golang are implemented just by coding the approapiate methods. This means that there are certain situations where a struct not implementing an interface results in a runtime error instead of a compilation error. To make it always detect it at compile time you can ensure that a certain struct (`StructName`) implements a interface (`InterfaceName`) with the line `var _ InterfaceName = StructName{}` or `var _ InterfaceName = &StructName{}`.

Reference: https://golang.org/doc/faq#guarantee_satisfies_interface

This line itself is a test. The process you described, while perfectly valid for 99.99% of the cases, doesn't make sense for this particular case.

**Comment by camilamacedo86** [comment]
HI @Adirio, 

When I say  `Check how it works` I am not speaking about interfaces in go. I am speaking about the feature that you would like to fix/change. Did you test the webhooks feature which will use this scaffold file? 

Also, note that it is v1 which is deprecated then, the strategy does not really change it. So, we need to be very sure that this change/fix is required.

**Comment by Adirio** [comment]
> Did you test the webhooks feature which will use this scaffold file? Do you know how it works? What is wrong and how it should work?

Yes, I tested and works. This change is a test, despite not being in a `*_test.go` file. This ensures that if someone removes the `AdmissionWebhooks.GetInput` method, we will get a compile error saying that we are missing this method.

> Also, note that it is v1 which is deprecated then, the strategy does not really change it. So, we need to be very sure that this change/fix is required.

This change is an additional test. It's just correcting a typo in a test.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

Following my checks and observations

- The change here in the interface shows correctly. 
- We can confirm that this file is scaffolded by default for v1 projects. See  [here](https://github.com/kubernetes-sigs/kubebuilder/search?q=%2F%2F+Builders+contain+admission+webhook+builders&unscoped_q=%2F%2F+Builders+contain+admission+webhook+builders). 
- Also, we can check that it is just valid for v1 and not used in the v2
- So, it has been checked by the CI which is passing and the scaffold files were not impacted at all. 

Then, the change/fix shows OK. However, since the v1 is deprecated I am not sure if we should or not move forward with changes there unless they are strictly required. I will leave it with the team members as described in the PR.
