### ISSUE TITLE
[feature request] Support golang runtime or net/http pprof

### ISSUE THREAD

**Issue by gaocegege** [kubernetes-sigs/kubebuilder#1225]
/kind feature

It will be nice if we could support net/http/pprof or runtime/pprof with kubebuilder.

Now I have such a workaround:

```go
func main() {
	ctrl.SetLogger(zap.Logger(true))

	var metricsAddr string
	var pprofAddr string
	var enableLeaderElection bool
	flag.StringVar(&pprofAddr, "pprof-addr", "0", "The address the pprof endpoint binds to.")
	flag.StringVar(&metricsAddr, "metrics-addr", "0", "The address the metric endpoint binds to.")
	flag.BoolVar(&enableLeaderElection, "enable-leader-election", false,
		"Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.")

	flag.Parse()


	if pprofAddr != "0" {
		go func() {
			log.Println(http.ListenAndServe(pprofAddr, nil))
		}()
	}

```

I think we can reuse the metrics-addr for pprof but now it is running on TCP, thus it cannot work with http pprof.

**Comment by yeya24** [comment]
I am running into the same issue. Seems there is a PR for this now https://github.com/kubernetes-sigs/controller-runtime/pull/743.

**Comment by camilamacedo86** [comment]
Kubebuilder uses the controller-runtime so it is something that would need to be implemented/provided there and then, will be available to kubebuilder when it is using the release version with the solution.  Also, as @yeya24  point out shows that we have a PR already for that there. 

@yeya24 @gaocegege could you please follow up this PR and raise this need in kubernetes-sigs/controller-runtime ? 

I am closing this one since shows that has nothing to be done here. However, please feel free to re-open if I misunderstood something or if you think that it needs to be kept open because something still needs to be done in the Kubebuilder project. 

/close

**Comment by gaocegege** [comment]
SGTM. Thanks for your reply.
