### ISSUE TITLE
Do we have list of all operators built using kubebuilder ?

### ISSUE THREAD

**Issue by gautamkmr** [kubernetes-sigs/kubebuilder#1239]
Something like this https://github.com/operator-framework/awesome-operators which operator-sdk uses ?

**Comment by DirectXMan12** [comment]
there's not currently a list, no

**Comment by hasbro17** [comment]
Just chiming in since I've stumbled across this issue. That list above is only a showcase of operator projects. It's not for operators scaffolded with the Operator SDK. Quite a few of them actually use Kubebuilder. E.g https://github.com/microsoft/azure-databricks-operator

Although I'm not aware of a good way to curate such a list and keep it updated. Or if that's even worth doing. Even in projects where users volunteer this information (https://etcd.io/docs/v3.3.12/production-users/) those lists can become stale.
