### ISSUE TITLE
Why two different log packages?

### ISSUE THREAD

**Issue by jaypipes** [kubernetes-sigs/kubebuilder#1269]
I'm wondering why the manager's `main.go` uses the `sigs.k8s.io/controller-runtime/pkg/log/zap` library:

https://github.com/kubernetes-sigs/kubebuilder/blob/19458ba88aa88a2fcc240cd9cf69bc88b4388d5b/pkg/scaffold/v2/main.go#L139

the webhook generator uses the `sigs.k8s.io/controller-runtime/pkg/log` package as well:

https://github.com/kubernetes-sigs/kubebuilder/blob/19458ba88aa88a2fcc240cd9cf69bc88b4388d5b/pkg/scaffold/v2/webhook/webhook.go#L94

but the controller uses the `github.com/go-logr/logr` library:

https://github.com/kubernetes-sigs/kubebuilder/blob/19458ba88aa88a2fcc240cd9cf69bc88b4388d5b/pkg/scaffold/v2/controller.go#L74

Would it be beneficial to standardize on a single package?

/triage support

**Comment by DirectXMan12** [comment]
> I'm wondering why the manager's main.go uses the sigs.k8s.io/controller-runtime/pkg/log/zap library:

`pkg/log/zap` is a helper for setting up logr with Zap.  Logr is a generic logging interface.  Zap is one concrete implementation.

> the webhook generator uses the sigs.k8s.io/controller-runtime/pkg/log package as well

`pkg/log` is a helper for cases where you haven't plumbed through a copy of `logr.Logger` and want a handle to a semi-global logger

That being said, it's actually using `pkg/runtime/log`, which is a deprecated path.  Not sure how that snuck into v2.  cc @mengqiy 

> but the controller uses the github.com/go-logr/logr library:

Right.  Most things should try to just pass down a copy of `logr.Logger` when they can.  When they can't, they can fall back to `pkg/log` if they need to.  Since the webhook code doesn't have its own struct to store the logger in, it has to use the global logger for the moment.

**Comment by DirectXMan12** [comment]
/good-first-issue

on the replacement of `pkg/runtime/log` for `pkg/log` in *just* the v2 scaffolding.

**Comment by jaypipes** [comment]
Thanks very much for the background @DirectXMan12! :) I'll try to hop on this contribution early next week.

**Comment by mengqiy** [comment]
@jaypipes That's a bug got snuck in.
Thanks for catching and trying to fix it! Feel free to assign me when you have the PR.

**Comment by dionysius** [comment]
Confirm that as well to move from `pkg/runtime/log`  to `pkg/log`

```
api/v1/sampleresource_webhook.go:6:2: SA1019: Package sigs.k8s.io/controller-runtime/pkg/runtime/log is deprecated: use pkg/log  (staticcheck)
        logf "sigs.k8s.io/controller-runtime/pkg/runtime/log"
```

**Comment by mengqiy** [comment]
It seems no PR has been opened to fix the bug.
@camilamacedo86 Do you have bandwidth to fix this bug? It should be a straightforward one.
