### ISSUE TITLE
Docs cleanup

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1279]
The book needs to be cleaned up.

- [ ] The files are not completely up-to-date and the tutorial should be followed step by step and checking the differences in the code as tracked in #1251 
- [ ] Is the folder `/docs/book/src/migration/testdata` being used for anything? It should be removed if it isn't. Why should we have a `testdata` folder that is the one used by the golden script inside one of the book chapters?
- [ ] Several files related to the old documentation like migration from v0, gifs, or some files that look like the utils used for previous versions of the documentation before moving to the new book format are still found in this directory

/kind cleanup

**Comment by vaibhavk** [comment]
Hi, I would like to work on it.
/assign

**Comment by Adirio** [comment]
@vaibhavk the first point should be pretty straightforward. Just follow the tutorial in a new project and doccument the differences in the file.

Second point requires to verify that the testdata directory is not used for anything, and remove it.

Third would require deep undestanding of the whole book creation process.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

Following a few comments inline. 

> The files are not completely up-to-date and the tutorial should be followed step by step and checking the differences in the code as tracked in #1251

It shows a duplicate of #1251 so I think that can be removed from the scope of this issue. I mean the repo has another issue already to address the same. Also, the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1492/files probably address it. 

> Is the folder /docs/book/src/migration/testdata being used for anything? It should be removed if it isn't. Why should we have a testdata folder that is the one used by the golden script inside one of the book chapters?

The `/docs/book/src/migration/testdata` is used just in the migration guide to help users move forward from V1 to V2. Since V1 was deprecated to long and has no longer supported I think we could remove the migration guide and the testdata dirs on it. WDYT? 

>  Several files related to the old documentation like migration from v0, gifs, or some files that look like the utils used for previous versions of the documentation before moving to the new book format are still found in this directory

I think the above would solve this one as well. WDYT?

**Comment by camilamacedo86** [comment]
HI @mengqiy @droot, 

Do you think that we could remove the V1 to V2 migration guide as a solution to close this one?

**Comment by Adirio** [comment]
I listed them to remember we need to do it but I don't have enough knowledge of the inner workins of how the documentation is generated to really know if those files are being used somewhere or they aren't.

**Comment by camilamacedo86** [comment]
HI @Adirio, 

Sorry, shows that have some misunderstand. Following some comments inline order to clarify.
- The first item of the list is duplicated of #1251. So, IMO should not be here
- The second list of the item is `/docs/book/src/migration/testdata` which shows quite safe be removed at this point. See:  https://github.com/kubernetes-sigs/kubebuilder/pull/1499 
- IMO: I should not migrate to the migration guide. We can create new ones when required. It is a doc that should exist with its steps as history. We just do not need to keep `/docs/book/src/migration/testdata` because it is not really adding value to the information, v1 is deprecated/not supported and currently removed. I mean the `/docs/book/src/migration/testdata` is not required for users to migrate their projects and follow up the steps. 
- And then, I understand that the third item of this list would be also solved.

**Comment by Adirio** [comment]
Yeah, I understood you correctly. What I mean is, if we have the migration guide (v1->v2) we keep the corresponding testdata folder, if we remove that guide we remove the folder.

**Comment by camilamacedo86** [comment]
added all detailed reasons why in POV is quite safe to delete the example of a V1 project that is just used in the migration guide from V1 to V2 in the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1499#issuecomment-628038450
