### ISSUE TITLE
webhook marker path updatable or not?

### ISSUE THREAD

**Issue by dionysius** [kubernetes-sigs/kubebuilder#1333]
Markers are usually hints on for the generated code output, which is true here. Are markers meant to be to allow the developer to change the value?

I'm asking this because the [marker for webhooks](https://book.kubebuilder.io/reference/markers/webhook.html) `+kubebuilder:webhook:path` is actually not customizable, since [this path is hardcoded](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/webhook.go#L118) and there is no way to specify the matching path for the controller code.

/triage support

**Comment by mengqiy** [comment]
This is true if you are using the `Defaulter` and(or) `Validator` interfaces from controller-runtime for your CRD. In this case, we generate the path for you to avoid conflicts between webhook paths.

The path is customizable otherwise. e.g. Write a webhook for built-in types.

I'd like to hear more about your use case why customizing path is important for you.

**Comment by dionysius** [comment]
It's not important for me that it can't be changed, but it is important to me, that it is documented, that this shouldn't be changed or things break. That's all. The usual me expected a marker - after consulting the documentation of that marker - to be changeable.

**Comment by mengqiy** [comment]
The document for the webhook marker has been updated in https://github.com/kubernetes-sigs/controller-tools/pull/353/files.
