### ISSUE TITLE
Testing with operator-sdk ??

### ISSUE THREAD

**Issue by mjshariati98** [kubernetes-sigs/kubebuilder#1336]
Is it possible to test an operator that weitten with kubebuilder, with oeprator-sdk framework for e2e testing ?

**Comment by hasbro17** [comment]
@mjshariati98 Not yet.

Besides the fact that SDK and Kubebuilder have different layouts for operator manifests, a Kubebuilder project's `config` directory has Kustomize bases and patches, unlike the SDK's deployment directory which has complete manifests scaffolded.
https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md#running-the-tests

So while it might be possible, it would be troublesome to pass the `operator-sdk test` cmd the complete operator manifests output from `kustomize build`. And even then there might be issues.

However we are currently working to integrate Kubebuilder's scaffolding into the SDK so in the future it should be possible for `operator-sdk test` to work on Kubebuilder projects since SDK projects would have the same layout and workflow as Kubebuilder's.
See: 
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md
- https://github.com/kubernetes-sigs/kubebuilder/pull/1250

In the meanwhile you can try to use [envtest](https://book.kubebuilder.io/reference/testing/envtest.html) for integration tests in your Kubebuilder project.

And as for using the Operator SDK test-framework for non-SDK layouts, it's probably better if you can follow up by opening an issue on the SDK repo.

**Comment by hasbro17** [comment]
@mjshariati98 If that answers your question feel free to close the issue. If not, you can follow up on the SDK repo if it's more specifically about the test-framework.

**Comment by mjshariati98** [comment]
@hasbro17 thanks for your answer.
Is there a good example or documentation for e2e test for an operator ?

**Comment by hasbro17** [comment]
@mjshariati98 The envtest package might be a good place to start for operators using controller-runtime.
https://book.kubebuilder.io/reference/testing/envtest.html
Just be aware of the last section at the end that mentions that you're not testing against an actual cluster with envtest so there are some caveats.

And if it's a project scaffolded with the Operator SDK then you can take a look through the test-framework docs which walks through an example for writing e2e tests that will run against an actual cluster.
https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md

**Comment by hasbro17** [comment]
Closing this issue since after the SDK integrates Kubebuilder CLI, we're dropping support for test-framework in favor of envtest as the recommended way to write integration tests.

(Not sure I have permissions to close the issue though)

/close
