### ISSUE TITLE
Cleanup go unit tests

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#1342]
There are some go unit tests in kubebuilder to test the generated files match expected.
Given that we have the [golden files test](https://github.com/kubernetes-sigs/kubebuilder/blob/master/golden_test.sh), we can cleanup our go unit tests.
We can probably only keep the tests for testing the scaffolding machinery, but not for each generated file.
Maintaining go unit tests requires more efforts than the golden test, since whenever a new file is added or a file is deleted, we need to change the go test to reflect it.

2 actionable items:
- [x] remove go unit tests for scaffolding files
- [ ] ensure enough coverage for the scaffolding machinery

**Comment by camilamacedo86** [comment]
HI @mengqiy, 

The golden tests are e2e tests and have not the same purpose as the unit tests. See that the golden will not cover all scenarios cases as the unit does. IHMO they have different purposes and both should be kept. Also, unit tests are faster and allow us to check, debug and ensure specific points locally which is very helpful for the development purpose. And then, in POV we should add more unit tests instead of just keep the golden one.   

Regards `remove go unit tests for scaffolding files` I understand that it has a completed different purpose. The scaffold tests are to help users test their projects then they are very valuable to them. See for example https://github.com/operator-framework/operator-sdk/issues/2467 a user asking for we scaffold tests for all gen code. However, IHMO it is also a point that should be improved since I do not think that is a good strategy we force users to do their tests using BDD and third-party APIs. See that BDD is may not the best approach for all scenarios and we may have users that would like or not working with them. Also, third-party APIs can be discontinued at any moment which would cause a not good experience for its users since that would mean re-duo all tests implementations in their projects too. So, over this point, I think we should scaffold tests using the go test framework provide in the language/stack instead of.  

Wdyt? Is it make sense?

**Comment by Adirio** [comment]
I think the name of unit tests brings a bit of confussion because they were really like e2e tests disguised as unit tests. They were basically creating a file in memory and checking it against the testdata folder. They were probably left-over code from before golden test was being used for this purpose. The discussion me and @mengqiy were having that brought up his issue was that these disguised tests were overlapping with the golden test and were way harder to maintain as new files required to write additional tests, where the golden test will already understand new files without requiring changes to the tests.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

Thank you for the clarification.  I checked the tests removed at #1343 and they are like the same e2e done in the golden tests as you said. So, for one side make since removing the duplication in order to ensure the changes performed. 

However, IMHO would be great we cover the project with unit tests at least since they will allow covering more scenarios cases. Also, tests implementing using go are faster and allow us to check, debug and ensure specific points locally which is very helpful for the development purpose which indeed I would advocate in prol of the usage of go test framework instead of third-party APIs as well.
