### ISSUE TITLE
More detailed contributor doc for how to test locally

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#1357]
Given that kubeubilder currently have many different types of tests (linters, test.sh, e2e, golden, etc), we should have more detailed contributor doc for how to test locally in
https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-test-kubebuilder-locally

**Comment by camilamacedo86** [comment]
HI @mengqiy, 

It was done  here: https://github.com/kubernetes-sigs/kubebuilder/pull/1432
Also, in order to give more visibility, the book/docs have a link for the contribution guidelines a well done in https://github.com/kubernetes-sigs/kubebuilder/pull/1494. 

So. I understand that your request made here is done. I am closing this one, however, please feel free to re-open and/or open another and ping me asking help if you see that it still requires more detailed information.   

/close
