### ISSUE TITLE
Webhook path is half hardcoded and half generated

### ISSUE THREAD

**Issue by ryanzhang-oss** [kubernetes-sigs/kubebuilder#1436]
Kubebuilder is heavily templated and given that there are next to none documentation around, the only place I can find for official help is the so called kubebuilder book.  [Here](https://book.kubebuilder.io/reference/markers/webhook.html) is what it says about the webhook.

However, in reality, the path is a trap.  In the controller-runtime (v0.4.0) pkg/builder/webhook.go:163, the path is auto-generated.  I changed the path in the webhook marker thinking that it is configurable without knowing it. Kubebuilder just silently generates the corresponding `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration` with the path I put in the webhook markers. I spent the next 2 days trying to figure out why I keep getting the following error
```
Error from server (InternalError): error when creating "addon-oam-kubernetes-local/config/samples/core_v1alpha2_manualscalertrait.yaml": Internal error occurred: failed calling webhook "manualscalertrait-mutate.kb.io": the server could not find the requested resource
```
Although I gained more experience with K8s in general, this experience makes me think twice before using kubebuilder again in any of my mission-critical projects.

Kubebuilder should either reject the wrong path or change the controller runtime to honor the path user specifies. 

What versions of software are you using?  Specifically, the following are often useful:

* go version.  1.13
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file) 
Version: version.Version{KubeBuilderVersion:"2.2.0", KubernetesVendor:"1.15.5", GitCommit:"0824a139f59e109c9e418a0b6e71a53c6e9e144f", BuildDate:"2019-11-20T00:00:24Z", GoOs:"unknown", GoArch:"unknown"}

* controller-runtime version (check your `go.mod` file)  v0.4.0
* controller-tools version.  v0.4.0
* Kubernetes & kubectl versions (just run `kubectl version` against your API server) v1.17.0

/kind bug

**Comment by devigned** [comment]
I ran into the same problem and lost a fair amount of time.

> Kubebuilder should either reject the wrong path or change the controller runtime to honor the path user specifies.

^ 💯

**Comment by DirectXMan12** [comment]
Ok, so, I'm going to lay out the problem here.  I recognize this might not seem particularly reasonable from a pure end-user perspective, but I want folks to understand what's going on here, and why fixing it is trickier than it seems.

The main problem is that these projects are intentionally somewhat loosely coupled.  It's supposed to be possible to use controller-runtime without controller-tools, and vice versa (and we have users that do just that).  This means that controller-tools doesn't really know what paths your code is serving on -- that's why you have to tell it.  Conversely, controller-runtime doesn't know what paths you generated your webhook for.  Unless we added code generation to controller-runtime (which I'm pretty iffy about), I don't see a good way to fix that.

That leaves KubeBuilder.  The problem is that KubeBuilder knows even less about your code than controller-runtime or controller-tools!  In order to reconcile the two, it'd have to somehow be able to figure out what paths your code was serving on, which is not really possible with static analysis -- you'd have to run the program to figure that out!

All this being said, if you have a concrete suggestion for how to fix this, I'd love to hear them.

**Comment by DirectXMan12** [comment]
And, FWIW, I agree that the DX is frustrating here, I just don't see a good path to fix it.

**Comment by DmitriGekhtman** [comment]
If anyone knows of a writeup that explains how to set up converting webhooks with KubeBuilder, let me know -- I'm having some trouble with it.

**Comment by DmitriGekhtman** [comment]
Resolved my troubles -- had some extra configuration I need to comment out:
https://github.com/kubernetes-sigs/kubebuilder/issues/2231#issuecomment-1510679638
