### ISSUE TITLE
[HELP] Got error when try to build base on v1.0.8

### ISSUE THREAD

**Issue by LinuxSuRen** [kubernetes-sigs/kubebuilder#1452]
I need an arm64 package of v1.0.8. I try to build it. But got the following errors:
```
+ goreleaser release --config=build/.goreleaser.yml --rm-dist --skip-validate

   • releasing using goreleaser 0.128.0...
   • loading config file       file=build/.goreleaser.yml
   ⨯ release failed after 0.00s error=yaml: unmarshal errors:
  line 14: field archive not found in type config.Project
```

Anyone could give a hint about this? I guess my goreleaser version is wrong.

/triage support

**Comment by camilamacedo86** [comment]
This version is very old. See that if you are using it then, you must be using 1.11 version as well and vendors instead of modules to work with. Also, `the v1 is deprecated since Feb 1, 2020. See how to upgrade your project to v2: https://book.kubebuilder.io/migration/guide.html.`

So, I think we should close this one. Please, feel free to re-open if you think that it still required. However, if you decided to re-open then, wdyt about provide the following info for we are able to help you with and the versions used?

> **What did you do?**
> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).


Really thank you for your attention and compression. 
I hope that it helps you with. 

/close
