### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by drpaneas** [kubernetes-sigs/kubebuilder#1479]
There are no contribution docs for kubebuilder. I think we could this as a new section to the https://book.kubebuilder.io which could potential include two sub-sections:

* How to contribute to the book
* How to contribute to the code

/kind documentation

**Comment by camilamacedo86** [comment]
HI @drpaneas, 

The contribution guideline is defined in the [Contribution.md](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md) in the repo. 

The `CONTRIBUTING.md` is a standard in the opensource projects in order to keep this information. However, please, feel free to open a pull request with a proposal to add it in the https://book.kubebuilder.io or to improve it. WDYT?

**Comment by drpaneas** [comment]
Good idea. I will work on it ;)

**Comment by drpaneas** [comment]
I read the contributing docs and it's pretty straight-forwards. I don't think it makes sense to duplicate this information to the book. I just added a link -- which is what I was missing basically, since it explains everything.

https://github.com/kubernetes-sigs/kubebuilder/pull/1494
