### ISSUE TITLE
Operator configuration

### ISSUE THREAD

**Issue by feloy** [kubernetes-sigs/kubebuilder#1509]
When an operator creates resources, for example a Deployment, some fields of the Deployment specs come from the CRD and others are "fixed" values provided by the operator.

It would be nice that kubebuilder provides a placeholder for a configmap or some generic tool that would contain the configuration for the operator.

/kind feature

**Comment by camilamacedo86** [comment]
Hi @feloy, 

I am not sure if I could understand your question/request. Kubebuilder will scaffold the project and apis, however, the CRD specs are implemented by you in its *_type.go. Also, any resource/object that you may like to manage via your project/controllers is implemented by you in the reconcile.

In this way, you have full control over what and how it should be done. You can find more information by following the tutorial or just open the hidden info in the quick start here: https://book.kubebuilder.io/quick-start.html.

**Comment by feloy** [comment]
As an example of what I would like to do, you can explore this repo: https://github.com/feloy/website-operator .

Especially, when the operator creates a Deployment, it uses some hardcoded values for resources requests/limits (see https://github.com/feloy/website-operator/blob/master/operator/controllers/static_deployment.go#L133). For separation of concerns reasons, I would like these values to be managed by the Ops team instead of the user that creates the CRD instance, and so, I would like to pass these values as configuration of the operator.

These configuration values could be passed to the operator via environment variables, a configmap, etc. I was wondering if some of you were using some kind of configuration of this sort, and how?

**Comment by camilamacedo86** [comment]
HI @feloy, 

>  For separation of concerns reasons, I would like these values to be managed by the Ops team instead of the user that creates the CRD instance, and so, I would like to pass these values as configuration of the operator.

So, you can define in the API the specs that you wish and then, add the values in the CRs which are instances of the CRDs. In the reconcile you will get these values from the spec of the CR which will be reconciled.  

The following are pieces of code as an example to do the exacly the same for you check how you can do it. I mean, for the same Deployment attributes indeed I am using values from the CR spec in my [personal](https://github.com/dev4devs-com/postgresql-operator) project built with SDK. It works at exactly the same way with projects which are made with Kubebuider. 

- See here the Deployment been created with the CR spec values. See: https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/resource/deployments.go#L90-L100

- See here the specs defined in the CR/Kind_type.go: https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/apis/postgresql/v1alpha1/database_types.go#L76-L86

- See here the CR which will be applied with the values: https://github.com/dev4devs-com/postgresql-operator/blob/master/deploy/crds/postgresql.dev4devs.com_v1alpha1_database_cr.yaml#L16-L17 

I'd like to recommend you follow up the [Kubebuilder Tutorial](https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html) it might be helpful to get how you can implement your projects.

**Comment by feloy** [comment]
Hi @camilamacedo86,

I effectively do this for some fields of the Deployment (here for example: https://github.com/feloy/website-operator/blob/master/operator/controllers/static_deployment.go#L115), but I would like to use *two* different sources of information for the values used to create resources (deployments, etc):

- values from the final user, through the CR, different for each CR,
- values from the DevOps team, through the operator configuration, common to all CRs.

I would really like to hide some values to the user and make them accessible only for the DevOps/SRE team.

**Comment by camilamacedo86** [comment]
HI @feloy, 

Following the comments inline.  

> - values from the final user, through the CR, different for each CR. 

Yes, each CR is instead of a CRD. The reconcile will get the values applied in the specific CR that it is reconciling. So, for example, if you apply in the namespace A the CR with values X the Deployment will be created with X. Then, if you apply in the namespace B another CR of the same CRD with values Y then the Deployment will be created with Y. 

> - values from the DevOps team, through the operator configuration, common to all CRs.

In this case, you can define in the code implementation something such as `If the value was not informed then use the default` or `you can use ENV VARs for the operator. E.g

- Define the environment variable in the `config/manager/manager.yaml`:

```yaml
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        env:
          - name: MY_ENV
            value: "ns1,ns2"
      terminationGracePeriodSeconds: 10
``` 

- Get EnvVar in the code:

```go
func getMyEnv() (string, error) {
	var myEnvVar = "MY_ENV"
	
	ns, found := os.LookupEnv(myEnvVar)
	if !found {
		return "", fmt.Errorf("%s must be set", myEnvVar)
	}
	return ns, nil
}
```

> I would really like to hide some values to the user and make them accessible only for the DevOps/SRE team.

K8S permissions are per resource and not for a specific value. For example, if you have a CRD Kind B then you can define what group of users is able to create/edit/update CRs of this Kind. See: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

So, what you could to do maybe is DevOps/SRE team are the only ones that have permissions in the namespace where the operator is deployed and then, in this way are the only ones that can edit its env vars. The other users have permissions in the namespaces B,C,D where the CR's can be applied. 

Also, you might find an interesting check https://operatorhub.io/. You can integrated your projects with OLM and provide them via a catalogue. There you also can find many examples of operators projects. 

I understand that your questions and mainly subject that made you raise this issue is sorted out and we can close this one. Do you not agree?

**Comment by feloy** [comment]
Thanks @camilamacedo86 for your feedback. I close the ticket
