### ISSUE TITLE
Using conversion-gen with multi-versioning

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1529]
Hi folks,
I have been wondering if there is an effective means for using conversion-gen to generate the conversions for the "rote conversions" as described at https://book.kubebuilder.io/multiversion-tutorial/conversion.html . It is of course possible to write up all conversions copying over most of the unchanged src spec to the dest but can get tedious (leading to typos !) with large CRDs with structure and repetitions across multiple versions. I did not see the multi-version examples use conversion-gen but it sounds like the tool that might help here. I am assuming other have been down this path. Thanks for any suggestions to make this simpler !

**Comment by madhurnawandar** [comment]
faced similar issue.  writing that logic is too much error-prone. Appreciate any help

**Comment by jgustie** [comment]
This was the approach we took recently, it amounted to:

1. In each spoke version packages, we added the `+k8s:conversion-gen` directive pointing to the hub version package (it must be in `docs.go`); we also added a `var localSchemeBuilder = &SchemeBuilder.SchemeBuilder` in `groupversion_info.go` so the auto-generated code would compile.
2. Update the make file to run `conversion-gen` on the spoke versions to produce a `zz_generated.conversion.go` in the spoke version package.
3. Add a `{kind}_conversion.go` to implement `Convertible` for each type. When `conversion-gen` stops generating methods because of incompatibilities or we need to override the behavior, we stick them in this source file.

When we implemented `Convertible`, we just used the local `SchemeBuilder.Build()` to get a new scheme (the auto-generated code will register the necessary conversion methods because of the variable declaration) and used it to call `Convert`; i.e.:

```
$(CONVERSION_GEN) --go-header-file "./hack/boilerplate.go.txt" --input-dirs "./api/{spokeversion}" \
		--output-base "." --output-file-base="zz_generated.conversion" --skip-unsafe=true
```

```
package {spokeversionpkg}

import (
	"{hubversionpkg}"
	"k8s.io/apimachinery/pkg/conversion"
	conv "sigs.k8s.io/controller-runtime/pkg/conversion"
)

var _ conv.Convertible = &MyKind{}

func (in *MyKind) ConvertTo(hub conv.Hub) error {
	s, err := SchemeBuilder.Build()
	if err != nil {
		return err
	}
	return s.Convert(in, hub.(*{hubversionpkg}.MyKind), nil)
}

func (in *MyKind) ConvertFrom(hub conv.Hub) error {
	s, err := SchemeBuilder.Build()
	if err != nil {
		return err
	}
	return s.Convert(hub.(*{hubversionpkg}.MyKind), in, nil)
}
```

**Comment by camilamacedo86** [comment]
Shows that it was sorted out, so I am closing this one. however, please feel free to raise new issues and/or contributing to the project as well, for example, by raising a PR with a doc for that.

**Comment by wreed4** [comment]
@camilamacedo86  Has this made it into the tool or any of the documentation?  I've been trying to figure out how to do this for a few days now and a simple example would be incredibly helpful.

**Comment by LittleWat** [comment]
@wreed4 There is an example using conversion-gen. (it is not a simple one though...)
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/main/api

I asked another question related to this
https://github.com/kubernetes-sigs/kubebuilder/discussions/2889
