### ISSUE TITLE
[kubebuilder-book] Need kubebuilder-book Chinese version

### ISSUE THREAD

**Issue by Miss-you** [kubernetes-sigs/kubebuilder#1545]
hi, Kubebuilder is an SDK framework for building Kubernetes APIs based on CRDs, allowing users to quickly develop and build APIs, Controllers and Admission Webhooks from scratch using Kubebuilder.

I used it to develop the Ingress controller some time ago and benefited a lot from it. The only regrets are that there is less documentation for Chinese people and the kubebuilder-book is in English.

So, I'm translating the kubebuilder-book while using kubebuilder, and expect to finish the `cronjob controller` chapter this week!

link: https://github.com/Miss-you/kubebuilder-book

**Comment by zehuaiWANG** [comment]
It would be great to have a translation. Thank you for your contribution.

**Comment by vsxen** [comment]
add example project code?
https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/

**Comment by Miss-you** [comment]
Hi. My translation is a little slow due to time constraints.
However, our community 'Cloud Native CN', has organized some people to start translating the kubebuilder-handbook.
https://cloudnative.to/kubebuilder/

**Comment by camilamacedo86** [comment]
Hi @Miss-you, 

It is great 🥇 . @lhb008 is working on that in the issue https://github.com/kubernetes-sigs/kubebuilder/issues/1651. 
See that we create a branch to push these changes. https://github.com/kubernetes-sigs/kubebuilder/tree/book-v2-zh.
Feel free to contribute with it as well and push PR's against to this branch.   

I hope that is fine we close this one since we have the  https://github.com/kubernetes-sigs/kubebuilder/issues/1651 as well. However, please feel free to ping us if you think that it should be re-opened.
