### ISSUE TITLE
Create s390x binaries for kubebuilder

### ISSUE THREAD

**Issue by varunpal7** [kubernetes-sigs/kubebuilder#1591]
Parent task :[966](https://github.com/kubernetes-sigs/kubebuilder/issues/966)

**Comment by varunpal7** [comment]
Following a similar approach to the PR here - https://github.com/kubernetes-sigs/kubebuilder/pull/979.
Made changes in my fork - https://github.com/varunpal7/kubebuilder w.r.t s390x.

Cloned the fork in my machine having s390x architecture.

Ran the steps from the following link on `how to build kubebuilder locally`- https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md.

But when i run `make go-test` getting the below error:

```
go test -race -v ./cmd/... ./pkg/...
go test: -race is only supported on linux/amd64, linux/ppc64le, linux/arm64, freebsd/amd64, netbsd/amd64, darwin/amd64 and windows/amd64
Makefile:72: recipe for target 'go-test' failed
make: *** [go-test] Error 2
```
Any suggestions why i am getting this error ?

**Comment by varunpal7** [comment]
Trying to build locally but getting the following error:

```
Step #4: go: extracting golang.org/x/text v0.3.0
Step #4: # sigs.k8s.io/kubebuilder/pkg/model/file
Step #4: pkg/model/file/errors.go:40:9: undefined: errors.As
Step #4: pkg/model/file/errors.go:60:9: undefined: errors.As
Step #4: note: module requires Go 1.13
Step #4: # sigs.k8s.io/kubebuilder/pkg/plugin/internal/filesystem
Step #4: pkg/plugin/internal/filesystem/errors.go:46:9: undefined: errors.As
Step #4: pkg/plugin/internal/filesystem/errors.go:67:9: undefined: errors.As
Step #4: pkg/plugin/internal/filesystem/errors.go:88:9: undefined: errors.As
Step #4: pkg/plugin/internal/filesystem/errors.go:109:9: undefined: errors.As
Step #4: pkg/plugin/internal/filesystem/errors.go:130:9: undefined: errors.As
Step #4: pkg/plugin/internal/filesystem/errors.go:151:9: undefined: errors.As
Step #4: pkg/plugin/internal/filesystem/errors.go:172:9: undefined: errors.As
Step #4: note: module requires Go 1.13
Step #4: 
Finished Step #4
2020/07/14 12:43:55 Step Step #4 finished
2020/07/14 12:43:55 status changed to "ERROR"
ERROR
ERROR: build step 4 "gcr.io/kubebuilder/goreleaser_with_go_1.12.5:0.0.1" failed: exit status 1
2020/07/14 12:44:11 Build finished with ERROR status
```

Can someone please help ?

**Comment by camilamacedo86** [comment]
Hi @varunpal7, 

Sorry for teh delay. It shows that go version in the build files. See the pr: https://github.com/kubernetes-sigs/kubebuilder/pull/704/files

It should be https://github.com/kubernetes-sigs/kubebuilder/blob/master/go.mod#L3. Also, this issue shows a duplication of : https://github.com/kubernetes-sigs/kubebuilder/issues/1694.

**Comment by camilamacedo86** [comment]
regards Hi @varunpal7, 

Sorry for the delay. It shows an error with the go version required to build files. `ERROR: build step 4 "gcr.io/kubebuilder/goreleaser_with_go_1.12.5:0.0.1" failed: exit status 1`

It should be https://github.com/kubernetes-sigs/kubebuilder/blob/master/go.mod#L3. Also, all shows that this error will be addressed in the issue; https://github.com/kubernetes-sigs/kubebuilder/issues/1694. 

And then, regards create 390x binaries for kubebuilder we have an issue to do do that as well. Would be really nice to get your help with. See; https://github.com/kubernetes-sigs/kubebuilder/issues/1491

I am closing this one since shows duplicated. However, please feel free to ping to re-open it if you see that still required.
