### ISSUE TITLE
Is there a compatible matrix?

### ISSUE THREAD

**Issue by pigletfly** [kubernetes-sigs/kubebuilder#1592]
Should we add a compatible matrix to readme or kubebuilder book?

**Comment by camilamacedo86** [comment]
IMO the recommendation would be to use the versions that are provided by the tool in the scaffold since these are the versions which are tested and check. You might find out that has scenarios where would possible to upgraded your downgraded some dep, however, is very hard we know what should or not work in each scenario to provide a range of possibilities/compatibilities. So, for example, if you would like to upgrade the versions used you can use an upper version of the tool and check the latest combination. 

@DirectXMan12 wdyt? Do you agree with the above information? would you like to supplement this one?

**Comment by pigletfly** [comment]
What I means here is which go and k8s version goes well with kubebuilder version.Or kubebuilder doesn't care the version of go and k8s?

**Comment by camilamacedo86** [comment]
Hi @pigletfly,  

Related to the versions supported see the **Prerequisites** section in the [quick-start](https://book.kubebuilder.io/quick-start.html): 

> Prerequisites
> - go version v1.13+.
> - docker version 17.03+.
> - kubectl version v1.11.3+.
> - kustomize v3.1.0+
> - Access to a Kubernetes v1.11.3+ cluster.

Currently, the go version supported with the latest version release and master is 1.13. You should not use it with 1.12 since you will face the issue and it might work with 1.14 but it is not tested and in this way not officially supported besides I have no knowledge so far over problems faced with. 

And then, note that when you generated a project with a version X of the tool you will see that the modules versions are fixed in your go.mod. **Example**

```
go 1.13

require (
	github.com/go-logr/logr v0.1.0
	github.com/onsi/ginkgo v1.11.0
	github.com/onsi/gomega v1.8.1
	k8s.io/apimachinery v0.18.2
	k8s.io/client-go v0.18.2
	sigs.k8s.io/controller-runtime v0.6.0
)
```

So, regards the dependencies, for example: 

```
	k8s.io/apimachinery v0.18.2
	k8s.io/client-go v0.18.2
	sigs.k8s.io/controller-runtime v0.6.0
```

I understand that; the recommendation is you use the version scaffolded by the tool. In this way, for example, if you would like to upgrade your project to use an upper version of `sigs.k8s.io/controller-runtime` you are able to do it. However, I'd recommend you upgrade your project to use a new version of the tool and use its upper versions to ensure the compatibilities between the modules and features because it is very hard to say if you will or not face some issue with different combinations of the modules since they might not be compatible or have breaking changes that can or not affect your implementation and customizations made so far. 

Also, if the default scaffolded project has breaking changes you will see that a migration guide is provided to help users move forward as it was done from V1 to V2 Projects.

**Comment by pigletfly** [comment]
thanks for your elaboration. /close
