### ISSUE TITLE
Make namespace configurable

### ISSUE THREAD

**Issue by pigletfly** [kubernetes-sigs/kubebuilder#1613]
/kind feature

Now we are using system namespace for CRD deployment in scaffolds, I think it's better to make it configurable.Because the default `system` namespace may not exists, and also we may want to put different CRDs in different namespaces.

**Comment by camilamacedo86** [comment]
Hi @pigletfly, 

Shows that when you run the make targets for the project it will scaffold a new namespace which is the "projectName"+"-system" and apply all manifest on it. So, the namespace will always exist since it is created as well. 

Also, check that for v3 we will be able to configure the project name. See https://github.com/kubernetes-sigs/kubebuilder/pull/1609.

However, users are able able to o customizations on their project Makefile as well. Please, let us know if it makes sense and if you still have seen something that could be addressed in the default behaviour. If yes, could you please describe what/where and provide use cases that justify the feature request?

**Comment by camilamacedo86** [comment]
/asign @camilamacedo86 

HI @pigletfly, 

As described above with #1609 (valid just for v3+) allow users to configure the project name. The namespace is created via the default configuration and workflow by default always then the scenario `default system namespace may not exists` shows that not valid. 

Feel free to test it with the master branch by using the v3+ plugin such as:

E.g:

> kubebuilder init --plugins=go/v3-alpha --domain=tutorial.kubebuilder.io --project-version=3-alpha --repo=tutorial.kubebuilder.io/project --license apache2 --owner "The Kubernetes authors"

However,  users are also able to customize their projects by updating the files scaffolded as the Makefile as please them to for example change the namespace where the project will be deployed. 

So, your concern here shows addressed already and because of this, I am closing this RFE. However, feel free to re-open if you see that has something that could be addressed yet. 

/close
