### ISSUE TITLE
Working with custom marshalling ?

### ISSUE THREAD

**Issue by eddycharly** [kubernetes-sigs/kubebuilder#1646]
Is there a way to workaround types with custom marshalling ?

Those types typically don’t have json tags and therefore generate type Any in the open api schema. 

See this for example https://github.com/tektoncd/pipeline/blob/8df31f7358c381e4fc97b6cb51b90897dd8115cd/pkg/apis/pipeline/v1beta1/param_types.go#L86-L93

/triage support

**Comment by eddycharly** [comment]
Why not just add `x-kubernetes-preserve-unknown-fields: true` on the node and omit the offending field ?

**Comment by camilamacedo86** [comment]
Hi @eddycharly. 

Shows that your problem was regards the versions used.  We have tasks and PR to working in the upgrade of the versions to use v1. The problem faced by you is not faced in all currently support clusters versions too but it will be addressed soon in v3+. 

See PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1644 and the issue  #933. 

Closing this one as a duplicate of  #933. However, please feel free to ping us and re-open it if you need or raise a new issue all info as the steps and versions used ok?
