### ISSUE TITLE
Chinese version for Kubebuilder docs are available and want to be merged.

### ISSUE THREAD

**Issue by majinghe** [kubernetes-sigs/kubebuilder#1651]
Hi team
Cloud Native Community in China already translated the Kubebuilder docs into Chinese, now Chinese version is available on https://cloudnative.to/kubebuilder/. Community wants to confirm is it possible to merge the Chinese docs into the Kubebuilder main repo? Thanks

**Comment by camilamacedo86** [comment]
Hi @lhb008, 

I think it shows great. Unfortunately, I believe that none of its owners/admins knows Chinese and would be really hard for our keep maintained many languages.it will need to rely on the community contributions. So, IMO we need clarifies that the English docs are mainly maintained just in case it gets outdated. At least, Chinese users will be able to have the thought/light to try to check the English version if something gets wrong.

WDYT about we replace English for English (Official)? And then, have you any idea over a way of we make people beware of that as well? I hope that I could clarify my concern and I am open a better way the communicate and let them beware of that.

@DirectXMan12 @pwittrock @gabbifish any suggestion ? WDYT?

**Comment by camilamacedo86** [comment]
/kind documentation
kind feature

**Comment by DirectXMan12** [comment]
@camilamacedo86 I talked to some folks, I think we have official language docs reviewers for the Kubernetes project.  We should be able to have them do reviews/basic checks of the docs, and then merge.  I'll file a bug in the SIG docs repo and see about getting stuff reviewed.

@lhb008 can you open a PR with the book contents?  We might want to create a separate branch and subdomain for them

**Comment by camilamacedo86** [comment]
HI @lhb008, 

I'd like to know if you would like to help us to achieve it? WDYT? Please, feel free to ping me if you need any help.

**Comment by lhb008** [comment]
@camilamacedo86  Sorry to reply this so late. It is great for us community(China Cloud Native Community). I will open a PR for Chinese docs.

**Comment by lhb008** [comment]
I have opened a PR https://github.com/kubernetes-sigs/kubebuilder/pull/1736.  Our community has already created a new branch `zh` to store the chinese docs. For the continuous update in the future, we can find a right way to do this, for example, if there is new feature for kubebuilder, you can tell our community, we will translate this into chinese, anyway, our community will focus on this always to help user in China to get the available chinese docs.

**Comment by lhb008** [comment]
Hi  @camilamacedo86 . What do you think about to create a new branch to store chinese docs, then i can open the PR with the corresponding chinese docs branch?

**Comment by camilamacedo86** [comment]
Hi @lhb008, 

Currently, we have: 

- [book-v2](https://github.com/kubernetes-sigs/kubebuilder/tree/book-v2): book.kubebuilder.io -- current docs
- [book-v1](https://github.com/kubernetes-sigs/kubebuilder/tree/book-v1): book-v1.book.kubebuilder.io -- legacy docs
- master: master.book.kubebuilder.io -- "nightly" docs 

In SDK, we had a proposal for that see: https://github.com/operator-framework/operator-sdk/pull/3376 whcih would be in the same branch. By looking on the @DirectXMan12 comment https://github.com/kubernetes-sigs/kubebuilder/issues/1651#issuecomment-689869770 it might need to be another branch which I understand that would need to be something such as `book-v2-zh` where we would have the current docs in Chinese. 

In this way, I think that after the releases, as a post-action, would be required to always push the master changes to the `book-v2-zh` as we do for the book-v2. So, the Chinese community could be working on that to keep this branch updated and with the translations.  I'd recommend you start to do this work from the master branch since we will probably do a release soon and it has doc changes. WDYT?

**Comment by lhb008** [comment]
Hi @camilamacedo86 . Actually,  our [chinese translation](https://cloudnative.to/kubebuilder/) is based `master` branch. A new branch `book-v2-zh` will be ok for chinese docs, if possible, could you please help to create the new `book-v2-zh` branch first, then i will create the chinese docs PR for this new branch. In the future, if english docs changes(pushed changes to `master` branch), Our community will follow the changes and push the changes to `book-v2-zh` branch. How do you think about his process?

**Comment by camilamacedo86** [comment]
Hi @lhb008, 

The branch is created. Please feel free to push your changes against it. See https://github.com/kubernetes-sigs/kubebuilder/tree/book-v2-zh
