### ISSUE TITLE
Make dry-run to get manifests.yaml

### ISSUE THREAD

**Issue by cargaona** [kubernetes-sigs/kubebuilder#1693]
Hi! During last weeks I've been developing an operator and noticed that there is no clear way to obtain the manifests for the resources we generate. 

So I edited the makefile to get a "make dry-run" command which writes all the manifests for deploying the Operator in a "dry-run" folder.

```make
dry-run: manifests
	cd config/manager && kustomize edit set image controller=${IMG}
	mkdir -p dry-run
	kustomize build config/default > dry-run/manifests.yaml
```
I think it can help making things faster. 

/kind feature

**Comment by camilamacedo86** [comment]
Hi @noquarteer, 

Thank you for share. I am not sure if I got your motivation. So, I'd like to share that usually the steps are as describe in the [quick-start](https://book.kubebuilder.io/quick-start.html) which means that when we run `make deploy IMG=<some-registry>/<project-name>:tag` all manifests will be applied on the Cluster. 

So, could you please help me understand better why you need to move them to dry-run/manifests.yaml? Are you looking for have a single file with all to check it? What is the need that are you trying to solve with?

**Comment by noquarteer** [comment]
Hi Camila!
Make deploy works great. But it applies everything to the cluster and I don't get the yaml files being applied. What I want by adding this dry-run is to get the yaml files that are going to be applied to the cluster instead of applying them. Something like helm --dry-run does. 

Since i'm working on a operator that will be deployed in various clusters, I can distribute this manifest file to install the operator in all of them. I don't want the developers who are going to use it to clone the repo and installing through their terminal by making make deploy.

**Comment by camilamacedo86** [comment]
Regards the distribution I'd like to recommend you check the [OLM](https://github.com/operator-framework/operator-lifecycle-manager). You can integrate your projects with OLM and provide them in a catalogue whcih can be internal or public. See https://operatorhub.io/ to have a better idea. 

[SDK](https://github.com/operator-framework/operator-sdk) 1.0+ can help you integrate your kubebuilder projects with OLM as well.  

For Helm, the purpose of "Dry Run" is to validate that the output of the chart will actually work if sent to the server which shows not the same purpose with these target. IMO the default Makefile needs the common target with are useful for th bigst part of th cases and in order to keep it maintainability we can suggest to userss customize it as they wish. 

However, if you wish I think that we could add that in the https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/reference/makefile-helpers.md. WDYT? Would you like to do a PR for that?

**Comment by noquarteer** [comment]
Sounds good to me. I will submit a PR soon for makefile-helpers. 
Thanks for your help!

**Comment by camilamacedo86** [comment]
it is done closing this one.
