### ISSUE TITLE
CLI: it would be helpful to skip PROJECT reads for extra commands

### ISSUE THREAD

**Issue by jmrodri** [kubernetes-sigs/kubebuilder#1755]
It would be helpful to skip `PROJECT` file reads for extra commands. `kubebuilder version` will throw an error if an errant `PROJECT` file exists. I do not expect this for `version` or other extra commands.

For example,

```
$ kubebuilder version
2020/10/29 12:19:36 failed to read the configuration file: read PROJECT: is a directory
```

I expected the `version` and extra commands to ignore the `PROJECT` file/directory. 
```
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}
```

To reproduce:

```
mkdir PROJECT
kubebuilder version
```

This also affects the `operator-sdk` because we use the `kubebuilder` cli. I've tracked down some of the interaction.  Starting from [`cli.New`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/cli/cli.go#L86) which always calls [`c.initialize()`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/cli/cli.go#L99). This fails with the following error: [`FATA[0000] failed to read config: read PROJECT: is a directory`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/cli/cli.go#L201) because of the errant `PROJECT` file. With most commands it is useful and/or required to read the `PROJECT` file but for something like `version` or other extra commands I believe it isn't required. 

/kind bug

**Comment by Adirio** [comment]
The CLI is fine if no project configuration file exists (`PROJECT` is just a name, lets not use that term) as there are some subcommands (like `kubebuilder init`) which obviously don't expect a configuration file to exist previously. In the initalize method we are checking if the file exists or doens't exist and proceed appropiately. But when reading the file, other errors may happen and we need to detect these. We may need to split the commands that require a project configuration file and those that don't, and only trying to read the file in the first case.

/cc @estroz

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

The problem raises here is that to run the extra commands the CLI it is checking if the PROJECT file is created or not and then, in this case, the check should not be made. Also, we might have plugins which not requires the PROJECT file so it should not be required by default. 

Example of the scenario; 

- We have the `command version` as an extra command.
```
var commands = []*cobra.Command{
	version.NewCmd(),
}
```

- Then, we consume the CLI from kubebuilder in another project

```go
c, err := cli.New(
		cli.WithCommandName("mybin"),
		cli.WithPlugins(
			&golangv2.Plugin{},
			&helmv1.Plugin{},
			&ansiblev1.Plugin{},
		),
		cli.WithDefaultPlugins(
			&golangv2.Plugin{},
		),
		cli.WithExtraCommands(commands...),
	)
	if err != nil {
		log.Fatal(err)
	}

```
If we run `mybin version ` it will fail with the error that the PROJECT file is missing when should not. 
PS.: Its motivation came from SDK. See that [this project](https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/operator-sdk/cli/cli.go#L57) is doing it and if the command `operator-sdk version` be called the issue will be faced.

**Comment by Adirio** [comment]
@camilamacedo86 the error comes from the `makedir PROJECT`. We already support commands with no project configuration file (for example, `kubebuilder init` is one of them). What we currently do is check if the file exists, then load and read thwe configured version. If reading the file gives a "file not exist" error we just consider it as not-configured yet and proceed. The problem is that reading the file may yield other types of errors, in this case it says that the file exists but it is a directory so we can't read it, and that's why the bug is happening.

Now we have two solutions:
1. The same way we consider "file not exist" errors to mean that the project is not configured, we can consider "file is a dir" errors to do the same. Fast fix that will work for this specific case out of the way. But there will be other cases in the future and we will have to add more exceptions to this list ("file not exist", "file is a dir", ...) which is not a very good approach.
2. Try to make the CLI work without reading the file at all until neccesary. This will be safer for the future as we won't need to keep adding exceptions but will require to change the cli initialization process.

I was trying to evaluate how much work would the second approach need and evaluate if it was worth it.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

I close my previous comment to not make it confusing. I checked with @jmrodri the scenario. Following the steps to reproduce:

```
cd /tmp
mkdir PROJECT
kubebuilder version
2020/11/02 11:25:41 failed to read config: read PROJECT: is a directory
```

It is considered the directory PROJECT as a file. We need only looking for a file with this name.

**Comment by Adirio** [comment]
It uses the project file to try to guess the project version and the plugin layout, which gets saved in that file. But I do agree that we may be able to move that check after we know that it is needed by the subcommand. Some validation from the CLI would need to be dropped though, like having plugins for the proper version as we won't be able to know the version of the project without reading the file.

**Comment by Adirio** [comment]
@jmrodri #1828 should solve this issue. Would you mind verifying it? You would need to clone that PR's branch and build the source code from it. If you need further help you can contact me on Slack or post a comment here.

**Comment by jmrodri** [comment]
@Adirio i will check it out today. Thanks for the PR.

**Comment by jmrodri** [comment]
With the patch from PR #1828 applied, this issue is fixed.

```
$ mkdir PROJECT
$ /home/jesusr/dev/kubebuilder/bin/kubebuilder version
Version: main.version{KubeBuilderVersion:"v2.3.1-391-gf260cc8e", KubernetesVendor:"unknown", GitCommit:"f260cc8ea59e64b444c4b2cf0a40da2fb61f635e", BuildDate:"2020-11-23T20:09:54Z", GoOs:"linux", GoArch:"amd64"}
```
