### ISSUE TITLE
Investigate using edit command to turn on and off ComponentConfig

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/kubebuilder#1821]
As of https://github.com/kubernetes-sigs/kubebuilder/pull/1790 we are adding the ability to scaffold a project where the config is loaded from a file, it would be nice if we could use the `kubebuilder edit` command to switch that on and off.

This issue is to track if it's possible and if not why. 

Existing conversation - https://github.com/kubernetes-sigs/kubebuilder/pull/1790#discussion_r518270527

/kind feature

**Comment by camilamacedo86** [comment]
My idea over it would be: 

`kubebuilder edit --component-config=[true/false]` which will:

- Update the PROJECT file componentConfig for true/false
- Replace the default manager scaffold in the main. See: https://github.com/kubernetes-sigs/kubebuilder/pull/1790/files#diff-6d104501fc7dc73bb67118a31ea122a23d55af27d443c7b96029054238978a36R233-R252. Also, if the user customize its implementation will not possible to do the replace than a WARN should be outputed.  
- Comment/Uncomment :` - manager_auth_proxy_patch.yaml` in the `config/default/kustomize.ymal`. See; https://github.com/kubernetes-sigs/kubebuilder/pull/1790/files#diff-e1b4379535ca15931f7ad4adb74878e79f40de8732b5a25f060c7628988f12deR74-R77

**Comment by camilamacedo86** [comment]
This issue was not accepted in the bug triage meeting. the community concern is mainly related to updating the main file when it has customization as well. Also, shows not too hard to enable and disable this setup manually by following the tutorial.   

In this way, this one can be closed. However, we can re-open always if someone else brings a good argumentation for it.

**Comment by christopherhein** [comment]
Sounds good, thanks for closing this,
