### ISSUE TITLE
How is this SVG image generated？

### ISSUE THREAD

**Issue by Devying** [kubernetes-sigs/kubebuilder#1859]
How is this SVG image generated

https://raw.githubusercontent.com/kubernetes-sigs/kubebuilder/master/docs/gif/kb-demo.v2.0.1.svg

**Comment by camilamacedo86** [comment]
Hi @Devying, 

You might find what you are looking for by searching for such as [how to generate a svg from a gif](https://www.google.com/search?q=how+to+geneerate+a+svg+from+a+gif&oq=how+to++geneerate+a+svg+from+a+gif&aqs=chrome..69i57.5532j0j7&sourceid=chrome&ie=UTF-8)

Since your question is not really related to the tool resonsabilities I hope that is fine we close this one. However, please feel free to raise new issues if you need to.

**Comment by Devying** [comment]
thank you
