### ISSUE TITLE
go get sigs.k8s.io/kubebuilder@latest gets v1.0.8

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#1863]
Steps to reproduce:

- `cd $(mktemp -d)`
- `go get sigs.k8s.io/kubebuilder@latest`

This is cause `pkger` to break as it tries to get the latest kubebuilder and then can't find `sigs.k8s.io/kubebuilder/v2`

**Comment by Adirio** [comment]
#1791 talks about this. Basically `go mod` expects us to add `v2` to the import path and module name in order to be able to find it. This change has been applied to the code, but no release has been made since then. I think we may want to back port this change to older `kubebuilder` release branches and release a fix for them so that we don't have to wait until `v3` is ready.

**Comment by pwittrock** [comment]
Ack.  I can work around this for now.

**Comment by Adirio** [comment]
v2.3.2 released which should make `sigs.k8s.kubebuilder/v2` available
