### ISSUE TITLE
Is there any best practice to wait for pod ready in reconciler?

### ISSUE THREAD

**Issue by mjaow** [kubernetes-sigs/kubebuilder#1965]
I have a scenerio:

1. My controller will watch for a cr created and start to reconcile
2. create several pods for it
3. mark cr status to be unknown (pending) 
4. after all pods ready, I'll mark cr status to be ready

Do we have any best practice to wait util all pod ready? I can think of two approach, not quite sure about the best practice

1. keep waiting and polling status in reconciler util all pods are ready
2. check if they are ready, if not , trigger a reconcile by setting requeueAfter for several seconds

/triage support

**Comment by shawn-hurley** [comment]
I would personally suggest that unless you have a good reason otherwise, freeing the reconciler thread to respond to more other actions would be the correct approach, so 2. 

I can imagine there are cases that maybe this isn't what you always want like all things there are trade offs :)

**Comment by Adirio** [comment]
Freeing the reconciler is definetely the best practice. You may not need to requeue if you modify its status to unknown as this change itself will trigger another reconcile loop.

My logic would be:
- If the CR has no status set, create the pods and set status to pending, or waiting or something like that (unknown doesn't seem the best status for this)
- If the CR status is pending, check if the pods are ready:
    - If they are ready set status to ready
    - If they are not ready, check if there is any action to take and requeue (here we do need a requeue because we are not updating the CR)
-  If the CR status is ready, check if the pods are ok:
    - If they are ok, skip
    - If they are not ok, take actions (like relaunching and setting status to pending, or whatever logic you want.

I'm closing this as it seems that @shawn-hurley's answer above solved your question because you didn't comment any further. If you still need support, reopen it.
/close
