### ISSUE TITLE
kubebuilder update vendor fails if Gopkg.toml doesn't exist

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kubebuilder#197]
A nice new option `--overwrite-dep-manifest` defaulted to `false` was introduced by #140 to make sure we preserve user dependencies if `Gopkg.toml` exists. However, this breaks the previous `kubebuilder` behavior if a project does not have a `Gopkg.toml` checked-in, because we assume we're updating the file and since the flag is defaulted to `false`, we fail with:

```
2018/05/21 18:03:42 error upgrading the dep manifest (Gopkg.toml): open Gopkg.toml: no such file or directory
```

What should be the desired behavior here? Should we:
1. expect users to pass in this new flag if `Gopkg.toml` doesn't exist?
1. update `kubebuilder` to generate `Gopkg.toml` if it doesn't exist and `--overwrite-dep-manifest` is `false` (the default)?

**Comment by pwittrock** [comment]
Probably *2.* with a message saying it is creating the Gopkg.toml because it is missing.

@font If you have any interest in filing a PR to fix, I would be happy to review it.  Should be around this line:

https://github.com/kubernetes-sigs/kubebuilder/blob/master/cmd/kubebuilder/initproject/vendor.go#L102

**Comment by droot** [comment]
Ideally, users should check-in `Gopkg.toml` and `Gopkg.lock` files to ensure reproducibility of the vendor dependencies. In a way, these files should be treated like any other files generated by KB. 

About the desired behavior, second option seems to be the way to go because most of the users would invoke the second option anyways.

**Comment by font** [comment]
@pwittrock Will do!

@droot Yes, I tend to agree.
