### ISSUE TITLE
reconcilation is called twice

### ISSUE THREAD

**Issue by yalctay93** [kubernetes-sigs/kubebuilder#1976]
Hello,

I am facing the issue that my reconcile function requeues once every time I do any CRUD operation on my CR.
For example, I have a "route" CR for my Operator. The reconcile function is called in route_controller.go whenever I CRUD a route object however, it always is requeued after the first run.

So for example if I create a route object, my reconcile function is called and does something. It immediately does the same thing again - and after that reconcilation is stopped and I cannot figure out why it is queued twice.

Any ideas on why this could be happening? I only have one worker as far as I know and only one instance of my operator deployed with make run on my minikube environment.

Thanks!

**Comment by Adirio** [comment]
This is a common situation, your reconcile function should be able to understand that it has nothing to do and return early for these cases. The causes can be many. For example, are you modifying the route object in the reconcile loop? In that case is obvious why the controller sees another update to the resource. The reconcile function should be idempotent.

**Comment by yalctay93** [comment]
> This is a common situation, your reconcile function should be able to understand that it has nothing to do and return early for these cases. The causes can be many. For example, are you modifying the route object in the reconcile loop? In that case is obvious why the controller sees another update to the resource. The reconcile function should be idempotent.

I do add annotations to my route object, after certain operations are done in the route_controller.go
So you say that these actions queue the same item again?

How would I prevent the controller to requeue tht object?

**Comment by Adirio** [comment]
> I do add annotations to my route object after certain operations are done in the route_controller.go
> So you say that these actions queue the same item again?

Exactly

> How would I prevent the controller to requeue tht object?

You don't. It will be requeued, but when you receive an object what you need to do is check if something has changed and only performs actions for this. In your case you could, for example, check if the annotations are already set and not set them in that case. The "certain operations are done" part needs something similar, you check if they have already be done for the current reconciling route and don't do anything then. A common approach is to store a hash of the route in its status, by hashing the route object itself (except for its status). In your reconcile loop you first compute the expected hash, fi it matches the stored one means that no change was made to the spec. If it doesn't, something was changed, so do the updates you need to do, run the operations you need to run, and update the hash to the new one so that following requeues of this object without a modification to its spec will not run them again.

**Comment by yalctay93** [comment]
Thanks for the insight - I will probably resort to the status field and store a hash value like you explained, is it considered best-practice? Is there any best-practice how to handle such things?

**Comment by yalctay93** [comment]
> > I do add annotations to my route object after certain operations are done in the route_controller.go
> > So you say that these actions queue the same item again?
> 
> Exactly
> 
> > How would I prevent the controller to requeue tht object?
> 
> You don't. It will be requeued, but when you receive an object what you need to do is check if something has changed and only performs actions for this. In your case you could, for example, check if the annotations are already set and not set them in that case. The "certain operations are done" part needs something similar, you check if they have already be done for the current reconciling route and don't do anything then. A common approach is to store a hash of the route in its status, by hashing the route object itself (except for its status). In your reconcile loop you first compute the expected hash, fi it matches the stored one means that no change was made to the spec. If it doesn't, something was changed, so do the updates you need to do, run the operations you need to run, and update the hash to the new one so that following requeues of this object without a modification to its spec will not run them again.

I have implemented this approach just now and it works flawlessly. Thank you alot!
