### ISSUE TITLE
Question about the tutorial book (`api/v1/cronjob_webhook already exists` when executing kubebuilder create webhook --group batch --version v1 --kind CronJob --conversion)

### ISSUE THREAD

**Issue by chenliu1993** [kubernetes-sigs/kubebuilder#2103]
Hi experts, I am starting learning the basic of kubebuilder from the online tutorial book. And I am currently on Chapter 2 <MultiVersion API>. But I hit some issues here. It is about the kubebuilder command.

When I run `kubebuilder create api/webhook --group batch --version v1/v2 --kind CronJob (--conversion)` I always got an error like `api/v1/cronjob_webhook already exists` or `controllers/cronjob_controller.go already exists`. seems that these files will be created again when executing the `create` cmd. Is this expected? Or I am using somewhere wrong?

And another one is that even the error above showed up, but some files are still generated like `api/v2/cronjob_types.go`, but like zz_generated_deepcopy.go is not gened under v2 group, why? I have to copy it manually to make go errors run away.

Thank you

**Comment by Adirio** [comment]
Command calls are not idempotent. This means that if you run a `kubebuilder create api/webhook` twice you are not guaranteed to end in the same state. The reason why idempotency cannot be guaranteed is because some files are meant to be modified, either by the operator developer (you) manually coding some parts or by other command calls inserting code fragments at certain locations. We have three scaffolding policies that determine the behavior when scaffolding a file that already exists:
- Skip: for example, `api/vX/groupversion_info.go` only needs to be scaffolded for the first API, so if it is found already, we just skip scaffolding it again.
- Overwrite: for example, `go.mod` may be present before the initalization command call, we overwrite if with our desired one which includes the required dependencies.
- Error: for example `api/vX/*_types.go`. It is a file that we do not expect to be there before calling its corresponding create API command (we cannot skip) and that is expected to be modified by the operator developer (we cannot overwrite), so we can only return an error.

The other issue we are facing is that we do not guarantee atomicity right now. It is a desired feature (#1956) but it is hard to achieve. Atomicity guarantees that no file will be scaffolded in case of error and all files are scaffolded if succeeded. Right now, if a file fails, for example for the reason mentioned above, the files before it will be scaffolded but the files after it won't. The exact file you are mentioned is auto-generated with `make generate` but there are other files that are missing when you see that error that are not generated that way. (`make generate` is called after all files have been scaffolded in a create API command call but as some failed it didn't reach that point.)

**Comment by chenliu1993** [comment]
Thank you Adirio, very detailed explanation! Really helpful!
