### ISSUE TITLE
Add deprecated information for API

### ISSUE THREAD

**Issue by morvencao** [kubernetes-sigs/kubebuilder#2116]
As the API evolves, we need to deprecate some fields in the old version of API, looks like the [openSchema-v3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject) supports `deprecated` in the CRD, but I didn't find the corresponding marker to make the deprecated information automatically generated.

Can anyone guide me how to achieve that?

Also, the field deprecating validation can be implemented by the openSchema V3, even if we don't enable validation webhook, right?

/triage support

@camilamacedo86

**Comment by hasheddan** [comment]
@morvencao it looks like the marker has been [added in `controller-tools`](https://github.com/kubernetes-sigs/controller-tools/blob/ecaffbc2dc09cd5e09c07b692d899dbbc8fdda0e/pkg/crd/markers/crd.go#L52). I imagine this will be included in `v0.6.0`.

**Comment by morvencao** [comment]
thanks @hasheddan

**Comment by erikgb** [comment]
This issue is closed, and `kubebuilder:deprecatedversion` works - I use it! But it is missing from the docs. I would expect it to be here: https://book.kubebuilder.io/reference/markers/crd.html. I've tried digging into the doc-generation, but got lost. Maybe @camilamacedo86 knows how the marker-gendocs works here? I am not sure if I should open an issue (and file a PR) here in kubebuilder, or in https://github.com/kubernetes-sigs/controller-tools. 🤔

**Comment by christian1607** [comment]
Yep, the marker for deprecatedversion works, you could also specify the message warning:

`//+kubebuilder:deprecatedversion:warning="example.com/v1alpha1 CronTab is deprecated"
`
