### ISSUE TITLE
Scaffold Ginkgo tests in a dedicated directory and run with the Ginkgo CLI

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes-sigs/kubebuilder#2171]
## Proposal

1. Scaffold ginkgo tests with envtest in a separate directory - `test/integration`
2. Scaffold the Makefile to install the Ginkgo CLI (as is done with other go tooling)
3. Scaffold a dedicated `test-integration` make target, which invokes the integration test suite via the Ginkgo CLI
4. Scaffold a dedicated `test-unit` make target, which invokes `go test` on the directories that kubebuilder generates on init.
5. Update the scaffolded `test` make target to invoke the new `test-unit` and `test-integration` targets.

## Motivation

When scaffolding controllers with Kubebuilder, the generators create Ginkgo test suite code that sits in the same directory and package as the controller code. Ginkgo tests are then invoked via the default make targets, using `go test ./...`, with Envtest providing a kube apiserver suitable for integration level tests.

There are several downsides to this approach:

1. It encourages developers to use Ginkgo for all testing, or forces developers to mix Ginkgo tests with standard Go unit tests in the same package.
2. It restricts the capabilities of what can be done with Ginkgo tests. There are several options in the ginkgo CLI which are not available via a `go test` invocation.
3. The scaffolded ginkgo suite bootstraps Envtest, which may be overkill for unit tests.

Moving the scaffolded Ginkgo tests to a dedicated `test/integration` directory helps communicate that tests with Envtest are meant to be integration tests. Envtest out of the box gives developers the assurance that they are doing the right thing with respect to apiserver calls, but does not capture how the controller will behave on a real cluster. Creating a top-level `test` directory will also encourage developers to invest in test code, and extend their integration tests further (ex - "e2e" tests against a real cluster).

With the Ginkgo scaffold tests moved out, developers will be encouraged to write standard Go unit tests alongside the controller code. This is considered accepted practice in the go community - many go developers are resistant to using Ginkgo or other non-standard tools for unit testing.

## Prior Work

A previous proposal to remove ginkgo/gomega as the preferred testing tool was closed [1], since go tests by themselves are not effective for testing Kubernetes controllers.

This proposal does not remove these capabilities. It instead moves the ginkgo tests to a separate directory that by default cannot access private methods in the `controller` package. This encourages black box, behavior driven test designs, which is where Ginkgo shines as a testing tool.

[1] https://github.com/kubernetes-sigs/kubebuilder/issues/822 

### Aditional Info:
If you would like to work on it please check : https://github.com/kubernetes-sigs/kubebuilder/issues/2171#issuecomment-865868608

**Comment by estroz** [comment]
https://github.com/kubernetes-sigs/kubebuilder/issues/822#issuecomment-506887995 argues against your point (1), an argument I personally agree with. Ginkgo/Gomega encourages clean, readable test code and has _a lot_ of facilities that the std testing library lacks. People tend to supplant it with a testing framework for this reason. I think it's ok for kubebuilder to be opinionated about this.

That does not preclude the validity of points (2) and (3) however, although I see envtest-reliant code as e2e tests rather than integration. If anything, I'd take a hybrid of your approach:
- Move all test code relying on envtest to `test/e2e/`
- Scaffold a non-envtest Ginkgo/Gomega suite in `controllers/`
- Create Makefile targets to run e2e, unit, and e2e+unit tests

**Comment by strideynet** [comment]
I think encouraging a ``test/e2e`` similar to that in the Kubernetes repository also makes a lot of sense for testing Controllers.   I've been following this practice on my kubebuilder generated projects and allows me to invest in longer more complicated tests without worrying about the time it takes for the suite to run. As a result, I can run ``go test ./...`` for cheap unit/integration tests when iterating quickly locally, but still enforce E2E tests passing on pull requests.

Overall, I disagree that Ginkgo/Gomega are necessary for writing tests in Go, but as that issue has already been discussed and closed, this seems like a next best option to encourage engineers to use standard go testing as much as possible, reserving Ginkgo/Gomega for the E2E tests. I would definitely challenge the statement that "People tend to supplant it with a testing framework for this reason.". Relatively few projects are using testing frameworks, the Kubernetes source is more an exception than a rule and whilst I can't recall it exactly, I do seem to remember several k8s contributors complaining about the usage of ginkgo/gomega.

**Comment by camilamacedo86** [comment]
By following the Golang good practices the tests should be with the code implemented then, I do not think that is a good idea create these dedicates directories proposed here.

**Comment by estroz** [comment]
>like a next best option to encourage engineers to use standard go testing as much as possible, reserving Ginkgo/Gomega for the E2E tests

That's not what the closed issue or I am saying, so how did you come to the conclusion that this the next best option? Using two different testing paradigms is even more confusing. BDD testing is a super common paradigm in many languages, so it's not like kubebuilder is asking users to do something esoteric.

>Relatively few projects are using testing frameworks, the Kubernetes source is more an exception than a rule and whilst I can't recall it exactly, I do seem to remember several k8s contributors complaining about the usage of ginkgo/gomega.

Got any data to back that statement up? When I search ginkgo or gomega in github I see quite a few projects pop up, and that's just one framework. I don't see how "several k8s contributors complaining" constitutes a will to move away from those testing libraries. If anything, it shows that the majority of people don't feel strongly enough to complain, or are at least ok using those libraries.

There will always be a community split on testing libraries. You can generalize that statement to any code community and any library. _In my opinion_, Go's std testing library is barebones and BDD is great, especially for new Go users since BDD is persistent across languages. If you prefer another testing library, kubebuilder should make it easy to rip out one testing library for another, which is mainly what I'm saying above.

**Comment by camilamacedo86** [comment]
These seems a subject that ought to be raised in [Kubebuilder, Controller Runtime, and Controller Tools](https://docs.google.com/document/d/1Ih-2cgg1bUrLwLVTB9tADlPcVdgnuMNBGbUl4D-0TIk/edit#heading=h.dp4gt7gj3cn). Could you please do that?

**Comment by camilamacedo86** [comment]
Hi @adambkaplan, 

This RFE was discussed in the latest  [Kubebuilder, Controller Runtime, and Controller Tools](https://docs.google.com/document/d/1Ih-2cgg1bUrLwLVTB9tADlPcVdgnuMNBGbUl4D-0TIk/edit#heading=h.dp4gt7gj3cn) and after further consideration, we reach a consensus that not all here would be beneficial for Kubebuilder and/or SDK. 

Note that to do unit tests you would work on with the fake client and then that is not something that controller-runtime and kubebuilder which is the tool that leverage on it would like to encourage users to use it at all. More info: https://github.com/kubernetes-sigs/controller-runtime/issues/768. Note that also is a good practice in Golang to keep the tests with the files.

Ditto so, what was discussed and accepted to be done would add an attr field to the PROJECT file which would allow users to disable the default tests scaffolds such as it is done to configure the layout to support multi-group via the edit command, see: 

https://github.com/kubernetes-sigs/controller-runtime/issues/768

In this way, would you like to contribute with it? If yes, please feel free to push a PR with it.
