### ISSUE TITLE
Generating markdown document for CRD

### ISSUE THREAD

**Issue by ymmt2005** [kubernetes-sigs/kubebuilder#2198]
### What do you want to happen?

I would appreciate it if kubebuilder scaffolds Makefile rules to generate markdown documents for CRDs.

In my project, I'm using [clamoriniere/crd-to-markdown](https://github.com/clamoriniere/crd-to-markdown) to generate such documents as follows:

https://github.com/cybozu-go/moco/blob/87c2e817d8011268f7ae06219efc5b553422cb6d/Makefile#L59-L62

An example markdown file for one of my CRDs is https://github.com/cybozu-go/moco/blob/main/docs/crd_mysqlcluster.md

**Comment by camilamacedo86** [comment]
Hi @ymmt2005, 

After the discussion in the bug triage, we think that this might not fit for all developers/use cases so that would make hard it to be added in the default scaffolds. Also, kb tries to avoid add third-party dependencies. 

In this way, that seems a need that would take advantage of the vision that we have for phase 2.0 plugins, see https://book.kubebuilder.io/plugins/creating-plugins.html#future-vision-for-kubebuilder-plugins. To know more about the plugin see: https://book.kubebuilder.io/plugins/plugins.html.  

It means that in the future the CLI would able to discover plugins and allow you to use them to do default customizations in your organization. However, also feel free to attend the meetings and re-raise this topic if you wish. 

In this way, I hope that is fine we close that for now.

**Comment by ymmt2005** [comment]
Understood.  Thank you for taking your time.
