### ISSUE TITLE
Can we get the OpenApi JSON created automatically when we get the autogenerated crd spec

### ISSUE THREAD

**Issue by ravipwaghmare** [kubernetes-sigs/kubebuilder#2278]
### What do you want to happen?

So i was working on multiple controllers. 
Where I got one requirement to provide the Open API JSON for the project. 
So it was not possible to handle multiple controllers Kustomization file to change it to open api.
Is there any way we can achieve it.

When we do any change in the spec and run make install 
we get the autogenerated kustomization file with the CRD specs
Can we also get the OpenAPI JSON  along with it?
So it will be easier to document the project.

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi  @ravipwaghmare,

OpenAPIv3 schemas are added to CRD manifests in the `spec.validation` block when the manifests are generated. This validation block allows Kubernetes to validate the properties in a Memcached Custom Resource when it is created or updated.

[Markers][markers] (annotations) are available to configure validations for your API. These markers will always have a `+kubebuilder:validation` prefix.

Usage of markers in API code is discussed in the kubebuilder [CRD generation][generating-crd] and [marker][markers] documentation. A full list of OpenAPIv3 validation markers can be found [here][crd-markers].

To learn more about OpenAPI v3.0 validation schemas in CRDs, refer to the [Kubernetes Documentation][doc-validation-schema].

[markers]: https://book.kubebuilder.io/reference/markers.html
[crd-markers]: https://book.kubebuilder.io/reference/markers/crd-validation.html
[generating-crd]: https://book.kubebuilder.io/reference/generating-crd.html
[doc-validation-schema]: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

Closing it since we have indeed it doc already. However, feel free to ping us in the channel if you need or let us know if you think that it should to be re-opened.
