### ISSUE TITLE
Adding support for s390x architecture

### ISSUE THREAD

**Issue by rposts** [kubernetes-sigs/kubebuilder#2298]
### What do you want to happen?

Currently `Kubebuilder` releases binaries for several platforms including `arm64` and `ppc64le`.

I am exploring the possibility of making binary available on `s390x` big-endian architecture.

I am able to successfully build and run `test-unit` on `s390x` architecture with following changes to `Makefile`:
```diff
index 2d69e6f4..23575c1a 100644
--- a/Makefile
+++ b/Makefile
@@ -102,7 +102,11 @@ test: test-unit test-integration test-testdata test-book ## Run the unit and int

 .PHONY: test-unit
 test-unit: ## Run the unit tests
+ifeq (s390x,$(shell uname -p))
+       go test -v ./pkg/...
+else
        go test -race -v ./pkg/...
+endif

 .PHONY: test-coverage
 test-coverage: ## Run unit tests creating the output to report coverage
```
However, `make test` fails because it downloads incompatible [`kubebuilder-tools`](https://storage.googleapis.com/kubebuilder-tools) from `googleapis` storage location.

I suspect in order to add `s390x` support we will require the following two steps at a minimum:
- Make available `s390x` compatible `kubebuilder-tools` on https://storage.googleapis.com/kubebuilder-tools
- Modify `Makefile` to remove `race` option for `s390x` architecture

I am looking for direction on how to make this possible so that `s390x` arch `Kubebuilder` can be obtained directly from the [`Releases` ](https://github.com/kubernetes-sigs/kubebuilder/releases) page.

Thanks.

**Comment by rashmigottipati** [comment]
assign @camilamacedo86

**Comment by camilamacedo86** [comment]
/remove-lifecycle stale

I think we need to revisit this one.

**Comment by tdaleibm** [comment]
@camilamacedo86 I'm not sure I fully understand the process but I see you are doing a similiar for arm64 in bug #2664 , are you able to trigger on the Google Cloud to generate the artefact for s390x ? I was able to workaround `make test` by sideloading with setup-envtest, All three binaries (kubectl, kube-apiserver, etcd)  already have s390x builds available. What more is required to get this on https://storage.googleapis.com/kubebuilder-tools?

**Comment by tdaleibm** [comment]
Sorry, I meant the individual packages usually contained in kubebuildre-tools ( so kubectl, kube-apiserver, and etcd ). I'm not sure how to packaging of those into https://storage.googleapis.com/kubebuilder-tools is being done for other architectures.

**Comment by rposts** [comment]
/remove-lifecycle stale @camilamacedo86 just checking if there is something I could do at my end to assist - tx!

**Comment by camilamacedo86** [comment]
I added needs-triage on this one. I think we can discuss it can. 
Also, freeze for it not to be closed.

**Comment by camilamacedo86** [comment]
After further discussions on the KB meeting at Aug 25, it was decided to accept this one.
Maybe we could use docker buildx to provide this support.

**Comment by jmrodri** [comment]
The operator-sdk project supports s390x, the latest release shows we have s390x binaries: https://github.com/operator-framework/operator-sdk/releases/tag/v1.23.0

**Comment by camilamacedo86** [comment]
@jmrodri @rposts @tdaleibm, 

To accomplish this one we need to:

- a) Ensure that envtest-tools ( https://storage.googleapis.com/kubebuilder-tools ) are built for this arch. To know how to do it see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/RELEASE.md#to-build-the-kubebuilder-tools-artifacts-required-to-use-env-test (we need to check the branch)

- b) ensure that the auth-proxy-image scaffold by default in the projects provides this support, see that we will also need to change another branch: https://github.com/kubernetes-sigs/kubebuilder/blob/master/RELEASE.md#to-build-the-kube-rbac-proxy-images

- c) Then, we have a PR open where we are adding a new target to allow authors to generate the manager image using multiple platforms: https://github.com/kubernetes-sigs/kubebuilder/pull/2906 (assuming that this one gets merged we will need update the nodeAffinity info to add this one and the new target) 

TL'DR: Following the comments about https://github.com/kubernetes-sigs/kubebuilder/issues/2298#issuecomment-1227480907

@jmrodri in SDK we are generate the scorecard and kuttle images with this support. Probabably ansible/helm images. However, the projects are scaffolded with two images/workloads. One is the, kube-rbac-proxy which is managed by kubebuilder (so that it is not providing this support) and the manager image itself is built by the author and we do neither provide a helper so far to allow them to build this one with multiple architecture support.

**Comment by rposts** [comment]
@camilamacedo86 seems like [kube-rbac-proxy](https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy) image is building for `s390x`. This should bring us a step closer? Please let me know how we can resume this work. Thanks!

**Comment by camilamacedo86** [comment]
Closing this one as sorted out.

**Comment by rposts** [comment]
Thanks @camilamacedo86 - can we expect `s390x` binary available in the next release?

**Comment by camilamacedo86** [comment]
It was closed by mistake. 

We still missing generate the envtest and CLI binary:
More info: https://github.com/kubernetes-sigs/kubebuilder/issues/2298#issuecomment-1242994510

**Comment by rposts** [comment]
@camilamacedo86 I tried building the tools and it seems to work - I presume this is what is needed by `envtest` (?):
```
# wget https://raw.githubusercontent.com/kubernetes-sigs/kubebuilder/tools-releases/build/thirdparty/linux/Dockerfile
# docker build --build-arg OS=linux --build-arg ARCH=s390x --build-arg KUBERNETES_VERSION=v1.29.0 -t kbld .
# docker run --rm -it kbld sh
/ # ls
bin                             lib                             root                            tmp
dev                             media                           run                             usr
etc                             mnt                             sbin                            var
home                            opt                             srv
kubebuilder_linux_s390x.tar.gz  proc                            sys
/ # tar xvfz kubebuilder_linux_s390x.tar.gz
kubebuilder/
kubebuilder/bin/
kubebuilder/bin/etcd
kubebuilder/bin/kubectl
kubebuilder/bin/kube-apiserver
/ # ls -larth kubebuilder/bin/
total 202M
-rwxr-xr-x    1 root     root      127.2M Jan 26 13:47 kube-apiserver
-rwxr-xr-x    1 root     root       51.4M Jan 26 13:47 kubectl
-rwxr-xr-x    1 root     root       23.5M Jan 26 13:47 etcd
drwxr-xr-x    3 root     root          17 Jan 26 14:01 ..
drwxr-xr-x    2 root     root          55 Jan 26 14:01 .
/ #
```

**Comment by camilamacedo86** [comment]
Hi @rposts,

The ENV TEST is used to run the tests.
The binaries are configured in your local ENV and executed when you run `make test`
See:  https://github.com/kubernetes-sigs/kubebuilder/blob/93d8fb8edb38682ae7b1fa354e72d759732faa94/testdata/project-v4/Makefile#L171-L174

Then, check some examples of code using ENV TEST to test out the controllers:
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/internal/controller/memcached_controller_test.go

I am looking for we setup the ARCH to build it. 
They are available in : https://storage.googleapis.com/kubebuilder-tools

However, I have a really good question.
Are your local env linux s390x? 
Why do you want run Kubuilder CLI on those envs?
Are you looking for the final solution works in a server s390x?

**Comment by rposts** [comment]
@camilamacedo86 I do have a local s390x build environment. It can also be obtained via [IBM LinuxONE Community Cloud](https://linuxone.cloud.marist.edu/#/register?flag=VM).

`Kubebuilder` is being used by certain projects to run/setup tests ([velero](https://github.com/vmware-tanzu/velero/blob/main/hack/build-image/Dockerfile) for example), and availability of this `kubebuilder` on `s390x` environment will help with the enablement effort.

Hope this helps. Thanks.

**Comment by camilamacedo86** [comment]
Hi @rposts 

> I do have a local s390x build environment.

Yes, that is helpful. That is precisely what I want to confirm; I want to ensure that people have local environments running in s390x. It would not make sense to have the tool and ENVTEST targeting it since you could, for example, develop in a Mac targeting an env s390x then; that means that the image built for your Manager would need to support s390x but not the CLI itself. 

Thank you for sharing.

**Comment by camilamacedo86** [comment]
Hi @rposts,

We have now the binaries for ENV TEST as well, see:

<img width="759" alt="Screenshot 2024-01-26 at 17 55 13" src="https://github.com/kubernetes-sigs/kubebuilder/assets/7708031/2f5669c3-1408-4fc1-a2f2-c98d848e3620">

Also, you have the image auth-proxy image built within already and you added the target arch to the Go releaser so we will have the binary for the next one: https://github.com/kubernetes-sigs/kubebuilder/pull/3741

In this way, we can close this one, Thank you for your help.
