### ISSUE TITLE
"create api" generates wrong import alias when using the "" group

### ISSUE THREAD

**Issue by armsnyder** [kubernetes-sigs/kubebuilder#2299]
### Expected

Supposing I initialize my Kubebuilder project with the domain "foo.example.com" and create a new resource "Foo", I expect the code generation to import that package as "foov1".

### Actual

The package import alias is generated as "fooexamplecomv1". In real world examples the alias can be quite a bit longer. Manually fixing the import alias is not an option, because when the next resource is generated, it adds a duplicate import statement and registers the schema twice. (See repro).

### Create a new project and first resource with no group

```bash
# Create a new project.
mkdir example
cd example
go mod init foo.example.com
kubebuilder init --domain foo.example.com
# Add a resource.
kubebuilder create api --version=v1 --resource --controller=false --group="" --kind Foo
cat main.go
```

### Result: Import alias is the full domain name

```go
...snip...

import (
	...snip...

	fooexamplecomv1 "foo.example.com/api/v1"
	//+kubebuilder:scaffold:imports
)

var (
	scheme   = runtime.NewScheme()
	setupLog = ctrl.Log.WithName("setup")
)

func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))

	utilruntime.Must(fooexamplecomv1.AddToScheme(scheme))
	//+kubebuilder:scaffold:scheme
}

...snip...
```

### Fix the import alias and add a second resource

```bash
# Fix the import alias.
sed -i '' 's|fooexamplecomv1|foov1|g' main.go
# Add a second resource.
kubebuilder create api --version=v1 --resource --controller=false --group="" --kind Bar
cat main.go
```

### Result: Duplicate import and duplicate `AddToScheme`

```go
...snip...

import (
	...snip...

	fooexamplecomv1 "foo.example.com/api/v1"
	foov1 "foo.example.com/api/v1"
	//+kubebuilder:scaffold:imports
)

var (
	scheme   = runtime.NewScheme()
	setupLog = ctrl.Log.WithName("setup")
)

func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))

	utilruntime.Must(foov1.AddToScheme(scheme))
	utilruntime.Must(fooexamplecomv1.AddToScheme(scheme))
	//+kubebuilder:scaffold:scheme
}

...snip...
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.1.0", KubernetesVendor:"unknown", GitCommit:"92e0349ca7334a0a8e5e499da4fb077eb524e94a", BuildDate:"2021-05-29T05:57:53+01:00", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

version: "3"

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```

### Other versions

go version go1.16.6 darwin/amd64

go.mod:
	k8s.io/apimachinery v0.20.2
	k8s.io/client-go v0.20.2
	sigs.k8s.io/controller-runtime v0.8.3

**Comment by armsnyder** [comment]
I realized my mistake. I assumed group would create a subdirectory inside `api` but actually it is what controls the import alias. All I had to do was run `create api` with `--group=foo` and it resulted in what I expected. Closing this issue.

**Comment by armsnyder** [comment]
I'm re-opening this bug because doing the above has the undesired effect of causing the CRD to be inside the group `foo.foo.example.com`.

```yaml
apiVersion: foo.foo.example.com
kind: Foo
```

**Comment by camilamacedo86** [comment]
Hi @armsnyder, 

The support for empty groups was added in: https://github.com/kubernetes-sigs/kubebuilder/pull/1679/files
If I follow up the steps added by you:

```
# Create a new project.
mkdir example
cd example
go mod init foo.example.com
kubebuilder init --domain foo.example.com
# Add a resource.
kubebuilder create api --version=v1 --resource --controller=false --group="" --kind Foo
cat main.go
```

I will check the import:
``` 
fooexamplecomv1 "foo.example.com/api/v1"
```

That seems expected since will be the <domain>/api/<version> where you will find all APIs created with empty group and the version `v1`

See that if you run `kubebuilder create api --version=v1 --resource --controller=false --group="" --kind Foo2` then the second APIs should also be created there. 

```
customresourcedefinition.apiextensions.k8s.io/foo2s.foo.example.com created
customresourcedefinition.apiextensions.k8s.io/foos.foo.example.com created
```

Then, if I run `make manifests`

```sh
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: foos.foo.example.com
```

I will see the expected `name: foos.foo.example.com` for that as well since is the kind in the plural and the domain. 
WDYT about close this one and raise a new one with the steps performed, the expected result and the result that you are checking?

**Comment by armsnyder** [comment]
From what I can tell there is no technical limitation here, only a somewhat bad user experience.

Imagine I want all my CRDs to have the domain "myorganization.mycompany.com". I would expect that I initialize kubebuilder with `--domain myorganization.mycompany.com`. However this results in overly verbose import aliases `myorganizationmycomanycomv1`.

The workaround (or intended usage, perhaps) is to initialize kubebuilder with `--domain mycompany.com` and then for each new CRD, set `--group myorganization`. To me this is annoying and unnecessary having to remember to set the group anytime I add a CRD.

**Comment by camilamacedo86** [comment]
Hi @armsnyder, 

In kb v1 the tool scaffolds the multi-group layout by default. However, looking for simplicity, since v2 we scaffold by default a layout or you would always work with only one group. However, that does not mean that you cannot have different groups in the same domain. See: https://book.kubebuilder.io/migration/multi-group.html

However, I agree with you that is annoying to inform many times the same value for the default layout. In this way, what do you think about the following suggestion:

- We add the group flag as an option to the init
- It will track the default group to the project file 
- Then, if the project has not multi-group enable and the flag group not be informed we would use the default group tracked for the project. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-multigroup/PROJECT#L4

Would you like to work on this solution?
Your PR and collab are very welcome.

**Comment by armsnyder** [comment]
Thanks for your response @camilamacedo86.

I agree it would be a nice improvement if you could initialize the project with a single group and not need to specify it in every subsequent kubebuilder command.

For my purposes though, I am ok with the current workaround of specifying `--group` on every command, and I do not think I would work on this improvement. I will leave it to someone else to open this as a new issue if they like. In the meantime I will close this bug since it seems to be working as intended.
