### ISSUE TITLE
Stop to use go get in favor of go install

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2477]
### What do you want to happen?

See that: `go get: installing executables with 'go get' in module mode is deprecated.`

	To adjust and download dependencies of the current module, use 'go get -d'.
	To install using requirements of the current module, use 'go install'.
	To install ignoring the current module, use 'go install' with a version,
	like 'go install example.com/cmd@latest'.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

Then, we need to fix the toolings, scripts and scaffolds

**Comment by ankitm123** [comment]
I can take a look this month, but as discussed on slack, there's 2 months to fix this ...
/assign

**Comment by ryantking** [comment]
I'm currently looking at this one for operator-sdk. So far kustomize has been problematic since it has `exclude` and `replace` directives in its go.mod file, which breaks `go install`. I'm currently looking at just using the kustomize install script instead of `go install`. @ankitm123 let me know if you come to any alternative solutions for this.

**Comment by bprashanth** [comment]
go 1.18 already requires this: https://go.dev/doc/go-get-install-deprecation

At the very least, the go-get-tool in the autogen Makefiles should be replaced with go install: https://github.com/kubernetes-sigs/kubebuilder/blob/acdede50a58a1b9ac7fa66fc335bc810fe9ef6f6/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L179
