### ISSUE TITLE
Failed to download version 3.2.0 

### ISSUE THREAD

**Issue by qyk1995** [kubernetes-sigs/kubebuilder#2517]
I  use command： curl -L -o kubebuilder https://go.kubebuilder.io/dl/v3.2/$(go env GOOS)/$(go env GOARCH)，But the download is an HTML file. The page address is  https://go.kubebuilder.io/releases/3.2.0/linux/amd64,But unable to download kubebuilder file.
please help me

**Comment by camilamacedo86** [comment]
Hi @qyk1995, 

You can check all assets for all versions, as download them by looking at https://github.com/kubernetes-sigs/kubebuilder/releases: 

<img width="683" alt="Screenshot 2022-02-22 at 09 51 15" src="https://user-images.githubusercontent.com/7708031/155135956-b464434c-ebd1-408c-8873-b43da3db8f5a.png">

However, in your case see that you are also using v3.2 instead of v3.2.0. You can check the instructions to download the KB CLI as well in: https://book.kubebuilder.io/quick-start.html

```sh
# download kubebuilder and install locally.
curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
chmod +x kubebuilder && mv kubebuilder /usr/local/bin/
```

In this way, it shows sorted out and I hope that you do not mind we close this one.
However, please feel free to raise new issues if you need.
