### ISSUE TITLE
Remove the `tools` package in favor of go 1.18 go install

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes-sigs/kubebuilder#2594]
## Objective
Compiling the dependent binaries using a special package `tools` can be replaced with `go install` as we are doing in the generated Makefile.

## Solution:
1. Remove the `tools` dir
2. Replace the installation of APIDiff in the Makefile with `GOBIN=$(shell dirname $(GO_APIDIFF)) go install github.com/joelanford/go-apidiff@latest`

**Comment by camilamacedo86** [comment]
Hi @AlmogBaku, 

Let's create an PR to do only this change
In its description, the **Motivation** can be add support to 1.18

**Comment by AlmogBaku** [comment]
Since this issue depends on https://github.com/joelanford/go-apidiff/issues/15 I suggest holding that

/hold

**Comment by camilamacedo86** [comment]
Hi @AlmogBaku, 

The apidiff on Kubebuilder is only used in the Ci - Github Action
 We can still using go 1.17 for its ci if the appdiff does not work with https://github.com/kubernetes-sigs/kubebuilder/pull/2561/files#diff-dd565f122600dd57c8c3c546dd80893fe3e96c09f41ef16886f908d6d0ce7b50R21 

Also, the new tools added to the project here: https://github.com/kubernetes-sigs/kubebuilder/commit/9e94fe0f67db3ba893a8288546d37b693adb0eff  shows a mistake. 

Why we need to import apidiff on the project at all?
It is not used by the CLI so that should not be imported in the go.mod at all.

**Comment by AlmogBaku** [comment]
Right now, the `make apidiff` does work because it uses an updated version of `golang.org/x/tools` from our go module.

Until https://github.com/joelanford/go-apidiff/issues/15 will be fixed, removing it will prevent developers from running `make apidiff` in local environments with go 1.18.

**Comment by joelanford** [comment]
@AlmogBaku, I just released [go-apidiff v0.4.0](https://github.com/joelanford/go-apidiff/releases/tag/v0.4.0). Hopefully this solves the issue!

**Comment by camilamacedo86** [comment]
go forward @mjlshen . thx
