### ISSUE TITLE
Distinct between Plugins and Bundle Plugins

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes-sigs/kubebuilder#2630]
### What do you want to happen?

Following up on today's meeting-

Currently, we have two terms that are very confusing:
* "Plugins" - a (decoupled) component that is used to scaffold language code (such as Kustomize YAMLs, Go code, Java code, etc.)
* "Bundle Plugins" - a composition of a few plugins. The bundles allow a friendly user interface for end-users around common use cases, I.E: "go bundle" combines Kustomize+go/v3

Following up on the call, we should separate these two terms into Plugins and Bundles and reflect the documentation/code accordingly.

### Extra Labels

/kind documentation, /kind cleanup

**Comment by camilamacedo86** [comment]
I would like to do some clarifications which I think I could not do properly in the meeting. 

In Kubebuilder we have a design which allows us to extend and reuse it as Lib. 
We call plugins a unit which is responsible to address a need and perform scaffolds. (i.e we can have a plugin to allow us to provide helpers for the project, to allow us to do different scaffolds following other partners such as we have the declarative one and etc) 

PS.: For further information, please check the plugins docs: https://book.kubebuilder.io/plugins/plugins.html as its design docs. 

Bundles are the mechanism that allows us to create a plugin by composition. It is part of the Kubebuilder API and only matters for kubebuilder maintainers or for those who are looking to extend Kubebuilder and use it as a lib.
See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/bundle.go

Because of this, I do not agree with the definition added to its description. 

> "Bundle Plugins" - a composition of a few plugins. The bundles allow a friendly user interface for end-users around common use cases, I.E: "go bundle" combines Kustomize+go/v3

**It is not correct. The bundle is only a mechanism/api to build plugins**

Any plugin available can be provided and used by users or extended by any project that consumes Kubebuilder as a lib. 


For this specific case, still not clear what are the proposed changes. Would you like to change the dos or the api names?  So, as I said in the meeting if you check any documentation in the project that you think has a hall for improvements please feel free to push a pull request so that we can properly understand and check what are the suggestions proposed and begin a discussion from there. WDYT?

c/c @rashmigottipati @ryanbrainard @jmrodri @varshaprasad96

**Comment by camilamacedo86** [comment]
Hi @AlmogBaku, 

Could you please clarify what should be done here or let us know if the above explanation sorted out your concerns and we can close this one?

**Comment by AlmogBaku** [comment]
I disagree. The fact that we have written in the API or the documentation doesn't mean we can't change it.


Although technically-wise plugins can be built of a bundle of plugins, this is very confusing from **a product** point of view.

My suggestion is to rename the bundle plugins concept to be just "plugins".
The fact that bundles are implemented *behind the scenes* as a plugin, doesn't contradict it.

**Comment by camilamacedo86** [comment]
@AlmogBaku, 

Seems that we have a misunderstanding here.
The plugin is the concept
BundlePlugin is an API that allows us to create a plugin via composition. 

So, could you please clarify what exactly should change?
Do you want to change a doc? Do you want to change the API?
It is still not clear to me what is the suggestion here. WDYT about you push a pull request with what do you want to change? it might help us understand your thoughts and suggestions.

**Comment by AlmogBaku** [comment]
Sorry, I meant:
>My suggestion is to rename the bundle plugins concept to be just *"bundles"*.

**Comment by camilamacedo86** [comment]
HI @AlmogBaku, 

> My suggestion is to rename the bundle plugins concept to be just "bundles".
 
Where the change should be made? 
Also, see that only "bundles" does not specify bundles of `what`
The SDK (consumer of KB) has "OLM Operator Bundles" which are used to integrate the projects with OLM.

**Comment by AlmogBaku** [comment]
I suggest changing the names only in the docs and comments. The problem is mostly when communicating, it's not a techy issue.

**Comment by camilamacedo86** [comment]
It was discussed in the KB meeting today and we agree to try to improve the [doc][https://github.com/kubernetes-sigs/kubebuilder/blob/6a2384761944cf5e096df0255e213c8bec111aaf/docs/book/src/plugins/creating-plugins.md#L15] to bring a better clarification.
