### ISSUE TITLE
go/v3: Ability to specify custom path

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes-sigs/kubebuilder#2633]
### What do you want to happen?

It could be very helpful if we could specify the path the generate scaffolded files instead of the default `./api` path. This is especially required since the `PROJECT` file support specifying such a thing.

**Comment by AlmogBaku** [comment]
related to #1149

**Comment by camilamacedo86** [comment]
As described in https://github.com/kubernetes-sigs/kubebuilder/issues/2634#issuecomment-1109708790 it seems a duplication of https://github.com/kubernetes-sigs/kubebuilder/issues/932.

However, if you would like to propose a solution for the available plugins working with custom paths then we will need here a design doc for that because it is complex enough and needs to be fully discussed. Also, it would be a duplication of https://github.com/kubernetes-sigs/kubebuilder/issues/1149 since any proposed solution here would need to be generic enough.

**Comment by camilamacedo86** [comment]
Hi @AlmogBaku,

I hope that you do not mind. I am closing this one in favor of https://github.com/kubernetes-sigs/kubebuilder/issues/932. ( it is duplicated )

The above task is created to allow us to provide a feature where would be possible customize the path of what is scaffolded by default.

Also, please feel free to push a PR with a Proposal solution doc to address this requirement.
