### ISSUE TITLE
Upgrade the cert manager template to generate certificate/issuer with the new cert-manager api version `apiVersion: cert-manager.io/v1`

### ISSUE THREAD

**Issue by mzaghab** [kubernetes-sigs/kubebuilder#2705]
### What do you want to happen?

Upgrade the cert manager template to generate certificate/issuer with the new cert-manager api version `apiVersion: cert-manager.io/v1` as the one used actually is deprecated and will be removed sooner
need to upgrade the documentation reference to set the good version of cert-manager as a pre-requisite
https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v2/scaffolds/internal/templates/config/certmanager/certificate.go#L43

### Extra Labels

/kind deprecation

**Comment by camilamacedo86** [comment]
Hi @mzaghab, 

The code shared by you (https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v2/scaffolds/internal/templates/config/certmanager/certificate.go#L43) is deprecated, See: https://github.com/kubernetes-sigs/kubebuilder/pull/2734

Since `28 Apr 2021` kubebuilder scaffold by default https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/certmanager/certificate.go#L49.

If you built your project with an old Kubebuilder version I'd like to recommend migrating your project to the latest one, For more info check the Migration Guide.
