### ISSUE TITLE
openAPIV3Schema generated by controller-gen for map doesn't have allows: true in additionalProperties

### ISSUE THREAD

**Issue by yongxiu** [kubernetes-sigs/kubebuilder#2892]
### What broke? What's expected?

In https://github.com/kubernetes/kubernetes/issues/104137#issuecomment-1215575261, I just learnt that if you want to allow arbitrary key in maps, you need to specify allows: true in additionalProperties for a map.

However for a normal map, controller-gen will not add this `allows: true` in the additionalProperties, causing adding key and value failed the schema validation

### Reproducing this issue

kuebuilder example:
```
// +kubebuilder:validation:Optional
Labels map[string]string `json:"labels,omitempty"`
```

Generated CRD's openAPIV3Schema
```
labels:
   additionalProperties:
       type: string
```

When validating this openAPIV3Schema against a normal yaml:
```
labels:
    "key1": "value1"
```

It will give errors
```
* [].spec.labels: Invalid value: "key1": spec.labels.key1 in body is a forbidden property
```

### KubeBuilder (CLI) Version

v1.23.5

**Comment by camilamacedo86** [comment]
HI @yongxiu,

Could you please open a PR in the controller-tools project https://github.com/kubernetes-sigs/controller-tools? 
Also, feel free to contribute there with the fix. Therefore, when it is fixed in a future release we will be able to get this in the Kubebuilder. 

I am closing this one since it needs to be addressed in the controller-gen.
Thank you for your understanding..
