### ISSUE TITLE
panic when `go.kubebuilder.io/v3` and `go.kubebuilder.io/v4-alpha` specified in `layout`: flag `make` redefined

### ISSUE THREAD

**Issue by pmalek** [kubernetes-sigs/kubebuilder#2899]
### What broke? What's expected?

When running `kubebuilder` in directory that has both `go.kubebuilder.io/v3` and `go.kubebuilder.io/v4-alpha` specified in `layout` section on `PROJECT` file, `kubebuilder` crashes.

```
panic: api flag redefined: make

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0x140001f6b00, 0x140000b0f00)
        /go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x548
github.com/spf13/pflag.(*FlagSet).VarPF(0x14000712a58?, {0x102dfba10, 0x140000a0a29}, {0x1029ed34a, 0x4}, {0x0, 0x0}, {0x102a5f57c, 0x33})
        /go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x140
github.com/spf13/pflag.(*FlagSet).BoolVarP(0x140001f6b00?, 0x102a0489a?, {0x1029ed34a?, 0x1029b2728?}, {0x0?, 0x1029b2714?}, 0xa0?, {0x102a5f57c?, 0x14000712a01?})
        /go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:55 +0x4c
github.com/spf13/pflag.(*FlagSet).BoolVar(...)
        /go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:50
sigs.k8s.io/kubebuilder/v3/pkg/plugins/golang/v3.(*createAPISubcommand).BindFlags(0x140000a09f8, 0x140001f6b00)
        /workspace/pkg/plugins/golang/v3/api.go:97 +0x5c
sigs.k8s.io/kubebuilder/v3/pkg/cli.initializationHooks(0x140000b9400, {0x140000b0820, 0x4, 0x2?}, {{0x102a051a0?, 0x1029e87d8?}})
        /workspace/pkg/cli/cmd_helpers.go:169 +0x1d4
sigs.k8s.io/kubebuilder/v3/pkg/cli.(*CLI).applySubcommandHooks(0x14000712e78, 0x140000b9400, {0x140000b0820, 0x4, 0x4}, {0x102a2c142, 0x14}, 0x0)
        /workspace/pkg/cli/cmd_helpers.go:120 +0xe4
sigs.k8s.io/kubebuilder/v3/pkg/cli.CLI.newCreateAPICmd({{0x102a051a0, 0xb}, {0x140000b6000, 0xc3}, {0x102a62d4f, 0x37}, 0x14000595110, 0x14000595140, {0x3, 0x0}, ...})
        /workspace/pkg/cli/api.go:64 +0x18c
sigs.k8s.io/kubebuilder/v3/pkg/cli.(*CLI).addSubcommands(0x140000a07e0)
        /workspace/pkg/cli/cli.go:411 +0x1dc
sigs.k8s.io/kubebuilder/v3/pkg/cli.(*CLI).buildCmd(0x140000a07e0)
        /workspace/pkg/cli/cli.go:175 +0x17c
sigs.k8s.io/kubebuilder/v3/pkg/cli.New({0x14000713a08?, 0x0?, 0x1400055ce00?})
        /workspace/pkg/cli/cli.go:100 +0x38
main.main()
        /workspace/cmd/main.go:61 +0x7e8
```

### Reproducing this issue

1. Create a `PROJECT` file with the following 2 layouts specified:

    ```yaml
    - go.kubebuilder.io/v3
    - go.kubebuilder.io/v4-alpha
    ```

1. Run `kubebuilder` in directory containing that `PROJECT` file

### KubeBuilder (CLI) Version

3.6.0

### PROJECT version

3

### Plugin versions

```yaml
- go.kubebuilder.io/v3
- go.kubebuilder.io/v4-alpha
```
```


### Other versions

_No response_

### Extra Labels

_No response_

**Comment by camilamacedo86** [comment]
Hi @pmalek, 

Thank you for the contact. The PROJECT file defines the config of the project and is scaffolded by the tool. Users should use go/v3 ( default scaffold ) OR go/v4-alpha to init a project, not both. In this way, the steps described are not expected.

So, why are you doing these steps?  Could you please let us know so we can help you out?

**Comment by pmalek** [comment]
Hi @camilamacedo86 👋 

That's what I thought but at the same time: why shouldn't the user get a nice error message explaining this situation, hm?

**Comment by camilamacedo86** [comment]
Hi @pmalek, 

It is not expected that users change the PROJECT file. I do not think that you are able to do that using the tool only. Are you able to scaffold the project "kubebuilder init" and then run again `kubebuilder init --plugins=go/v4-alpha`? If so, I think we could try to introduce some validation in the CLI to avoid this scenario. 

However, it would be really hard to validate and provide a message for any possible not recommended or not expected action that someone can do in what is scaffolded by default.

If you see that is something that we should/could do please feel free to push a PR with this contribution. Anyway, regards this issue I think we could verify that is not actually a bug and we could close this one. WDYT?

**Comment by pmalek** [comment]
I see your point. When I run the init and then try to run it again on already initialized project I'm getting

```
Error: failed to initialize project: already initialized
```

which would align with what you're saying that it's only possible if `PROJECT` is manipulated by hand.

Nevertheless, a nice error message stating that what the user is trying to do is not allowed would be nice. Well definitely better than `panic`.

I'll probably not find the time to go through the code base and contribute a patch for this but you might leave this open (if you deem it appropriate) so that others can do so if they please.

**Comment by camilamacedo86** [comment]
Hi @pmalek 

> Nevertheless, a nice error message stating that what the user is trying to do is not allowed would be nice. Well definitely better than panic.

As described above it seems a scenario that technically is hard/impossible to cover. And also, that should not really occur at the first place. See the error: 

`panic: api flag redefined: make`

You put 2 plugins ( that has the same goal and would not make sense be executed together manually in the PROJECT file) then, the CLI runs the first plugin and when will run the second plugin see that flag make is already defined. This error came from the golang/cobra pkg because is collision.

I do not see technically how to sort out this scenario or improve the msg.
- Users should not change the PROJECT file unless they are looking to do an workarround for example.
- By using the tool and the plugins the error would not occur. 

On top of that, I'd like to share that the issue https://github.com/kubernetes-sigs/kubebuilder/issues/2786 covers what technically is achivable in this scenario. 

In this way, I hope that you do not mind but I think we need to close this one with: cannot technically be fixed/improved but what is possible get done is covered in the issue https://github.com/kubernetes-sigs/kubebuilder/issues/2786.

However, feel free to check out the code and propose a solution if you see anyone that could fit pushing a new PR against the repo.

Thank you for your attention and compression.
