### ISSUE TITLE
`mdbook serve` failed when missing controller-gen

### ISSUE THREAD

**Issue by Kavinjsir** [kubernetes-sigs/kubebuilder#2955]
### What broke? What's expected?

Missing `controller-gen` in go path would lead to `mdbook serve` failure when building the book locally:
```shell
❯ mdbook serve
2022-09-20 16:45:30 [WARN] (mdbook::book): The output.html.google-analytics field has been deprecated; it will be removed in a future release.
Consider placing the appropriate site tag code into the theme/head.hbs file instead.
The tracking code may be found in the Google Analytics Admin page.

2022-09-20 16:45:30 [INFO] (mdbook::book): Book building has started
+ ../../bin/literate-go supports html
+ ../../bin/literate-go
+ ../../bin/marker-docs supports html
+ ../../bin/marker-docs
2022/09/20 16:45:31 unable to fetch marker docs: exec: "controller-gen": executable file not found in $PATH
2022-09-20 16:45:31 [ERROR] (mdbook::utils): Error: The "markerdocs" preprocessor exited unsuccessfully with exit status: 1 status
```

Not sure why we need `controller-gen` for building docs.
And to resolved the error, I have to ensure that `controller-gen` is installed, such as:
```shell
go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
```

### Reproducing this issue

1. Remove the `controller-gen` if installed:
```shell
❯ l /Users/jintony/go/bin/controller-gen
.rwxr-xr-x 33M jintony  8 Sep 00:27 /Users/jintony/go/bin/controller-gen

❯ rm /Users/jintony/go/bin/controller-gen
```

2. Follow the steps to [run book locally](https://github.com/kubernetes-sigs/kubebuilder/blob/v3.7.0/docs/README.md#running-mdbook):
```shell
❯ cd docs/book/

❯ mdbook serve
```

3. See error logs similar as:
```shell
2022/09/20 16:51:20 unable to fetch marker docs: exec: "controller-gen": executable file not found in $PATH
2022-09-20 16:51:20 [ERROR] (mdbook::utils): Error: The "markerdocs" preprocessor exited unsuccessfully with exit status: 1 status
```

### KubeBuilder (CLI) Version

❯ kubebuilder version Version: main.version{KubeBuilderVersion:"v3.7.0", KubernetesVendor:"unknown", GitCommit:"3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286", BuildDate:"2022-09-20T20:55:27Z", GoOs:"darwin", GoArch:"amd64"}

### Other versions

Go version:
```shell
❯ go version
go version go1.19.1 darwin/amd64
```

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @Kavinjsir, 

We use the controller-gen bin to generate the markers doc, see:
**Code implementation** 

[- https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/utils/markerdocs/main.go#L112-L122
- ](https://github.com/kubernetes-sigs/kubebuilder/blob/3d06aa368761d39bf4dc0fc9dd30b8e02e0d9590/docs/book/utils/markerdocs/main.go#L112-L122)

https://github.com/kubernetes-sigs/kubebuilder/blob/3d06aa368761d39bf4dc0fc9dd30b8e02e0d9590/docs/book/utils/markerdocs/main.go#L227-L235

Therefore, to sort it out we could only doc that and clarifies here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/README.md that the controller-gen used by must be in the GOPATH.

I am labelling this one as triage accepted since does not seems required to discuss this one in the meeting. Would you like to do this one?

**Comment by Kavinjsir** [comment]
Yeah, sounds good!
/assign
