### ISSUE TITLE
Generate apis types from existed crd definition yaml

### ISSUE THREAD

**Issue by ArenaSu** [kubernetes-sigs/kubebuilder#3082]
### What do you want to happen?

How to generate apis types from existed crd definition yaml ? For example i have a crd definition yaml, and i want to generate golang apis types, is there a way to do it ?

The Scenario is below:
My project (generated by kubebuilder) import openfunction v0.7.0 which import keda(github.com/kedacore/keda/v2) v2.4.0 .Meanwhile my project import another inner project which import keda(github.com/kedacore/keda/v2) v2.8.1. Then it conflicts and error occurred when exec go mod tidy. I want to generate keda v2.4.0 api types from v2.4.0 crds and generate keda v2.8.1 api types from v2.8.1 crds. Then move the api types to different directories and import them inner.

And i know kubernetes-client Java have a action named "CRD Java Model Generate", it can generate apis types from crd definition yaml.

**Comment by camilamacedo86** [comment]
Hi @ArenaSu, 

It should be possible. Mainly with the tool, you will need to call create API and generate only the controller. However, we need to do some manual changes, for now, See that we have an open issue to better address that: https://github.com/kubernetes-sigs/kubebuilder/issues/1999

You can also check that we have an old doc: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/using_an_external_type.md  (we need to update it and add it to the docs/website and help would be great as well.)

Also, as guidance would recommend you check that the API is added to the cluster in the main.go, see: https://developers.redhat.com/blog/2020/02/04/how-to-use-third-party-apis-in-operator-sdk-projects

Therefore, would be great to do (ihmo):

**Create a doc in the reference (https://book.kubebuilder.io/reference/reference.html) such as Working with external/third-party apis**

- Add on this section: the recommendations to check out if the API is applied in the main.go and how to add the schema:  https://developers.redhat.com/blog/2020/02/04/how-to-use-third-party-apis-in-operator-sdk-projects
- Add the info from the old doc https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/using_an_external_type.md (updated)
- Ensure that we doc all steps to do it with the current scaffold and create a note pointing out the open issue https://github.com/kubernetes-sigs/kubebuilder/issues/1999 

**Also, help to address the issue https://github.com/kubernetes-sigs/kubebuilder/issues/1999 is welcome**

Would you like to contribute with?

**Comment by varshaprasad96** [comment]
Adding few pointers here, in case it helps: 
Just to understand right, the scenario looks like this: 
- Module A imports something@v2.4.0 
- Module B imports something@v2.8.0
- You require both Module A and Module B in your project.
Doing so, `go mod tidy` errors, since I assume both are incompatible and breaking. This seems to be a Golang issue.

This dependency cycle in a project is highly not suggested since go cannot differentiate between the two. In order to use 2 versions of the same package in a project, you would have to use 2 different `major` versions, (ie) you can have `something/pkg` and `something/v2/pkg`. More details on the same are also [here](https://github.com/golang/go/issues/31578). The other fragile workaround (I would not suggest this) is to fork both the versions locally, and use [replace](https://go.dev/doc/modules/managing-dependencies#tmp_11) directives in `go.mod`.

Meanwhile, coming to the best practices in Kubernetes world - it would helpful to understand your use case. Having multiple GVKs in a same project can definitely be possible, though only one version is eventually stored in etcd server on cluster. In your case, if `v2.8.1` and `v2.4.0` are incompatible, this means both of them belong to different versions of custom resources (say CR/v1 or maybe CR/v2). This indirectly means that though you may need to generate `_types` individually for both, they in turn can be translated to have different major versions. Unfortunately, here we have a thin line of conversion between semantic and alphanumeric versioning which needs to be sorted out based on the use case and nature of APIs.

**Comment by camilamacedo86** [comment]
Oh thank you @varshaprasad96,
No I got that I misunderstood the question.

@ArenaSu maybe nit trying to create controllers for Kinds that are created by other projects.
actually is looking to import the definitions from another project and then re-created the Kind/Api.  

I'd suggest you do not do that. And instead to do the steps described on my previous comment: https://github.com/kubernetes-sigs/kubebuilder/issues/3082#issuecomment-1318435800

**Comment by ArenaSu** [comment]
> Adding few pointers here, in case it helps: Just to understand right, the scenario looks like this:
> 
> * Module A imports something@v2.4.0
> * Module B imports something@v2.8.0
> * You require both Module A and Module B in your project.
>   Doing so, `go mod tidy` errors, since I assume both are incompatible and breaking. This seems to be a Golang issue.
> 
> This dependency cycle in a project is highly not suggested since go cannot differentiate between the two. In order to use 2 versions of the same package in a project, you would have to use 2 different `major` versions, (ie) you can have `something/pkg` and `something/v2/pkg`. More details on the same are also [here](https://github.com/golang/go/issues/31578). The other fragile workaround (I would not suggest this) is to fork both the versions locally, and use [replace](https://go.dev/doc/modules/managing-dependencies#tmp_11) directives in `go.mod`.
> 
> Meanwhile, coming to the best practices in Kubernetes world - it would be helpful to understand your use case. Having multiple GVKs in a same project can definitely be possible, though only one version is eventually stored in etcd server on cluster. In your case, if `v2.8.1` and `v2.4.0` are incompatible (I assume), which means both of them belong to different versions of custom resources (say CR/v1 or maybe CR/v2). This indirectly also means that though you may need to generate `_types` individually for both, they in turn can be translated to have different major versions. Unfortunately, here we have a thin line of conversion between semantic and alphanumeric versioning which needs to be sorted out based on the use case and nature of APIs.

The Scenario is below:

1. k8s cluster A installed keda@v2.4.0
2. k8s cluster B installed keda@v2.8.1
3. two apps (crd controller and apiserver) outside of the two clusters need to create and get two version keda crd resources

It's a very common scenario i think.

**Comment by everettraven** [comment]
@ArenaSu since you are using CRDs from a Go package that already exists with type definitions. While you may not be able to import both `v2.4.0` and `v2.8.1`, you can create you own type definitions by copying their implementation and then renaming them as you see fit for use in your project. Personally I think this would be easier than trying to find a tool to do that from a CRD YAML file (which I am not aware of one that exists for Go). 

I am still curious if there is a better way to handle a scenario like this rather than having to re-implement the type definitions. I would assume that there aren't incompatible changes between the CRDs since they are both the same major version, but there may be new fields added to them from `v2.4.0` --> `v2.8.1` (This is also assuming they are versioning their CRDs in this way. You would likely need to verify that there are no incompatible API changes). 

If your operator can already tell which cluster requires which version of the CRD to use you could have certain logic to populate the fields that only exist in the corresponding version of the CRD. This way you would only need to import and use the definitions from keda `v2.8.1` and use as is for cluster B but when you need to do something on cluster A you only use the fields that exist in a keda `v2.4.0` CRD (you may end up having to use an `unstructured.Unstructured` object to represent creation of a `v2.4.0` CR but I'm not entirely sure here).

**Comment by ArenaSu** [comment]
@everettraven @camilamacedo86 I get it, thanks a lot. I do use runtime.RawExtension and unstructured.Unstructured to make multi-version crds compatible and handle them for different clusters respectively over not only keda but also many other crds. And i will copy multi-version crd definition code to my project to solve the problem. Um it's a "strenuous" work.

**Comment by ArenaSu** [comment]
@everettraven @camilamacedo86 Hi, i am trying to develop a tool to generate api types code from CRD yaml.But i have no experience before.And i am reading the controller-tools source code to find the way how to create a standard generator. I would be very grateful if you give me some ideas or suggestions to generate code from apiextensions CustomResourceDefinition as you are experts in this area. Maybe some useful libs or the specialized way to do it?

**Comment by varshaprasad96** [comment]
@ArenaSu I've had the experience of developing custom generators using controller-tool as a library and hence got the urge to answer the question on that :) So adding some inputs here, in case it helps!

Note:
If you're looking to parse yaml and generate an api type, I doubt controller-tools is the right tool. I'm still going to go ahead and explain the utilities of controller-tools in case you are looking to decode the library and would like to use any helpers for your use case.

The major utilities which c-t provides us with is the ability to define markers in the format we want, parse them with any custom logic and scaffold out relevant bits of code (the output maybe a yaml, a go file or anything).

Step 1:
Declaring markers and parsing them:
- The first step is to declare the format of markers and create a "definition" out of them. The commonly used helper for this is `marker.MakeDefinition` (https://pkg.go.dev/sigs.k8s.io/controller-tools/pkg/markers#MakeDefinition).
- Markers can be defined to be on a type, on a package or on a field. (like kubebuilder object/validation/webhook markers). These can be specified through `Describes<*>` field which is added when you define a marker (https://pkg.go.dev/sigs.k8s.io/controller-tools/pkg/markers#DescribesPackage)
- The marker format can accept arguments. The fields can be defined as a struct and passed on to the definition, similar to https://pkg.go.dev/sigs.k8s.io/controller-tools/pkg/crd/markers#PrintColumn.
An example of this is here: https://pkg.go.dev/sigs.k8s.io/controller-tools/pkg/crd/markers#CRDMarkers.

Step 2:
Parse the marker:
This is done using gengo for which we have wrappers in controller-tools. An example for the same is here: https://pkg.go.dev/sigs.k8s.io/controller-tools/pkg/crd#Generator.Generate. We have several helpers around the parsing logic: https://pkg.go.dev/sigs.k8s.io/controller-tools/pkg/markers#MarkerValues.Get

Step 3:
Generate output:
The output can be of any form. An example of writing yaml is here: https://pkg.go.dev/sigs.k8s.io/controller-tools/pkg/genall#GenerationContext.WriteYAML, and one for writing go files is: https://github.com/kubernetes-sigs/controller-tools/blob/v0.11.1/pkg/deepcopy/gen.go#L290. The `GenerationContext` wraps around all these functionalities. It just boils down to having bytes of data and utilizing other  go tool to write the output in the format we want.

**Comment by ArenaSu** [comment]
> @ArenaSu I've had the experience of developing custom generators using controller-tool as a library and hence got the urge to answer the question on that :) So adding some inputs here, in case it helps!
> ...

Thank you very much.It do help a lot.I will dig into the method what you list and try to develop the tool.
