### ISSUE TITLE
deploy operator as a distributed system

### ISSUE THREAD

**Issue by a85302543** [kubernetes-sigs/kubebuilder#3189]
### What do you want to happen?

noticed that the operator itself is deployed as a standalone service，which means that maybe it will slow down or even crash when under pressure？
is that possible to deploy the operator as a distributed system（like multiple pod to provide service at the same time ） ? or is that any other operator system maybe supported before? 
Looking forward to reply ：）

**Comment by camilamacedo86** [comment]
Hi @a85302543,

Sorry for the delay. Following the answers of your questions:

> noticed that the operator itself is deployed as a standalone service，which means that maybe it will slow down or even crash when under pressure？

The [manager](https://github.com/kubernetes-sigs/kubebuilder/blob/7aa151a9ed9200a2c73e279506474f56d10e2135/testdata/project-v4/cmd/main.go#L68-L85) is scaffolded within leader election. Therefore, another instance will be elected if the manager pod goes downs.

> is that possible to deploy the operator as a distributed system（like multiple pod to provide service at the same time ） ? or is that any other operator system maybe supported before?

You can deploy the Operator in a distributed system. However, you can have only one manager (pod) managing the same controllers otherwise you would have concurrency issues and the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) is not designed to work within. 

I am closing this one as answered but feel free to raise new issues if you need.
