### ISSUE TITLE
Reconcile function will be called concurrent?

### ISSUE THREAD

**Issue by lysShub** [kubernetes-sigs/kubebuilder#3196]
### What broke? What's expected?

Reconcile function will be call concurrent?

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.9.0", KubernetesVendor:"1.26.0", GitCommit:"26f605e889b2215120f73ea42b081efac99f5162", BuildDate:"2023-01-16T17:21:30Z", GoOs:"linux", GoArch:"amd64"}

**Comment by camilamacedo86** [comment]
Hi [lysShub](https://github.com/lysShub),

The reconcile is like a loop that will run until perform all operations required to ensure a desired state. I would like to suggest you check the blog https://dev4devs.com/2020/08/16/how-to-getting-started-develop-go-operators-from-scratch-with-sdk-1-0/ since it has a small overview over how the things work and explain the reconciliation.

Because this are common questions I think would be great if we could copy and updated this content, tweeking a little for our documentation. We could add a new section under the QuickStart https://book.kubebuilder.io/quick-start.html such as Overview to add this code.    

We could also recommend check the documentation over how to [develop Operator pattern solutions](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) from Kubernetes to better understand the purpose of the common solutions that are built with KubeBuilder.  

We could also create an another documentation under the references to clarifies the "Common Suggestions", "Best Practices" or provide the following content in this overview: 

------

## Develop idempotent reconciliation solutions

When developing operators, it is essential for the controller’s reconciliation loop to be idempotent. By following the [Operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) you will create [Controllers](https://kubernetes.io/docs/concepts/architecture/controller/) which provide a reconcile function responsible for synchronizing resources until the desired state is reached on the cluster. Breaking this recommendation goes against the design principles of [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) and may lead to unforeseen consequences such as resources becoming stuck and requiring manual intervention.

## Understanding Kubernetes APIs
Building your own operator commonly involves extending the Kubernetes API itself. It is helpful to understand exactly how [Custom Resource Definitions interact with the Kubernetes API](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/). Also, the Kubebuilder documentation on [Groups and Versions and Kinds](https://book.kubebuilder.io/cronjob-tutorial/gvks.html) may be helpful to better understand these concepts as they relate to operators.

## Follow Kubernetes API conventions
By [developing Operator pattern solutions](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) you will be extending the Kubernetes api. It is highly recommended you understand how Kubernetes API is design and looking for design solutions which follow up the same standards and conventions. Please, ensure that you its [guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#api-conventions)

## Avoid a design solution where more than one Kind is reconciled by the same controller
Having many Kinds (such as CRDs) which are all managed by the same controller usually goes against the design proposed by [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). Furthermore this might hurt concepts such as encapsulation, the Single Responsibility Principle, and Cohesion. Damaging these concepts may cause unexpected side effects, and increase the difficulty of extending, reusing, or maintaining the operator.

## Use  [Status Conditionals](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties)

Its recommended you manage your solutions using [Status Conditionals](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties). You can check the scaffold provided via the [deploy-image][https://book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html] as example over how can you implement it. 

Your help is more than welcome, if you would like to contribute with the project please push a pull request and feel free to ping me out it for get reviews.

**Comment by lysShub** [comment]
@camilamacedo86 

The operator is work for one Kind; I add Wath Pod event, and find cross

**Comment by Sajiyah-Salat** [comment]
> Because this are common questions, I think it would be great if we have a very similar content, tweaked a little for our documentation. We could add a new section under the QuickStart https://book.kubebuilder.io/quick-start.html, such as Overview, to add this code.

Hey @camilamacedo86 from ``this code`` you are referring to the code block in suggested blog. right? if not please clarify, wdym by this code. Thank you.
