### ISSUE TITLE
instance not found

### ISSUE THREAD

**Issue by abrahamhwj** [kubernetes-sigs/kubebuilder#3205]
### What broke? What's expected?

I just newer to learn this, I hop get some help, 3ks
when I run my controller, the log show this:

```
1.67401026673349e+09 INFO no xcoreDefinition instance found. {"controller": "xcoredefinition", "controllerGroup": "xcore.xg.com", "controllerKind": "XcoreDefinition", "xcoreDefinition": {"name":"xcoredefinition-sample"}, "namespace": "
", "name": "xcoredefinition-sample", "reconcileID": "8583b4b5-7883-4da7-b446-78d7e9eed081"}
1.6740102667348359e+09 INFO no xcoreDefinition instance found. {"controller": "xcoredefinition", "controllerGroup": "xcore.xg.com", "controllerKind": "XcoreDefinition", "xcoreDefinition": {"name":"xcore-sample"}, "namespace": "", "name":
"xcore-sample", "reconcileID": "d2945031-f38f-4f4d-a407-646cddd4f0f9"}
1.6740102667359676e+09 INFO no xcoreDefinition instance found. {"controller": "xcoredefinition", "controllerGroup": "xcore.xg.com", "controllerKind": "XcoreDefinition", "xcoreDefinition": {"name":"sample"}, "namespace": "", "name": "samp
le", "reconcileID": "a52060e5-51c1-4c3c-bbac-c9076f7cc2e0"}
```

my question:
1、xcoredefinition-sample\xcore-sample, these 2 instances already deleted before controller run, where these info from?
2、"sample" instance in namespace "xg"，already created before controller run，but as you can see, the log noti "not found"; I need apply this instance again after controller runing, then the controller can find it, it is normal? or I miss something?

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.5.0", KubernetesVendor:"1.24.1", GitCommit:"26d12ab1134964dbbc3f68877ebe9cf6314e926a", BuildDate:"2022-06-24T12:17:52Z", GoOs:"linux", GoArch:"amd64"}

### Other versions

go version 1.18

**Comment by camilamacedo86** [comment]
The logs are from a controller trying to check if it has resources available to be reconciled.

I would recommend you:
- a) Read the content: https://github.com/kubernetes-sigs/kubebuilder/issues/3196#issuecomment-1415494809
- b) Check the plugin: https://book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html; use it to create a sample project and check out how you can implement the solution, etc. Look on this code source. 

I am closing this one since the logs are from specific solutions, and this question is unrelated to Kubebuilder. 
Also, above, you will find all information to get started and skill up to better understanding.

Please, feel free to raise new issues if you have further questions and/or if you face problems.
