### ISSUE TITLE
Add k8sClient.Update example in cronjob_controller_test.go

### ISSUE THREAD

**Issue by Yicheng-Lu-llll** [kubernetes-sigs/kubebuilder#3212]
### What do you want to happen?

 [cronjob_controller_test.go](https://github.com/kubernetes-sigs/kubebuilder/blob/60697e4326e3fdb75a5af271ceacba7e61b19bd2/docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go#L109) gives a great example on how to write tests!
However, I notice that current examples only cover` k8sClient.Create`  and` k8sClient.Get`. There are no examples for ` k8sClient.Update`.

As [k8s api-conventions docuemnt](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency) says, if any changes are made by another client between the client's last Get and Update, then k8sClient.Update may fail with code 409( StatusConflict).

I have already seen a couple of solutions and suggestions:
1. client-go already has [a helper function: RetryOnConflict](https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict) and an [example](https://github.com/kubernetes/client-go/blob/master/examples/dynamic-create-update-delete-deployment/main.go#L118-L129). They use the retry strategy.
2. [azure-databricks-operator](https://github.com/Azure/azure-databricks-operator/blob/265a0a8546293a5d52cdb8a98bac507ce0750cae/controllers/dbfsblock_controller_test.go#L106)(also [link](https://github.com/Azure/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/secretscope_controller_test.go#L216)) does in a normal way(no retry just call update and see if success).

I wonder how kubebuilder will deal with the k8sClient.Update in controller test. It would be really helpful if k8sClient.Update example is added to [cronjob_controller_test.go](https://github.com/kubernetes-sigs/kubebuilder/blob/60697e4326e3fdb75a5af271ceacba7e61b19bd2/docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go#L109).

**Comment by camilamacedo86** [comment]
Hi @Yicheng-Lu-llll,

Did you check the scaffold provided by [deploy-image][https://book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html] as an example of how you can implement it? 

You can check an example of the controller with the implementation: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go

Note that the "problem" you are discussing here is not only about the status. If you get the resource and then when you try to update it ( no matter if it is the status or a spec ) and the specific resource has been changed in the needle of the time in the server, then it will fail, and the reconciliation will start again.

I recommend you get the latest resource versions before setting the values and updating them consistently. On top of that, the solution should be idempotent means that, if an error is faced, that is fine because the reconciliation should be re-started, and the desired stated will be ensured.  Please, check the content of this comment :   https://github.com/kubernetes-sigs/kubebuilder/issues/3196#issuecomment-1415494809

I hope that helps you out and answer your questions
I am closing this one as sorted out but feel free to re-open it if you see that it is required.

**Comment by Yicheng-Lu-llll** [comment]
Hi @camilamacedo86,

Thank you for your reply! The information is helpful. Though I understand that in real operator running time, the desired stated will be finally ensured, I am concerned more about the update operation may cause the test to be flaky. Meaning sometimes it updates successfully but sometimes it will throw 409 errors. 

Based on the [example you provide](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go#L245-L248), I think you will also agree that we can use [RetryOnConflict](https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict)  to make the test less flaky.


please let me know if I am wrong. Thank you in advance.
