### ISSUE TITLE
`make deploy` fails inside cronjob tutorial  

### ISSUE THREAD

**Issue by kallyaleksiev** [kubernetes-sigs/kubebuilder#3249]
### What broke? What's expected?

Currently, inside the code for the cronjob tutorial (in `docs/book/src/cronjob-tutorial/testdata/project`) if you try to deploy it to your cluster using `make deploy` you get an error:

```
lstat kubebuilder/docs/book/src/cronjob-tutorial/testdata/project/config/manager/controller_manager_config.yaml: no such file or directory"

error: no objects passed to apply
make: *** [deploy] Error 1
```

because the file `controller_manager_config.yaml` referenced in the `kustomization.yaml` does not exist there 

this file does not seem to be needed and the entire `configMapGenerator` https://github.com/kubernetes-sigs/kubebuilder/blob/73e25fadb93daa1e240b4dda4df7c9016ef4d3ce/docs/book/src/multiversion-tutorial/testdata/project/config/manager/kustomization.yaml#L7 can be deleted, at which point `make deploy` works

### Reproducing this issue

run `make deploy` inside `docs/book/src/cronjob-tutorial/testdata/project`

### KubeBuilder (CLI) Version

3.9.0

### Extra Labels

/kind documentation

**Comment by xiao-jay** [comment]
i agree @kallyaleksiev,i think should remove the code block below because the code does not seem to be needed and the entire configMapGenerator.I also create a project to test [cronjob tutorial](https://kubebuilder.io/cronjob-tutorial/controller-implementation.html),found not generate `configMapGenerator:`


[kubebuilder/docs/book/src/multiversion-tutorial/testdata/project/config/manager/kustomization.yaml](https://github.com/kubernetes-sigs/kubebuilder/blob/73e25fadb93daa1e240b4dda4df7c9016ef4d3ce/docs/book/src/multiversion-tutorial/testdata/project/config/manager/kustomization.yaml#L7)
```
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml
```


### test cronjob tutorial way
```
kubebuilder init --domain tutorial.kubebuilder.io --repo tutorial.kubebuilder.io/project
kubebuilder create api --group batch --version v1 --kind CronJob 
```

code in kubebuilder-cronjob/config/manager/kustomization.yaml
```
resources:
- manager.yaml
```


```
➜  manager kubebuilder version
Version: main.version{KubeBuilderVersion:"v3.9.0-48-g73e25fad-dirty", KubernetesVendor:"unknown", GitCommit:"73e25fadb93daa1e240b4dda4df7c9016ef4d3ce", BuildDate:"2023-03-04T05:50:09Z", GoOs:"darwin", GoArch:"arm64"}

```

**Comment by xiao-jay** [comment]
May be this issue need to close ?
/assign
