### ISSUE TITLE
kubebuilder 3.9.0 (latest), maybe there is a bug because of the "resources.claims"（k8s 1.25→1.26）

### ISSUE THREAD

**Issue by Qiubabimuniuniu** [kubernetes-sigs/kubebuilder#3250]
### What broke? What's expected?

my env ：kubebuilder 3.9.0 (latest), k8s(1.26.), client-go@0.26.0
Read this picture and maybe you will understand. I'm not sure if it's my version matching problem or if the latest version of kubebuilder doesn't take  "resources.claims" into account
![1d8d2b001877271a1cee55cf040b293](https://user-images.githubusercontent.com/88152426/221364366-1d33893f-da77-4854-a1e7-a3d39ad6d0d9.png)
![1d8d2b001877271a1cee55cf040b293](https://user-images.githubusercontent.com/88152426/221364373-a4b7eefb-6b3a-4827-bfd7-ecae4a3d2902.png)

### KubeBuilder (CLI) Version

3.9.0

**Comment by nagyv** [comment]
The same happens on k8s v1.25 (v1.25.6+k3s1)

I guess the issue might be in the copy&paste following of the tutorial. 

Everything works as expected when running:

```
git clone https://github.com/kubernetes-sigs/kubebuilder.git
cd kubebuilder/docs/book/src/cronjob-tutorial/testdata/project
make
make manifests
make install
```

**Comment by Qiubabimuniuniu** [comment]
> The same happens on k8s v1.25 (v1.25.6+k3s1)
> 
> I guess the issue might be in the copy&paste following of the tutorial.
> 
> Everything works as expected when running:
> 
> ```
> git clone https://github.com/kubernetes-sigs/kubebuilder.git
> cd kubebuilder/docs/book/src/cronjob-tutorial/testdata/project
> make
> make manifests
> make install
> ```

I think maybe because cronjob_types.go's "CronJobSpec struct" in the official project doesn't contain "Template v1.PodTemplateSpec ", it works just as expected. 
1.26 added "claims" property to pod"template.spec.resource" compared to 1.25. Here is my "***Spec Struct" with "v1.PodTemplateSpec“, so mine will break and the official example will work as expected.
![1677509165303](https://user-images.githubusercontent.com/88152426/221595215-82dd13cd-2ccb-46d8-9e55-c02fc35f7362.jpg)

**Comment by andregri** [comment]
Found discussions here:
- https://github.com/kubernetes-sigs/controller-tools/issues/752
- https://github.com/kubernetes-sigs/controller-tools/issues/772

In particular, [this workaround from #772](https://github.com/kubernetes-sigs/controller-tools/issues/772#issuecomment-1416027564) solved the error for me:
> set CONTROLLER_TOOLS_VERSION ?= v0.11.2 in Makefile and k8s.io/api v0.26.1 in go.mod

**Comment by camilamacedo86** [comment]
It seems that this problem occurs because you update the go dependencies incompatible with the controller-runtime version used.  You can fix it by ensuring that your go.mod has the following:

> k8s.io/apimachinery v0.26.1
> k8s.io/client-go v0.26.1
> sigs.k8s.io/controller-runtime v0.14.4

And you are using controller-tools version (v0.11.3) https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/Makefile#L136.

Just to highlight that if users change the go deps manually or the versions used by the artefacts without checking what versions are scaffolded and tested within each Kubebuilder release, then they might end up in scenarios like that where the versions are not compatible, see https://book.kubebuilder.io/quick-start.html#versions-and-supportability

To avoid it, I would recommend checking the samples in the test data directory to know what versions are used for each tagged release and make sure that you upgrade the project with compatible ones. 

In this way, I think we can close this one as sorted out. However, please to re-open if you think that is required.

**Comment by Qiubabimuniuniu** [comment]
thanks! I get it! @camilamacedo86 @andregri
