### ISSUE TITLE
Multi-arch node affinity patch included in auth proxy patch?

### ISSUE THREAD

**Issue by joelanford** [kubernetes-sigs/kubebuilder#3272]
### What broke? What's expected?

Since v3.7.0, it looks like kubebuilder is inserting a multi-arch-related affinity patch into my final kustomize manifests by including it in the auth proxy patch by default here: https://github.com/kubernetes-sigs/kubebuilder/blob/cbccafa75d58bf6ac84c2f5d34ad045980f551be/pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go#L56-L71

However, this same patch is included (but commented out) in the ./co.nfig/manager/manager.yaml file (originating here: https://github.com/kubernetes-sigs/kubebuilder/blob/3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286/pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go#L86-L105)

It seems like the patch was inadvertently added to the auth proxy patch file (it doesn't seem related to the auth proxy at all). I also didn't see any discussion about this in the PR that introduced it (#2906).

Just checking to see if this is a bug or if I'm missing something. Thanks!

### Reproducing this issue

Run any invocation of `kubebuilder init` that uses the kustomize/v1 plugin.

### KubeBuilder (CLI) Version

3.7.0 (or later, it seems)

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4-alpha
```

**Comment by camilamacedo86** [comment]
Hi @joelanford,

I agree it is a bug I think we should let it be commented.

**Comment by camilamacedo86** [comment]
Hi @joelanford,

I believe that the idea of it not be commented on in [manager_auth_proxy_patch.go](https://github.com/kubernetes-sigs/kubebuilder/blob/cbccafa75d58bf6ac84c2f5d34ad045980f551be/pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go#L56-L71)  is because it will apply the config for the image `gcr.io/kubebuilder/kube-rbac-proxy` which would support those platforms. 

However, are you saying that it doesn't seem related to the auth proxy at all? Did you find any issue within? 
Could you please let us know more about it to see if we need to just comment or if would be required to change the scaffold? 

Thank you for your collaboration and to bring it to our attention.

**Comment by joelanford** [comment]
If I understand correctly, the patch is applied at the pod level, not the container level. So it affects both the kube-rbac-proxy container and the manager container.
