### ISSUE TITLE
Cant install CRD

### ISSUE THREAD

**Issue by sadath-12** [kubernetes-sigs/kubebuilder#3305]
### What broke? What's expected?

What i did ?

I was following the cronjob tutorial and reached to page 
https://kubebuilder.io/cronjob-tutorial/running.html
was almost copy pasting code from these repository and got no error in compile time

when went ahead to crd with command make install 

I got the following bug 

```/home/sadath/operators/cron-job/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
test -s /home/sadath/operators/cron-job/bin/kustomize || { curl -Ss "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 3.8.7 /home/sadath/operators/cron-job/bin; }
/home/sadath/operators/cron-job/bin/kustomize build config/crd | kubectl apply -f -
The CustomResourceDefinition "cronjobs.batch.tutorial.kubebuilder.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[ephemeralContainers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[containers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[initContainers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[volumes].items.properties[ephemeral].properties[volumeClaimTemplate].properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* ```

I also made sure my docker and k8s are running

**Comment by xiao-jay** [comment]
#3303  you can look this issue.

**Comment by camilamacedo86** [comment]
This problem occurs because you update the go dependencies, which are incompatible with the controller-runtime version used. 

You can fix it by ensure that your go.mod has:

> k8s.io/apimachinery v0.26.1
> k8s.io/client-go v0.26.1
> sigs.k8s.io/controller-runtime v0.14.4

And you are using controller-tools version (v0.11.3) https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/Makefile#L136.

Just to highlight that if users change the go deps manually or the versions used by the artefacts without checking what versions are scaffolded and tested within each Kubebuilder release, then they might end up in scenarios like that where the versions are not compatible, see https://book.kubebuilder.io/quick-start.html#versions-and-supportability

To avoid it I recommend checking the samples in the test data directory to know what versions are used for each tagged release and ensure that you upgrade the project with compatible ones. 

Closing this one as duplicated https://github.com/kubernetes-sigs/kubebuilder/issues/3303#issuecomment-1475080334 of.
