### ISSUE TITLE
Document how to use pprof which was introduced in controller-runtime v0.15.x

### ISSUE THREAD

**Issue by zqzten** [kubernetes-sigs/kubebuilder#3338]
### What do you want to happen?

As [pprof support been introduced to controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/pull/1943), we can follow up to make it available (and visible) to end users of kubebuilder. This issue tracks the tasks needed TBD, please comment if I miss or get wrong on anything.

- [ ] upgrade controller-runtime to [v0.15.x](https://github.com/kubernetes-sigs/controller-runtime/milestone/12)
- [ ] add a flag to configure the pprof serving address in `main.go` of kubebuilder scaffold
- [ ] address the security issues (possible sensitive information leak) on exposing pprof in comments or the kubebuilder book

For the third task, I'm not sure what best practice we shall provide to end users so this is RFC.

For now, I can think up two possible ways:

* defaulting the pprof bind address to `127.0.0.1:xxxx`
* protect the pprof endpoint by kube-rbac-proxy just like the metrics does (this would require more tasks TBD)

Please comment your preference or other opinions if applicable, thanks!

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @zqzten, 

Thank you for tracking this one and for making this contribution. 
I understand that the Go runtime/pprof and net/http/pprof packages are used for profiling and performance analysis of Go applications. Therefore, it does not seem to be recommended to be applied to solutions in production such as the metrics are. 

However, it seems a very good and nice feature to let others be aware of. What do you think about address this one as a documentation? What about add a new topic in the docs such as `benchmark` and add a guide with example how to use this feature to benchmark the solution and check to analyze the performance?

WDYT? Would that make sense? would you like to push a PR within the doc since you are the featured author?

**Comment by zqzten** [comment]
Hi @camilamacedo86, thanks for the reply.

> Therefore, it is not recommended to be applied to solutions in production such as the metrics are.

This might not be the case I think, since enabling pprof itself would not introduce performance degression to the application (only an explicit profling request would do so). On the contrary, pprof is a must have when we want to inspect performance problems such as memory leak in production, as [alvaroaleman said here](https://github.com/kubernetes-sigs/controller-runtime/pull/1943#issuecomment-1176343059). Also, as an evidence, k8s components such as [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) also enables pprof by default.

So I still think that we'd better enable pprof by default, and the only concern is the security issues mentioned above.

**Comment by zqzten** [comment]
Wow thanks for the detailed explanation! @camilamacedo86 

> Profiling can consume considerable CPU and memory resources, especially when continuously enabled in a production environment.

CPU profiling is not activated at initialization time, it is only activated for a period of time (30 seconds by default) when the `/debug/pprof/profile` http service is called. So enabling pprof server alone should not impact much the performance of the application (except that extra goroutines for the http server are needed).

> However, it is still a potential security risk if an attacker were able to gain access to the master nodes, and I believe that in many environments, system admins will disable that if/when the env is not in a protected or disconnect network (airgap envs).

The pprof endpoint of kube-controller-manager is not only protected by network restrictions, but also protected by mTLS with RBAC (like that in kube-apiserver). So it's rather safe to keep it on by default in production.

For other points, I understand and agree with your opinion, since additional security efforts shall be applied to pprof endpoint, it might not be suitable to make it enabled by default to everyone, especially for those who have no need or knowledge of pprof.

For now, I think a brief doc would be enough to let ppl know this featue and related concerns on this, the plugin way is a little overkill. Glad to work on this :)

**Comment by camilamacedo86** [comment]
Hi @zqzten,

I am so happy that we could convey that doc this one for now seems the best way to move forward. Please, feel free to work in this doc if you wish.

I am adding Help wanted on this one as we. Have its doc would be very helpful for sure.

**Comment by camilamacedo86** [comment]
The comments above were hidden for simplicity. While we've decided to document its usage rather than include it in the default scaffold, you can refer to the hidden comments for more context on this decision. Nevertheless, introducing it as an optional plugin for the scaffold could be a viable alternative. This option would certainly be a beneficial addition.

To address this issue we must:
- Create a doc under the reference to let users know how to use this option
- Optionally we could address it via an Optional Plugin to update the default scaffold within this option. (I would recommend we doc first and then work in the PR with the proposal solution for it as a plugin as follow up)

**Comment by camilamacedo86** [comment]
It is supported since it is a feature in the controller-runtime.
The idea here is just add a doc under references to let people know how to use and when to use as its implications. 
We cannot add it in the default scaffold because it is not recommended for prod envs, see; https://github.com/kubernetes-sigs/kubebuilder/issues/3338#issuecomment-1541908179

**Comment by camilamacedo86** [comment]
It is done now !
Closing it
