### ISSUE TITLE
component-config example type is missing required object meta field

### ISSUE THREAD

**Issue by lefinal** [kubernetes-sigs/kubebuilder#3384]
### What broke? What's expected?

The `ProjectConfig` `struct` in the [example file](docs/book/src/component-config-tutorial/testdata/projectconfig_types.go) (website link: https://book.kubebuilder.io/component-config-tutorial/config-type.html) is missing the embedded `ObjectMeta` from `k8s.io/apimachinery/pkg/apis/meta/v1`. This leads to the type being ignored when scaffolding and no crd being generated.

### Reproducing this issue

Follow the component config example with an already existing project. You can also remove the line from [here](docs/book/src/component-config-tutorial/testdata/project/api/v2/projectconfig_types.go), add some fields and run `make manifests`. You will not see any changes in the crds.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.9.1", KubernetesVendor:"1.26.0", GitCommit:"cbccafa75d58bf6ac84c2f5d34ad045980f551be", BuildDate:"2023-03-08T21:23:07Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

3

### Plugin versions

```yaml
- go.kubebuilder.io/v4
```

### Other versions

`go version go1.20.2 linux/amd64`

from books example [go.mod](docs/book/src/component-config-tutorial/testdata/project/go.mod)
```
go 1.20

require (
	k8s.io/apimachinery v0.26.1
	k8s.io/client-go v0.26.1
	sigs.k8s.io/controller-runtime v0.14.4
)
```

### Extra Labels

/kind documentation

**Comment by yhrn** [comment]
I'm also confused by this - is the CRD really supposed to be generated for this?

If I understand correctly how the whole component config is supposed to work, we shouldn't be installing any CRDs because the config is just wrapped in a `ConfigMap` (in `config/manager/kustomization`) and mounted into the controller pod (via a patch in `config/default/kustomization`).

But if I'm right about that then it needs to be removed from `resources` in `config/crd/kustomization` and the tutorial isn't mentioning that. The tutorial is also not clear about what to do with `ObjectMeta`, the status and whether one should leave the `+kubebuilder:object:root=true` marker on the config type.

**Comment by camilamacedo86** [comment]
Hi @yhrn,
 
The Config only configures the Options values for the manager and not remove the need for CRDs or setup them.
The idea is you be able to have the same project deployed in different envs with different Manager Options config.
The Manager is configured in the cmd/main.go, and it is what will manage ALL controllers. 

https://github.com/kubernetes-sigs/kubebuilder/blob/2a97944a0cb387633953da26dce13a1a6814129e/testdata/project-v4/cmd/main.go#L68-L86

Therefore, I understand this issue concerns is about the samples under the book/docs directory, which are used to create the tutorials AND not the config component/plugin. 

To update the code of the samples is required to change the code implementation under hack/. The samples under the books are built automatically based on the code changes when we run `make generate`. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/hack/docs/internal/generate_component_config.go

**Comment by yhrn** [comment]
@camilamacedo86 I don't understand fully. From [Kubebuilder book](https://book.kubebuilder.io/component-config-tutorial/config-type.html): "...because ProjectConfig **is not intended to be an API extension** and cannot be reconciled." (my highlight).

Also, if you `kustomize build config/default` after following the tutorial your `config/manager/controller_manager_config.yaml` contents do not appear as a standalone object but it's wrapped in a config map. There is never any `ProjectConfig` (or whatever you decide to call your custom config type) deployed to the cluster, so I don't understand what you need the CRD for. I mean you couldn't read the config from disk the way it happens in `main.go` if it was an API object, then it would have to get it from the API server, it can only do that because it's in a `ConfigMap` that gets mounted.

The controller need to add it to the scheme so it understand it internally, but that happens in `main.go` and has nothing to do with the CRDs AFAIK.

**Comment by lefinal** [comment]
I see, seems to be my fault. First month of working with Operators. Thanks for the kind feedback and explanation! Closing this.

**Comment by yhrn** [comment]
@camilamacedo86 ☝️ 

If I'm misunderstanding this, please explain what the CRD is used for.
