### ISSUE TITLE
Update Webhook For Core Types for CR 0.15

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/kubebuilder#3393]
### What broke? What's expected?

It looks to me that [the book docs](https://book.kubebuilder.io/reference/webhook-for-core-types.html) is going to get broken in CR v0.15 series.  I got mine fixed by following [this commit](https://github.com/kubernetes-sigs/controller-runtime/commit/927c09e54313d6476b5780b7f029f381d777c149).

Submitting this issue to track the necessary doc updates.

### KubeBuilder (CLI) Version

N/A

### Other versions

`sigs.k8s.io/controller-runtime v0.15.0-alpha.0`

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @mythi, 

We start to working in a PR to bump the alpha version and address the breaking changes; see: https://github.com/kubernetes-sigs/kubebuilder/pull/3394

Since you could sort it out accordingly, could you give us a hand and help us to fix this doc? 
WDYT? Can you push a PR within the docs fixes against the master so that it would be fixed and updated in the next release?

**Comment by camilamacedo86** [comment]
Done to be shipped with Kubebuilder 3.11
