### ISSUE TITLE
Drop unnecessary steps and better logging when generating docs

### ISSUE THREAD

**Issue by Kavinjsir** [kubernetes-sigs/kubebuilder#3435]
### 1. Unnecessary `docker` commands
Currently executing `make generate-docs` will trigged `docker rmi -f`, which might not be necessary:
<img width="552" alt="Screen Shot 2023-05-29 at 12 03 44 PM" src="https://github.com/kubernetes-sigs/kubebuilder/assets/18136486/087f93a5-883e-4d45-9f43-a9ee5ddc68dd">

### 2. Hard to debugging when error happens during docs generation
Another case is: when error happens during docs generation by `make generate-docs`, it is hard to locate the error position from the display log info:
<img width="898" alt="Screen Shot 2023-05-29 at 12 06 27 PM" src="https://github.com/kubernetes-sigs/kubebuilder/assets/18136486/99ab5bec-ea1e-4d25-b847-9276e73d01d6">

## Suggestion

1. Remove the docker command and other unnecessary steps if possible for `make generate-docs`
2. Display rich log info when generating docs.

### One Approach for suggestion 2
For the UpdateTutorial method, we can change the comment lines to `log.Info`:
<img width="407" alt="Screen Shot 2023-05-29 at 12 09 24 PM" src="https://github.com/kubernetes-sigs/kubebuilder/assets/18136486/0e7efcdb-f69b-4902-a1bd-452810901852">

So that when running `make generate-docs`, it support trace the process:
<img width="804" alt="Screen Shot 2023-05-29 at 12 10 03 PM" src="https://github.com/kubernetes-sigs/kubebuilder/assets/18136486/4eaf9cdf-5635-4189-98b6-4c1089070b70">

### Extra Labels

/kind documentation, /kind cleanup

**Comment by ashutosh887** [comment]
@Kavinjsir 
Should I work on this one?

**Comment by camilamacedo86** [comment]
+1, IMO we need to:

- Improve the logs as suggested
- Ensure that all operations has a log for errors with an unique text so that when it fails we know where and the error itself.

I am adding a good first issue on this one.

**Comment by ashutosh887** [comment]
Sure let me work on this @camilamacedo86 

Thanks

**Comment by camilamacedo86** [comment]
What is required to be done in this task:

## 1) What is the main go of this task:

The main go of this task is ensure that for each operation done in the hack implementation to generate the doc samples we have a check to verify the errors with an information that help us to know what fails so that we can fix it. For example, see:

https://github.com/kubernetes-sigs/kubebuilder/blob/c2fbb3ecfe067605fce0fb274949fa51e5698bbd/hack/docs/internal/cronjob-tutorial/generate_cronjob.go#L469-L475

The both operations has an message `fixing suite_test.go` so that if we see this error we do not know where it fails. 
Therefore, the whole main point is to improve the code implementation to help us debug and troubleshooting when/if required. 

## 2) Second expected improvement 

See the description `docker command and other unnecessary steps`.
It occurs because we are using the same methods used to do the tests and it is required in the e2e tests.
See: https://github.com/kubernetes-sigs/kubebuilder/blob/c2fbb3ecfe067605fce0fb274949fa51e5698bbd/test/e2e/utils/test_context.go#L241-L251

Therefore, in the sample case we call Destroy but we do not need to call `cmd := exec.Command("docker", "rmi", "-f", t.ImageName)` So we can created a new method DestroyTempDir and use it instead or just replace the Destroy usage in the hack docs per the cmd commands and use it directly. 

NOTE: It is recommended to create one PR for each improvement so that it will make easier the review process.

**Comment by Sajiyah-Salat** [comment]
Sure. I will first focus on the first task. 
we will add filename, line, err. 
Do you think we also want to give different message or let the message as it is?

**Comment by Sajiyah-Salat** [comment]
Also can you please let me know how should I check my changes.

**Comment by Sajiyah-Salat** [comment]
I have done some research on my own it looks like withstack function can be used to debug errors more efficiently. i will try if succeded I will try to send the pr.

**Comment by Kavinjsir** [comment]
I think we may also take care about: making sure that the execution of `generate-docs` should use the kubebuilder built from the same source code.

For now, the code for generation assumes the env provides `kubebuilder`, so it does not check if this "kubebuilder" is created from the source code.

I guess this might lead to confusion when we have updates the document to sync with certain plugins updates.
For me, I have to remind myself to run `make install` before `make generate`.

**Comment by Sajiyah-Salat** [comment]
So you mean that we should first update the kubebuilder repository and then generate docs which will be easy for users as they dont need to remember to run make install before make generate. right?

**Comment by varshaprasad96** [comment]
Agree that this is an issue, that we are directly using the `kubebuilder` available in the path, rather than building from the source code. However, we would have look for the approach we are following while generating testdata - if we are running the `make install` command directly, or if we have a helper in place to build the KB binary. 

/assign @Kavinjsir
