### ISSUE TITLE
Documentation request: e2e test with webhook

### ISSUE THREAD

**Issue by vsoch** [kubernetes-sigs/kubebuilder#3454]
Hi Kubebuilder developers! I am looking for an example of an e2e test that also includes adding the webhook. We have some logic that is set in the webhook, and would like it to be there for the e2e test. An example adding to the testEnv might look like this:

https://github.com/kubernetes-sigs/jobset/blob/cfd9d7ce33da7599cdbd2590884481a99403afb8/test/integration/webhook/suite_test.go#L63-L70

And maybe that is close, but I wasn't able to get something similar working in the e2e test (and maybe I just need a subset, or a way to edit the cfg object generated?) It would be great if the docs here could provide an example like this. Thank you!

**Comment by camilamacedo86** [comment]
I think this one is interesting. Thank you for raising it.
It seems that would be very nice add an example in the docs over how to implement e2e test for the webhooks.

That would mean we improve the doc samples used so that we can do it in the tutorial.
- See that the code source used in the docs came from the samples, such as: https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/cronjob-tutorial/testdata
- Also, see that when we run make generate we updated the samples used and we have the code implementation to so under the hack: https://github.com/kubernetes-sigs/kubebuilder/tree/master/hack/docs

**Comment by vsoch** [comment]
@camilamacedo86 I don't think I can help here, but I just wanted to say I think you are a great maintainer! Your responsiveness on GitHub and in the slack (and interaction between the two) deserves a :clap:. Thank you for doing what you do! <3

**Comment by ashutosh887** [comment]
I can work on this @vsoch if @camilamacedo86 agrees 

Thanks
/assign

**Comment by camilamacedo86** [comment]
In this task we need to:
- Check if we can improve the file scaffold for suite_test under api for webhooks
- So, we need to check the options that we use for controllers ( under internal/controllers ) see if has something that we do there that we can either add to the suite test for webhooks.

**Comment by Sajiyah-Salat** [comment]
Hello @ashutosh887 Are you working on this till now? It would be great for me to work on this and solve this issue.

**Comment by ashutosh887** [comment]
Yes I'm on it @Sajiyah-Salat

**Comment by Sajiyah-Salat** [comment]
Great please give me link of the pr or if you haven't started that yet

**Comment by drewwells** [comment]
Any updates on this? Jobset appears to be successfully updated for a number of API changes in webhook and controller manager https://github.com/kubernetes-sigs/jobset/blob/d5dbb51970d57197b493693295ec323b8e9598b9/test/integration/webhook/suite_test.go#L102-L107
