### ISSUE TITLE
RFC: The kube-rbac-proxy is too opinionated to be opt-out.

### ISSUE THREAD

**Issue by hsyed-dojo** [kubernetes-sigs/kubebuilder#3482]
### What do you want to happen?

The kube-rbac-proxy is too opinionated to be an opt-out component. 

Issues:

* This solution doesn’t fit into a generalised strategy of how metrics scraping might be done cluster wide, this tends to be either leaving the endpoint unsecured or relying on a mesh. It will in most cases end up introducing a new scraping strategy. 
* This approach assumes the average user is OK with an additional sidecar and that they wouldn't have other ways of mitigating the risks of leaving this endpoint unsecured. 
* The approach results in an operator install process that is not self-contained and we need to give the prom scraper SA additional privileges. 

I’d like to advocate to make this opt-in and that the additional manifests are only generated if a CI flag is provided during the init.

**Comment by camilamacedo86** [comment]
HI @hsyed-dojo,

That is a very interesting RFE. 

**Regards to make it optional** (opt-in) then, I think we would need to have an plugin such as we have grafana/v1alpha1 and deployImage/v1alpha1 instead of use flags. More info: https://book.kubebuilder.io/plugins/plugins.html

However, note that we have a issue to replace the kube-rbac-proxy see: https://github.com/kubernetes-sigs/kubebuilder/issues/1885. Would the approach described in this issue sorted out your concerns?

**Comment by camilamacedo86** [comment]
Reopen this one since it is something that must be discussed.

**Comment by camilamacedo86** [comment]
### Next Step: Evaluate NetworkPolicy Integration

**Expected Outcome:**

> The outcome of this task is to make an informed decision regarding the adoption of NetworkPolicy in Kubebuilder. By evaluating its pros and cons and conducting testing, we aim to determine whether this change will enhance the project's functionality and align with community preferences.
> 
> Let's work together to evaluate this potential improvement and make an informed choice for the future of Kubebuilder.

**Goals:**

1. Assess using NetworkPolicy instead of rbac-proxy in Kubebuilder.
2. Test NetworkPolicy implementation via a PR with default scaffold changes.
3. Share PR results in Kubebuilder channel for discussion.

**Steps:**
**a) Evaluate Pros and Cons:**

Review comments to capture NetworkPolicy's benefits and drawbacks.
Note that the argument against NetworkPolicy (CNI support) may no longer apply.

b) Create PR with Scaffold Changes:

- Modify default scaffold to use NetworkPolicy.
- Thoroughly test in e2e scenarios.
- Summarize pros and cons in PR comment, linking it in the description. Ideally add a comment here in the issue and link it in the description so that we can easily check the summary with pros vs cons that you find out. 

c) **Community Discussion:**

Share PR results in Kubebuilder channel so that we can collect feedback and insights as decide whether to merge the PR or retain rbac-proxy.

Your help here is very appreciated by the whole community 🥇

**Comment by camilamacedo86** [comment]
## Next Steps:

The progress on this issue appears to be blocked by the discussion at [this GitHub comment](https://github.com/kubernetes-sigs/kubebuilder/issues/1885#issuecomment-1809841870).

Once the assessment mentioned above is completed, we will be in a better position to decide between the following options:

a) **Replacement of kube-rbac-proxy with NetworkPolicy:**
   Depending on the assessment's findings, we may choose to replace kube-rbac-proxy with NetworkPolicy if it aligns with project goals and requirements.

AND/OR

b) **Create a Plugin for Opt-In/Opt-Out Usage of rbac-proxy:**
   Alternatively, we can consider creating a plugin that allows users to opt-in or opt-out of using rbac-proxy. It's worth noting that in the long term, we might decide to donate the plugin to the respective project instead of maintaining it here. This option offers flexibility and user choice.

OR
c) **Keep the kube-rbac-proxy in the default scaffold and also make mandatory the usage of cert-manager by default**

- see that for properly ensure security with the metrics it might be required : https://github.com/kubernetes-sigs/kubebuilder/issues/3657
- also, due the changes and deprecation in the kube-rbac-proxy we might only be able to move forward with if cert-manager is mandatory by default and not only when webhooks are used. For further information, see: https://github.com/kubernetes-sigs/kubebuilder/issues/3524

We will proceed based on the assessment's results, taking into consideration the best approach for the project's needs.

Thank you for all your understanding.

**Comment by camilamacedo86** [comment]
HI @hsyed-dojo 

> I’d like to advocate to make this opt-in and that the additional manifests are only generated if a CI flag is provided during the init.

I need to let you know that you can opt-out by commenting the following line in the `config/default//kustomization.yaml`

```yaml
patches:
# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.
- path: manager_auth_proxy_patch.yaml
```
