### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by derecknowayback** [kubernetes-sigs/kubebuilder#3515]
I followed the instruction below: 
```bash
# download kubebuilder and install locally.
curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
chmod +x kubebuilder && mv kubebuilder /usr/local/bin/
```
And when I run my test it, I met the same problem like [#Issue326](https://github.com/kubernetes-sigs/kubebuilder/issues/326).
But ! I don't have any directory but a binary file `kubebuilder`.  There is nothing like `kubebuilder/bin` but a binary file itself.

**Comment by ashutosh887** [comment]
Let me check this @camilamacedo86 

/assign

**Comment by ashutosh887** [comment]
@derecknowayback 
Can you point me where did you get these installation instructions?

**Comment by camilamacedo86** [comment]
You are not using the latest version.
To run the tests you must have the binaries 

See that the binaries will be downloaded automatically via the makefile target envtest-setup:

https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/Makefile#L160-L163

So, please check in the PROJECT file what is the layout of the project that you have.
If you are using go/v2 or go/v3 I suggested you update your project, see: https://book.kubebuilder.io/migration/v3vsv4

However, another option is just copy and past the Makefile targets test and envtest-setup from : https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/Makefile

So that you will solve this issue. Note that you should ensure that the code changes/version still compatible within the versions used in your project.

In this way, I am closing this one as sorted out. However, feel free to re-open if you see that is required.
