### ISSUE TITLE
doc: quotes are displayed as &#34; in description of kubebuilder markers on CRD Validation page

### ISSUE THREAD

**Issue by tenstad** [kubernetes-sigs/kubebuilder#3534]
### What broke? What's expected?

See expanded description of `+kubebuilder:default` on [CRD Validation](https://book.kubebuilder.io/reference/markers/crd-validation.html?highlight=%22#crd-validation), which appears to come from [controller-tools/pkg/crd/markers/validation.go](https://github.com/kubernetes-sigs/controller-tools/blob/498444bd78eb90dbdf228dfd9ad333d68fe354e7/pkg/crd/markers/validation.go#L218)

The struct should be `{policy: "delete"}`, not `{policy: &#34;delete&#34;}`.

**Comment by camilamacedo86** [comment]
Hi @tenstad,

Thank you for raising it. Yes, the descriptions came from controller-tools project. Therefore, the content:

![Screenshot 2023-08-14 at 15 02 51](https://github.com/kubernetes-sigs/kubebuilder/assets/7708031/36cac036-1ad7-4b22-94c5-0eb7b0bb9ef5)

IN: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/reference/markers/crd-validation.md?plain=1

Then, the implementation which is responsible for generate this documentation can be found in: https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/utils/markerdocs

Also, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/markerdocs.sh

So, in order to address the issue described here is required to change its implementation in order to properly handle `"`. 

I will mark as help wanted and it might also be a good first issue. However, is required be able to analyse the code to know how properly change it out. Either is possible to verify the change in the doc preview which is available for each PR done against master, see;

![Screenshot 2023-08-14 at 15 10 22](https://github.com/kubernetes-sigs/kubebuilder/assets/7708031/1f5cdde5-110b-4726-b9c7-54741a5ebf4e)

**Comment by camilamacedo86** [comment]
It seems fixed so I am closing this one.
Feel free to re-open if you see a need for it.
