### ISSUE TITLE
Is there a way to watch the status of a CRD in a reconciler?

### ISSUE THREAD

**Issue by Kiruthika-Jayabalan** [kubernetes-sigs/kubebuilder#3550]
### What do you want to happen?

```
// SetupWithManager sets up the controller with the Manager.
func (r *XyzReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&v1.Xyz{},
			builder.WithPredicates(predicate.Or(predicate.GenerationChangedPredicate{}))).
Watches(&source.Kind{Type: &v1.ObjStatus{}},
		).
		Complete(r)
}
```

Something like this..

**Comment by camilamacedo86** [comment]
Hi @Kiruthika-Jayabalan,

By doing: `builder.WithPredicates(predicate.Or(predicate.GenerationChangedPredicate{}))).
Watches(&source.Kind{Type: &v1.ObjStatus{}},` it seems for me that you are waching an object that is Status.

See that, if you do like:

```go
return ctrl.NewControllerManagedBy(mgr).Owns(&argocdv1beta1.Register{}).
		For(<Resource that is the owned of this controller, the principle one which the controller is responsable for>).
		Owns(<Any resource that is created by the controller>).
		Complete(r)
```

You will watch the change in both resourced and you will re-trigger the reconcile in any scenario. 
However, you can either work within Predicates. To do so, look: https://sdk.operatorframework.io/docs/building-operators/golang/references/event-filtering/

It allow you filter what should or not re-trigger the reconciliation. For instance, ignore updates without some kind of label. 

I hope  that the above info answer your question. If not, I would recommend you raise those to controller-runtime (https://github.com/kubernetes-sigs/controller-runtime) since this is the project which owns the logic to do the watches and etc. You can either check in the slack their channel.

In this way, I am closing this one as sorted out but feel free to re-open if you see that fits.
