### ISSUE TITLE
Failed to create multi-version API 

### ISSUE THREAD

**Issue by linglingye001** [kubernetes-sigs/kubebuilder#3672]
I have followed the tutorial https://book.kubebuilder.io/multiversion-tutorial/tutorial to create multi-version API. In my project, current API version is v1beta1. I want to create v1 version API but failed.
```
kubebuilder create api --group test --version v1 --kind testCR
Create Resource [y/n]
y
Create Controller [y/n]
n
INFO[0004] Writing kustomize manifests for you to edit...
INFO[0004] Writing scaffold for you to edit...
Error: failed to create API: unable to scaffold with "base.go.kubebuilder.io/v3": error scaffolding API/controller: unable to load boilerplate: open hack/boilerplate.go.txt: no such file or directory
```

kubebuilder(CLI) version
`Version: main.version{KubeBuilderVersion:"3.12.0", KubernetesVendor:"1.27.1", GitCommit:"b48f95cd5384eadcdfd02a47a02910f72ddc7ea8", BuildDate:"2023-09-06T06:04:11Z", GoOs:"linux", GoArch:"amd64"}`

PROJECT version
`version: "3"`

Other version 
`go version go1.20.6 linux/amd64`

**Comment by camilamacedo86** [comment]
Hi @sbueringer,

This issue is solved already.

However, go/v3 has been deprecated for an extended period and will no longer be supported after the next bump of k8s.
Therefore, the fix was applied ONLY to go/v4. More info: https://github.com/kubernetes-sigs/kubebuilder/discussions/3622

See: https://github.com/kubernetes-sigs/kubebuilder/issues/3373

PRs:
- https://github.com/kubernetes-sigs/kubebuilder/pull/3378
- https://github.com/kubernetes-sigs/kubebuilder/pull/3391

**Workaround**
You can create the hack/boilerplate.go.txt manually for no longer face this one such as: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/hack/boilerplate.go.txt

Therefore, I am closing this one as sorted. 
 Thank you for raising it 🎉
