### ISSUE TITLE
docs: Marker docs about required fields are not fully accurate

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/kubebuilder#3675]
### What broke? What's expected?

In CRD validation documentation (https://book.kubebuilder.io/reference/markers/crd-validation) `//+kubebuilder:validation:Required` marker is advertised as "specifies that this field is required".

However, it seems for a struct field, empty struct in a YAML manifest (i.e. `{}`) or for a string field empty string `""` bypasses this check.

I think it's somewhat misleading that this validation allows zero values (which the `omitempty` would've omitted) through just fine.

### Reproducing this issue

1. Use package level `//+kubebuilder:validation:Required` 
2. Do not specify `",omitempty"` on a string field.
3. `kubectl apply --validate=false` your custom resource without specifying the field → observe the validation error
4. specify `""` as the value for the string field and re-apply → no error.

### KubeBuilder (CLI) Version

3.10.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

### Other versions

sigs.k8s.io/controller-runtime v0.16.2
kube-apiserver 1.21.14
kubectl 1.21.14

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @ahmetb,

By defining a String spec with "" you are defining a string with an empty value. 
So, it does not seem to be an error but the expected behaviour. 

In your case scenario, seems that you want ensure that:
a) The String spec exist  ( `+kubebuilder:validation:Required` )
b) If its value is bigger than X size ( `+kubebuilder:validation:MinLength` )

So you would need to use both.

However, if you think that the description or behaviour should be changed then can you please raise an issue against: https://github.com/kubernetes-sigs/controller-tools.

See that the markers are defined in this project. Kubebuilder uses controller-gen (controller-tools) to perform these validations. Indeed the doc is generated automatically from the descriptions added in controller-tools, see: https://github.com/kubernetes-sigs/controller-tools/blob/f185f4d8e8f1c0a006fee16fbb80c832594a1fcf/pkg/crd/markers/validation.go#L77

Therefore, I am closing this one.
But if you need, please feel free to reopen this one.
