### ISSUE TITLE
Add support for configuring `boilerplatePath` during API scaffolding on plugin `base.go.kubebuilder.io/v4`

### ISSUE THREAD

**Issue by ardikabs** [kubernetes-sigs/kubebuilder#3697]
### What do you want to happen?

*Description*:

Currently, I've configured my operator to adhere to an opinionated directory structure preference, causing me to execute `kubebuilder` with a non-default plugin, which is `base.go.kubebuilder.io/v4`. However, `kubebuilder` seems to define a hardcoded boilerplate path attribute in `hack/boilerplate.go.txt` during API scaffolding, as can be seen below at line 70:
https://github.com/kubernetes-sigs/kubebuilder/blob/26ee6711f7cd126d3490f1dfb8e2e648ddc60fac/pkg/plugins/golang/v4/scaffolds/api.go#L66-L77

*Feature Request*:

Could it be configured to accommodate an opinionated directory structure when attempting to satisfy certain preferences? say i expect the boilerplate refer to `tools/hack/boilerplate.go.txt`, as compared to `controller-gen` tool that could refer to a custom `headerFile` like below:
```bash
controller-gen object:headerFile="/path/to/boilerplate.go.txt"`
```

*Plugin*: `base.go.kubebuilder.io/v4`

**Comment by camilamacedo86** [comment]
Hi @ardikabs,

Thank you for bringing up this issue. I agree that the ability to customize all paths, not just specific ones, would be a valuable addition to Kubebuilder. A config file allowing users to define paths for controllers, hack, etc., would indeed enhance the tool's flexibility.

However, introducing such customization for only one aspect without addressing the others would lead to inconsistency in behavior. We aim for a uniform and predictable user experience. Therefore, implementing this feature across the board is crucial, albeit it introduces significant complexities.

Given these considerations, the best approach would be to develop a detailed proposal. This document would outline the implementation strategy, consider potential problems, and propose solutions. You can find a template for proposals here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/template.md, and some examples at: https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs.

As a temporary measure for the current issue, one possibility could be to issue a warning instead of an error when the boilerplate is not found, though this might be perceived as a bug by some users. However, it might be an acceptable interim solution.

We're definitely open to contributions that would help us move in this direction. 
Would you be interested in working on this feature?

**Comment by ardikabs** [comment]
Hi @camilamacedo86 , seems I missed the notification, sorry for the late response.

It seems there is no error produced when `hack/boilerplate.go.txt` file is missing because it will be overridden with [an empty value](https://github.com/kubernetes-sigs/kubebuilder/blob/4575a55eb4a6d52119ebd65fbe9da1669d963fc6/pkg/plugins/golang/v4/scaffolds/api.go#L73), the only error that occurs is when `hack/boilerplate.go.txt` isn't a valid file like permission denied on read, etc. 

Nevertheless, I am willing to address this concern by modifying `kubebuilder` to issue a warning rather than an error when an issue arises while reading the file.

Regarding the design proposal, I am interested in contributing to it. However, I'm unsure if focusing solely on `hack/boilerplate.go.txt` is acceptable as a design proposal, as it appears to be a relatively minor feature request.

**Comment by camilamacedo86** [comment]
Hi @ardikabs,

> It seems there is no error returned when hack/boilerplate.go.txt file is missing because it will be overridden with [an empty value](https://github.com/kubernetes-sigs/kubebuilder/blob/4575a55eb4a6d52119ebd65fbe9da1669d963fc6/pkg/plugins/golang/v4/scaffolds/api.go#L73), the only error that occurs is when hack/boilerplate.go.txt isn't a valid file like permission denied on read, etc.

So, that means what you need is done already :-) 
You are not blocked !!!

However, what you want and is asking here:  `Add support for configuring boilerplatePath` Then, as I said above: 

> Introducing such customization for only one aspect without addressing the others would lead to inconsistency in behavior. We aim for a uniform and predictable user experience. Therefore, implementing this feature across the board is crucial, albeit it introduces significant complexities.
> 
> IHMO: Given these considerations, the best approach would be to develop a detailed proposal. This document would outline the implementation strategy, consider potential problems, and propose solutions. You can find a template for proposals here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/template.md, and some examples at: https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs.

**Comment by mateusoliveira43** [comment]
About current structure (using `go/v4` and kubebuilder 3), is there any motivation to separate go files in 3 folders (api, internal and cmd). Adding them under a single folder could be a good approach? Example
```
├── pkg (or internal)
│   └── cmd
│       └── main.go (or without a sub folder, directly in pkg level)
│   └── controller
│   └── api
```

**Comment by camilamacedo86** [comment]
>  is there any motivation to separate go files in 3 folders (api, internal and cmd).

Yes, the default layout follow Golang/k8s Standards and Good Practies

- Api -> has the go files for APIs
- Internal -> where you find all that would not make sense import, in your case the controllers.
- cmd - is where we run the cmd init by default 
- Also, the license is inside of hack because it is also a k8s convection

More info:

- https://github.com/golang-standards/project-layout
- About hack dir: https://pkg.go.dev/k8s.io/kubernetes/hack#:~:text=The%20hack%20directory%20contains%20many,scripts%20are%20helpful%20for%20contributors.
- https://github.com/kubernetes-sigs/kubebuilder/pull/2985

Note that any change in the layout and how we scaffold is discussed a lot and cannot be done easily.

**Comment by mateusoliveira43** [comment]
thanks for the detailed explanation @camilamacedo86 !

**Comment by ardikabs** [comment]
Hi @camilamacedo86 , i have submitted a [PR](https://github.com/kubernetes-sigs/kubebuilder/pull/3716) for this request, but instead of storing to `PROJECT` file, it seems to me that would be better to loosen that constraint and allow adjustment through flags on every attempt when invoking the command (e.g., `init`, `create api`, and `create webhook`)

**Comment by camilamacedo86** [comment]
Hi @ardikabs 

> Hi @camilamacedo86, i have submitted a https://github.com/kubernetes-sigs/kubebuilder/pull/3716 for this request, but instead of storing to the PROJECT file, it seems to me that it would be better to loosen that constraint and allow adjustment through flags on every attempt when invoking the command (e.g., init, create API, and create webhook)

What you want to change here is related to the base of the Project
That means the only way to do that would be in the init command
Then, could you track it out in the ProjectConfig as described in the PR? 

Change it is outside of the domain of responsibility of create API, and create webhook commands

**Comment by ardikabs** [comment]
I see, in other words, we need to introduce a new field in the PROJECT file, yes? I think this would also make sense if we add a possibility to change the boilerplate path under the `edit` command, what do you think? @camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @ardikabs 

Yes. We need to:

- a) add the new spec to the ProjectConfig i.e. `header-file-path` or `boilerplate-path` (see the pkg/config: https://github.com/kubernetes-sigs/kubebuilder/blob/66c3572c9b4b6b918c129eaa5b27abe842c54c2a/pkg/config/v3/config.go#L55-L74)
- b) allow passing the flag in the init|edit commands
- c) ensure that the hack/[boilerplate.go.txt](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/hack/boilerplate.go.txt) will be generated in this path
- e) that in this case, hack/bolleplate.go will not exist/delete (if has only this file in the hack delete the dir otherwise the file)
- f) also, the makefile target will be scaffolded or updated accordingly ( see an example of how we do those replaces in : https://github.com/kubernetes-sigs/kubebuilder/blob/66c3572c9b4b6b918c129eaa5b27abe842c54c2a/pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go#L208-L213 ). If not possible to update then we should warn

I hope that clarifies.
