### ISSUE TITLE
More Development Makefile commands

### ISSUE THREAD

**Issue by mateusoliveira43** [kubernetes-sigs/kubebuilder#3703]
### What do you want to happen?

Would be awesome to add more commands to the Development section of the Makefile, and improve existing ones
https://github.com/kubernetes-sigs/kubebuilder/blob/3c9cf656ce4d62a10c8e78a1c0f066de47c983db/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L99-L119

As improvements
- Improve help messages. Example: `Run go vet against code` for me that usually work with Python, this is not clear. Telling that a linter will be run, for example, seems better
- `test` command seems to do too many things

Suggestion of new command
- A `ci` command would be awesome! Something that checks if Go code is formatted, if  files are up to date (were genearted), etc. Example of auxiliary command idea for this task
  ```makefile
  .PHONY: fmt-is-updated
  fmt-is-updated: TEMP:= $(shell mktemp -d)
  fmt-is-updated:
	  @cp -r ./ $(TEMP) && cd $(TEMP) && make fmt && cd - && diff -ruN . $(TEMP)/ && echo "Go code is formatted" || (echo "Go code is not formatted, run 'make fmt' to format" && exit 1)
	  @chmod -R 777 $(TEMP) && rm -rf $(TEMP)  
  ```

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43

Thank you a lot for raising it. 

You are using the Makefile of go/v3. The layout go/v3 has been deprecated for a long time and will no longer be available in the next N+2 release
See; 
- https://kubebuilder.io/plugins/go-v3-plugin
- https://github.com/kubernetes-sigs/kubebuilder/discussions/3622

Therefore,  could you please check the Makefile: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/Makefile 

And let us know if you would like to propose changes.

Also, assuming yes, can you let us know your motivation? What problems do you have now that would be sorted out with the changes proposed?

**Comment by mateusoliveira43** [comment]
Yes, I indirectly use Makefile of go/v3, because I use the one created by Operator SDK. Should I ask there when they will start to use go/v4? (I think there is already an alpha version)

Will take a look into Makefile of go/v4 and get back to you, thanks!

**Comment by mateusoliveira43** [comment]
You were right, I can use `go/v4` with Operator SDK. Example command
```sh
operator-sdk \
    --plugins go.kubebuilder.io/v4-alpha \
    --project-version 3 \
    init --project-name=<name> \
    --repo=<repo> \
    --domain=<domain>
```

About changes I would suggest

- add a CI command. The idea would be a similar to `test` command. The motivation is if we use it in a CI environment, it can give us false positives (example, I new contributor to a project proposed some changes, but did not run `fmt` or `manifest` command, which the command does automatically).
- add a version check to `golangci-lint` (maybe to all tools), like is done with kustomize. Also, remove `fmt` and `vet` commands? I am not yet totally familiar with `golangci-lint`, but I believe it does the same with `lint` and `lint-fix` comamnds. As motivation, users can silent use wrong version of tools in local environment.

If the changes are accepeted, I would be glad to work on adding them :smile:

**Comment by camilamacedo86** [comment]
@mateusoliveira43 

You are using an old release of Operator-SDK
If you use it from the source or the latest release: https://github.com/kubernetes-sigs/kubebuilder/blob/v3.13.0/cmd/main.go#L60-L63

You should get the go/v4 layout by just running operator-sdk init
Also, the name of the plugin is go/v4 
go/v4-alpha was its name until it came to be stabilized.

**Comment by mateusoliveira43** [comment]
I think not. I am using 1.32.0 for my tests. Reference https://github.com/operator-framework/operator-sdk/releases

If I try to run like this
```sh
operator-sdk \
    --plugins go/v4 \ # or go.kubebuilder.io/v4         
    --project-version 3 \
    init --project-name=<> --repo=<> \
    --domain=<>
```

I get this error
```
FATA[0000] no plugin could be resolved with key "go/v4" for project version "3"
```

And in the help command, I see this
```
Default plugin keys: "go.kubebuilder.io/v3"
Default project version: "3"
```

Maybe on master is already updated, but did not try with it.

But for suggestions on the Makefile, I used this as base https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/Makefile

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43,

> FATA[0000] no plugin could be resolved with key "go/v4" for project version "3"

**Response:** You should consider raising an issue against the Operator-SDK repository. The maintainers need to look into this issue. According to the Kubebuilder code ([source code reference](https://github.com/kubernetes-sigs/kubebuilder/blob/v3.13.0/cmd/main.go#L60-L63)), the default plugin is `go/v4`. Thus, running either `operator-sdk init` or `operator-sdk init --plugins=go/v4` should yield the same result.

> But for suggestions on the Makefile, I used this as base https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/Makefile

**Regarding your request:**

> Improve help messages. Example: Run go vet against code for me that usually work with Python, this is not clear.

Kubebuilder doesn't support Python; it's tailored for Go. The `go vet` command is a Go-specific tool. If there's confusion about this, could you specify how the documentation or help messages could be improved for better clarity?

> test command seems to do too many things

The `test` target in the Makefile is designed to run a series of commands including manifest generation, formatting, and vetting before executing the tests. Here's the snippet:

```makefile
.PHONY: test
test: manifests generate fmt vet envtest ## Run tests.
    KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" go test $$(go list ./... | grep -v /e2e) -coverprofile cover.out
``` 

> Suggestion of a new command
> A ci command would be awesome! Something that checks if Go code is formatted, if files are up to date (were  generated), etc. Example of auxiliary command idea for this task

It could be misleading as it might imply end-to-end testing rather than format checks. However, the existing fmt and vet targets cover your requirements:

```
.PHONY: fmt
fmt: ## Run go fmt against code.
    go fmt ./...

.PHONY: vet
vet: ## Run go vet against code.
    go vet ./...
```

These commands are already part of the make test target, aligning with what you're looking for. Additionally, the lint target utilizes [golangci-lint](https://github.com/golangci/golangci-lint), a popular linter in Go projects:

```
.PHONY: lint
lint: golangci-lint ## Run golangci-lint linter & yamllint
    $(GOLANGCI_LINT) run
```

It appears we already have the functionality you're requesting. The confusion might stem from unfamiliarity with the Go language, which is the primary language supported by Kubebuilder.

I believe we can consider this issue resolved. However, if you have further suggestions or specific change requests, please feel free to raise an issue with detailed explanations.

I hope that you do not mind but I am closing this one.

**Comment by mateusoliveira43** [comment]
I will try to open a PR with my suggestions when I have time
