### ISSUE TITLE
Include CRD viewer and editor roles in kustomization file?

### ISSUE THREAD

**Issue by joelanford** [kubernetes-sigs/kubebuilder#3782]
### What do you want to happen?

When I create a new API, kubebuilder automatically generates viewer and editor roles that could be used to give end users access to the API.

However, it doesn't look like Kubebuilder adds references to these new files in the `./config/rbac/kustomization.yaml` file, which means they don't end up being applied as part of the kustomize build + kubectl command.

It would be nice if Kubebuilder automatically added these to the kustomization file when it creates them.

**Comment by camilamacedo86** [comment]
It definitely would either help us ensure at least that the syntax is correct.  
+1

Adding good first issue here, since it seems very easy to be a good fit.

**Comment by camilamacedo86** [comment]
Hi @joelanford,

Thank you for bringing this to our attention.

Upon initial consideration, I saw merit in the suggestion as a means to ensure syntax correctness during test executions. However, after a moment of reflection, I chose to delete my previous comment and remove the label to prevent any confusion.

> Those rules are merely helpers; they are not utilized by the manager itself. Indeed, they can be removed from the project. The individuals who could benefit from them are those operating the solution. More information about its motivation can be found at https://github.com/kubernetes-sigs/kubebuilder/issues/886.

**So, why should we add those to the kustomize configuration for the Manager? What advantages would it bring for the users to have these applied when we deploy the manager? What is the use case?**

To be honest, I also do not know how much value these rules bring, since their purpose is not very clear. I wonder if we should actually not remove them in a future version. WDYT?

**Comment by camilamacedo86** [comment]
Hi @joelanford 

Yep, I go along with your thoughts.

Honest, I cannot think how option 1 could bring any harm.
Maybe, apply what is not necessary to the cluster? 
 Did you see any cons/downsides beyond that?

Furthermore, I think it would be great to have comments in the kustomize where those are applied to try to bring clarity about their purpose. Therefore, I think I am fine either with us:

a) Add it to be applied by default via the kustomize (so that we will start to cover at least the syntax in our e2e tests as well)
b) Then, ensure that we have a nice comment explaining its purpose/motivation: https://github.com/kubernetes-sigs/kubebuilder/issues/886

**It seems a good one for first good issues too. 
I am adding the label.**

**Comment by lunarwhite** [comment]
Hi @camilamacedo86, I'd like to help with this issue, and want to comfirm:

How/When should `*_viewer_role.yaml` and `*_editor_role.yaml` be added to rbac/kustomization file?

a. By `init`. One way is to directly modify `kustomizeRBACTemplate`: https://github.com/kubernetes-sigs/kubebuilder/blob/8afeb403549fa87bf55a00e10a819a34719eec53/pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/kustomization.go#L45-L63
b. By `create api`. We might implement it after `CRDEditorRole` and `CRDViewerRole` are generated:

https://github.com/kubernetes-sigs/kubebuilder/blob/8afeb403549fa87bf55a00e10a819a34719eec53/pkg/plugins/common/kustomize/v2/scaffolds/api.go#L64-L104

Please correct me if I misunderstood. Any additional suggestions would be appreciated.

**Comment by camilamacedo86** [comment]
Hi @lunarwhite,

First, that is great. We appreciate your help.
The view/editor roles are created for each API, so we create them when we create the APIs.
Therefore, it seems the place where we should do that.
