### ISSUE TITLE
Kubebuilder docs should more clearly state the interaction between `kubebuilder:validation:Required` and `omitempty`

### ISSUE THREAD

**Issue by jmeyers35** [kubernetes-sigs/kubebuilder#3794]
### What broke? What's expected?

This is purely a docs ask. I've run into the behavior noted in https://github.com/kubernetes-sigs/controller-tools/issues/599 a handful of times, and I think that it can be pretty surprising. The most recent time I've hit this, it caused us to break backwards compatibility in a user's CRD when we removed an `omitempty` tag on a field. I think that the interaction between the required tag and `omitempty` should be more explicitly stated in the documentation (and maybe a warning added at generation time: you probably _don't_ actually want both `required` and `omitempty`).

### KubeBuilder (CLI) Version

N/A

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @jmeyers35,

Thank you for raising this one. 

However, note that all documentation in kubebuilder is generated automatically via what is the doc in the source code of controller-tools. Therefore:

- a) Can you please transfer this issue to the controller-tools repo. Your request cannot be addressed via Kubebuilder repo/code source or project

- b) WDYT about open a pull request for controller-tools with the changes that you suggest. Therefore, when a new controller-tool release is made with it, the Kubebuilder docs will be updated. 

Thank you for attention.

@vincepri @joelanford (could you please move this issue to controller-tools if the owner be unable to do so?)

**Comment by jmeyers35** [comment]
I'm happy to open a PR for this at some point, but I wanted to flag this in case someone can get around to it before I can. I also could've been a bit more specific - when I said "documentation", I really meant the book, which I believe is indeed in this repo. But this is probably worth noting in the generated docs as well.

**Comment by camilamacedo86** [comment]
Hi @jmeyers35,

That is great. I see, the info that you would like to add in the docs is:

> Update:
> The omitempty tag in Foo string `json:"foo,omitempty"` had more precedence than the kubebuilder marker +kubebuilder:validation:Required therefore making the resultant generated crd field to be optional.
> 
> The +kubebuilder:validation:Required marker does works as desired when omitempty is not used.
> 
> I am not able to recall if docs(https://book.kubebuilder.io/) mentions it, but I hope it does.
> 
> With that I mark this issue to be closed.

Please feel free to open a PR with your suggestion on where you see that it should fit, and then we can move forward from there. 

_PS.: You might want to add this info to https://book.kubebuilder.io/reference/markers.html?highlight=omitempty#markers-for-configcode-generation. Then, in this part, the code is here._ 

Thank you for your collaboration 🥇

**Comment by camilamacedo86** [comment]
Hi @jmeyers35 

After share above the info to you, do you think that it still requiring further explanation?
Would you like to contribute with this one?

**Comment by jmeyers35** [comment]
the latter would work for me.

**Comment by camilamacedo86** [comment]
Hi @jmeyers35  and @mateusoliveira43 

We need to clarify the changes in : https://book.kubebuilder.io/reference/markers.html?highlight=omitempty#difference-between--optional-and--kubebuildervalidationoptional when we bump a new release within https://github.com/kubernetes-sigs/controller-tools/pull/944

c/c @sbueringer ^

**Comment by TAM360** [comment]
@camilamacedo86  @jmeyers35 @mateusoliveira43 I would like to work on issue if anyone isn't working on it.

**Comment by camilamacedo86** [comment]
Hi @jmeyers35 @mateusoliveira43 @TAM360 

The documentation in Kubebuilder is generated automatically.
See that we update master branch to generate the docs with the latest and the docs in https://book.kubebuilder.io/ will ge updated with the latest comments and docs introduced in the source code of https://github.com/kubernetes-sigs/controller-tools in the next release.

The update was done in the PR https://github.com/kubernetes-sigs/kubebuilder/pull/4010.

> Do we still need to add some documentation around this to close this issue, or just update controller-tools version used by kubebuilder to start using new behavior?

Look at https://deploy-preview-4010--kubebuilder.netlify.app/reference/markers
- If any info regards the controller-gen markers which are generated automatically still missing then it must be added in the controller-tools 

**Example:**

The info in https://deploy-preview-4010--kubebuilder.netlify.app/reference/markers/crd-validation:

<img width="823" alt="Screenshot 2024-07-23 at 05 33 22" src="https://github.com/user-attachments/assets/c4ebc3bd-0246-45ce-ab4a-e167e0f30ff0">

It is defined in:

https://github.com/kubernetes-sigs/controller-tools/blob/6c5158f6ba35809949d8594be48fb3df63a856a7/pkg/crd/markers/validation.go#L288-L295

So that, when we bump controller-gen in Kubebuilder docs those changes will be automatically reflected.

-However, if you want to supplement or change the Kubebuilder docs like in this NOTE: https://book.kubebuilder.io/reference/markers#difference-between--optional-and--kubebuildervalidationoptional

See:

<img width="799" alt="Screenshot 2024-07-23 at 05 36 21" src="https://github.com/user-attachments/assets/b24041c6-3859-4d37-9d1f-b76649dba25e">

Then, the change would be in the Kubebuilder docs:

https://github.com/kubernetes-sigs/kubebuilder/blob/4c4103ea68d1cf38a7f5941c52277069e620da96/docs/book/src/reference/markers.md?plain=1#L18-L29

## Conclusion

In this way, I am closing this one sorted out with the PR https://github.com/kubernetes-sigs/kubebuilder/pull/4010 assuming that the controller-gen docs are properly updated. However, if you see any documentation in Kubebuilder which should be properly updated. Like the above NOTE (https://github.com/kubernetes-sigs/kubebuilder/blob/4c4103ea68d1cf38a7f5941c52277069e620da96/docs/book/src/reference/markers.md?plain=1#L18-L29) please feel free to push a PR with the proposed changes.

I hope that make sense, thank you a lot for your collaboration 🥇

**Comment by TAM360** [comment]
@camilamacedo86 I think it's sufficient. As long the docs in `controller-gen` are getting updated, and it resolves this issue, it's fine. We can explicitly add the same detail in Kubebuilder's docs in future, if it gets reported more frequently.

**Comment by guettli** [comment]
BTW, this tool can help to detect errors like that: CRD linter kal: https://github.com/JoelSpeed/kal
