### ISSUE TITLE
Support for different reconcile events

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes-sigs/kubebuilder#38]
Currently, `Reconcile` loop will be triggered periodically or by any event. It would be great if the controller provides the functionality to perform specific reconcile effort based on event type. For example, there are 3 loops for `add`, `update`, and `delete` events (or one reconcile loop that performs differently based on event type).

@pwittrock
/cc @liyinan926

**Comment by pwittrock** [comment]
@crimsonfaith91 This is a bit of an anti pattern since it is an edge-based approach and Kubernetes controllers are typically level-based.  Support for this exists with [WatchEvents](https://godoc.org/github.com/kubernetes-sigs/kubebuilder/pkg/controller#GenericController.WatchEvents) but I don't think we want to make it overly accessible.
