### ISSUE TITLE
Access resource of another CRD

### ISSUE THREAD

**Issue by shach33** [kubernetes-sigs/kubebuilder#3805]
### What do you want to happen?

I am creating a CR controller where I get a configuration value. I need to further go and edit this value into the config of another CR.  

For example, I take a namespace name 'x' and I need to add a new pipeline in another CR 'y'. Manually I would do 

kubectl edit y 

and then change. However I am trying to do it using kubebuilder through my CR. Is it even possible? How can I access resources of another CR in my operator.

**Comment by camilamacedo86** [comment]
Hi @shach33,

Yes, you can accomplish that. It's important to understand that when you're creating a Custom Resource Definition (CRD) and its associated controller, you're essentially managing specific aspects of your Kubernetes cluster that are tailored to your business or solution's needs. For instance, consider Controller A, which is responsible for managing a custom resource, Thing A. To effectively manage Thing A within your cluster, you would typically need to interact with various Kubernetes objects such as Services and Deployments. This management is done within Controller A, where you'll import and manage these objects.

Similarly, you can also manipulate another CRD, let's call it CRD B, from within the controller for CRD A. This is particularly useful for cases where one resource depends on another.

**Therefore, in other words, when you extend the K8s API and create your OWN APIs/CRDs you can use at the same way that you use the K8S ones. So, at the same way that you for example watch a ConfigMap you can watch a "Your OWN Kind X" and go on.** 

## Example Solution

Take, for example, a project where one CRD represents a database and another CRD represents a backup process. It wouldn't be practical to initiate a backup if the database it depends on doesn't exist. Hence, within the backup's controller, there's functionality to monitor the database CR in the cluster to ensure that backups are only attempted when the database is present and to gather necessary information from the database for the backup process.

See: 

- Project to Manage a Postgree Database: https://github.com/dev4devs-com/postgresql-operator
- See that we are watching resources created by the Database Controller: https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/backup/controller.go#L60-L63



Please note that the project mentioned above is somewhat outdated and uses older syntax and Kubernetes API versions. However, it serves as a valuable example to understand the concept and the operational dynamics between different CRDs and their controllers.

To know more about:
- See watching: https://book.kubebuilder.io/reference/watching-resources
- See getting started: https://book.kubebuilder.io/getting-started (15 min it will give a very good idea over how the things work)
- See: https://book.kubebuilder.io/cronjob-tutorial/gvks (it will help you out understand the APIs)

I am closing this one, since I think the above info answer your question.
however, feel free to re-open or open new issues as you see fit.

**Comment by shach33** [comment]
This is great. Thankyou @camilamacedo86 !
