### ISSUE TITLE
Trailing spaces in generated README.md

### ISSUE THREAD

**Issue by bzub** [kubernetes-sigs/kubebuilder#3812]
### What broke? What's expected?

After running `kubebuilder init` some lines in the README.md contain trailing whitespace.

### Reproducing this issue

Run `kubebuilder init`.

### KubeBuilder (CLI) Version

3.14.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43 

We can sort it out using shell script. Note that we try as much as possible not add dependencies with third-part. Use third-party solutions usually increase the effort to keep things maintained, it ofen make hard for contributors as well since to do something they might to skill up with so many other solutions.

Ideally, we should when we run `make generate` remove ALL trailing spaces of the docs for example. 
Feel free to check it out if you wish and proposed a solution

**Comment by camilamacedo86** [comment]
@bzub @mateusoliveira43

See now we can solve it across the whole project when we run make generate
Also, now we are checking of the spaces so we will not get merged stuff with trailing spaces.


See: https://github.com/kubernetes-sigs/kubebuilder/pull/3826

**Comment by mateusoliveira43** [comment]
Nice solution @camilamacedo86 Thanks!
