### ISSUE TITLE
Standardize config folders structure

### ISSUE THREAD

**Issue by mateusoliveira43** [kubernetes-sigs/kubebuilder#3821]
### What do you want to happen?

I think would be good to standardize the structure of folders generated under `config` folder. Example:
- `crd` folder has `bases` folder
- `samples` folder does not have `bases` folder

My motivation was an automation I added to a project, which was easier to add to folders that had `bases` folder

I believe the only change, would be that `kustomization.yaml` files would change resources section from `- file_name` to `- bases/file_name`

I also believe this problem is NOT A PRIORITY, just a nice to have feature

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43 

thank you for raising this one. Could you please let us know what scenario/when would be helpful we have the based in the samples?

**Comment by mateusoliveira43** [comment]
I was adding a controller generated by kubebuilder to an operator generated by operator sdk

so, I wanted to added needed files to the operator (CRDs, RBACs, image and samples) under its `config/` folder. For CRDs, I just copied folders under `crd/bases/` folder, for samples, I needed to add an `if` statement to not add `kustomization.yaml` file, only the CRD example files  in `samples/` folder.

I think for understanding `kustomize`, is also nice to have the struct of `bases/` folder.

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43 

If we do this change then would we introduce a breaking change?
That means:
- If we create a project with the CLI tool current version
- Then, use a new version with this change to scaffold new APIs
- Would that work or fail?

If that fail, then it can only be done within a new go layout version (go/v5). If that is the case, than we can link it to go/v5 milestone and when we have a lot of item that justify we have a go/v5 we can work on this one.
Otherwise, you mut ensure backwards compatibility in this implementation.

Cheers,

**Comment by mateusoliveira43** [comment]
I did not test, but I think would work yes

basically, is just the kustomize resource path that would change, right?

Example: created project with current version and ran `create api` command. That will create following structure:
```
config/samples
├── kustomization.yaml
└── group_version_name1.yaml
```
Afterwards I update to idea version, and ran `create api` command again, then structure will look like this:
```
config/samples
├── bases
│   └── group_version_name2.yaml
├── kustomization.yaml
└── group_version_name1.yaml
```
With `kustomization.yaml` looking like this
```yaml
## Append samples of your project ##
resources:
- group_version_name1.yaml
- bases/group_version_name2.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
```
But it does look less organized, as some files are in `config/samples/` and others are in `config/samples/bases/`, so being in `go/v5` works for me :smile:

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43,

 Sorry, but it still not clear for me what exactly would be under the bases:

```
config/samples
├── bases
│   └── group_version_name2.yaml
├── kustomization.yaml
└── group_version_name1.yaml
```

the samples is a bucket that has ONLY samples no CRDs
It should not have the CRDs at all. The crds are under CRDs. 

```
## Append samples of your project ##
resources:
- group_version_name1.yaml
- bases/group_version_name2.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
```

So it is not clear for me what is `group_version_name1.yaml` outside if bases and ` bases/group_version_name2.yaml` inside of the bases. Are you trying to say here:

- What I want is generate the samples under `config/samples/base` instead of `config/samples` so that I can create patches for my samples as we have for the CRDs
- IHMO it is not a breaking changes because projects that has been scaffolded with the samples under the existing path will still working after the change and will end up with:

```
## Append samples of your project ##
resources:
- group_version_name1.yaml
- bases/group_version_name2.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
```

is that what you are saying here?

**Comment by mateusoliveira43** [comment]
> What I want is generate the samples under config/samples/base instead of config/samples so that I can create patches for my samples as we have for the CRDs

Exactly! And would apply this to every folder under config

**Comment by camilamacedo86** [comment]
HI @mateusoliveira43 

Would you like to work on this one?
I think the first step here is to create a PR with the proposed changes, i.e:

> PR title: (go/v4;kustomize/v2): Ensure that config/ scaffolds are generated under the base Kustomize files, allowing the default scaffold to support customizations and patches in the kustomize directory

Then, if we ensure that after those changes all still working fine and passing in the CI 
we can send it out in the channels and ask for feedbacks. If no big objections be raised then we can move forward. 

WDYT?

**Comment by mateusoliveira43** [comment]
sure, I just need some time

Probably next week I would be able to open it :smile:

**Comment by mateusoliveira43** [comment]
@camilamacedo86 just an update, I am a little busy these days. I do not know when I will have time to work on the PR

(if someone else wants to work on it, please do :smile: otherwise, when I have time, I will do)

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43,

After reviewing and analyzing the proposal, I think we should avoid adding empty `bases` folders for all directories under `config`. Here’s why:

1. **Best Practices**: Scaffolding empty directories may not align with good practices, as they could lead to unnecessary clutter in the repository and increase maintenance complexity without adding functional value.
   
2. **Limited Community Interest**: Since this request has been open for over a year without community engagement or upvotes, it appears there is limited interest in this change.

With these points in mind, I propose we close this as a "not to do" for now. If you still feel strongly that this change is beneficial, here are some recommended next steps:

- **Open a Discussion Topic**: Start a proposal with your use case and examples.
- **Request Feedback**: Share the proposal in the channel and mailing list to gather community input and votes.

If there’s a clear community interest, we can revisit this and work on implementing the enhancement.

Thank you for your understanding!

**Comment by camilamacedo86** [comment]
I am closing this one based on https://github.com/kubernetes-sigs/kubebuilder/issues/3821#issuecomment-2446791155.
If you think that should be re-opened please feel free to do so.
