### ISSUE TITLE
Removing dependence on kubebuilder repo for docs generation

### ISSUE THREAD

**Issue by munnerz** [kubernetes-sigs/kubebuilder#395]
Currently the kubebuilder docs generation command creates a 'hidden' dependency on `sigs.k8s.io/kubebuilder`.

This comes about because of the 'swagger-gen' tool depends on `github.com/kubernetes-sigs/kubebuilder/pkg/docs` for the `WriteOpenAPI` function (see: https://github.com/kubernetes-sigs/kubebuilder/blob/1623901fc78e477a559e752ec055d892f80d84a9/cmd/kubebuilder/docs/docs.go#L208)

If someone wants to use this tool but *does not* use kubebuilder for other aspects of their project, they will have to vendor the kubebuilder repo in order to resolve dependency conflicts with other files in our own repos `pkg/apis`.

The function being depended on is *really* simple, and it'd be ideal if this could be generated into our own projects instead of introducing an additional dependency.

This would make the experience for users that aren't using all of kubebuilder a lot smoother IMO.

In the meantime, I have reconstructed what the `kubebuilder docs` subcommand does in a bash script: https://github.com/jetstack/cert-manager/blob/master/hack/update-reference-docs.sh

**Comment by droot** [comment]
@munnerz Thanks for bringing this up. This makes sense. There is a big TODO to make `docs` work for v1 projects. I think you are referring about v0 version projects in this case which will be deprecated soon. So we can approach the docs-generation from fresh and probably can move it `https://github.com/kubernetes-sigs/controller-tools` repo so that it is available as independent tool. If this is something interests you and lead the charge on, would be happy to assist you with whatever help needed.

**Comment by DirectXMan12** [comment]
docs generation hasn't worked in a while and was removed, closing
