### ISSUE TITLE
CRD marker reference is broken

### ISSUE THREAD

**Issue by sttts** [kubernetes-sigs/kubebuilder#4044]
### What broke? What's expected?

https://book.kubebuilder.io/reference/markers/crd.html shows
<img width="851" alt="Bildschirmfoto 2024-07-24 um 14 04 57" src="https://github.com/user-attachments/assets/9a1c85c4-51a0-40c4-8809-511e41f43d9a">

### KubeBuilder (CLI) Version

docs

**Comment by marlapativ** [comment]
@camilamacedo86 

https://github.com/kubernetes-sigs/kubebuilder/pull/4045

I've raised a pull request to fix this issue as I needed the docs.
Please have a look and merge if it's good.

**Comment by marlapativ** [comment]
@camilamacedo86 
The issue/pr was closed before my question got answered. 
Posting here just to confirm as I didn't understand what you mean by cherry-pick to branch book-v4

Should I raise a new pull request to `book-v4` from my fork, cherry-picking this commit?
(Asking as I am not a member, so wasn't sure what the process is)

Or should I raise a pull request from `master` to `book-v4` within this repo?

**Comment by camilamacedo86** [comment]
Hi @marlapativ 

Sorry, for do not explain it properly.
**No worry, I did this one already.**
https://github.com/kubernetes-sigs/kubebuilder/pull/4047

**Just to share:** 
Master is the branch where we work on
However, in this case we want the fix in prod asap
So, we need to
- create a branch from upstream/book-v4
- git cherry-pick <commit>
- create a new pr against book-v4

So that we just update with this fix not with all that is in master.
We only update the PROD docs when we do the releases .
Then, we move all from master to prod.

**Comment by marlapativ** [comment]
@camilamacedo86 

My bad, I now understand what you are trying to tell (it was basically to create a hotfix)

Thanks for taking care of it 
And also for letting me contribute.

The documentation works properly now. Have a great day!

**Comment by camilamacedo86** [comment]
THANK YOU !!!!
REALLY !!!

It was amazing !!!!
