### ISSUE TITLE
`kubebuilder update` generates Gopkg.toml with hardcoded versions

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/kubebuilder#419]
The `kubebuilder update` command currently generates a `Gopkg.toml` with hardcoded versions:

https://github.com/kubernetes-sigs/kubebuilder/blob/0f8f2d8a45b96ea4ba1d094946b39ef7c60d9202/cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/project/gopkg.go#L147-L153

This is made worse by the fact that this is below a header `# STANZAS BELOW ARE GENERATED AND MAY BE WRITTEN - DO NOT MODIFY BELOW THIS LINE.` which makes it look like end-users should not touch that part.

**Comment by droot** [comment]
@alvaroaleman Though the version in the dep stanza is `v0.1.1`, `dep` will pick the `v0.1.x` where x being the latest patch version on `v0.1.x` ([dep docs here](https://golang.github.io/dep/docs/Gopkg.toml.html#version)). This is intentional because we want newly created Kubebuilder project to pick the latest stable version on `0.1.x` of controller-runtime and controller-tools.

And if you want to update to new version to pick recent fixes on `v0.1.x`, you can run 'dep ensure -update sigs.k8s.io/controller-runtime`.

**Comment by alvaroaleman** [comment]
@droot I see, thanks for the clarification. I find that a little unintuitive tbh but that is obviously something on `dep` side.

Maybe we can change the lines to `version=">=v0.1.1"` to make this more obvious?

**Comment by justinsb** [comment]
I would +1 to changing this.  I'm using go modules, and it's confusing to have a version specified in Gopkg.toml that isn't actually what you intend to use.

**Comment by DirectXMan12** [comment]
No longer using dep, closing
