### ISSUE TITLE
Add access to client and scheme inside webhooks (defaulting and validating)

### ISSUE THREAD

**Issue by migueleliasweb** [kubernetes-sigs/kubebuilder#4218]
### What do you want to happen?

# Validator and Defaulter advanced usecases (with `client` and `scheme`)

For some advances cases, both mutating and validating webhooks can benefit from having access to `mgr.GetClient()` and `mgr.GetScheme()` to perform lookups prior to actioning changes to the incoming `runtime.Object`.

Currently, the template generated by `kubebuilder` appends the needed methods onto the original CRD struct definition from `api/<version>` (note that I'm aware the upcoming changes on https://github.com/kubernetes-sigs/kubebuilder/issues/4214 which moves things to  `internal/`) but this lacks the `client` and `scheme` variables/properties. This creates the need for users with slightly more advanced usecases to substantially move things around and deviate from the original generated code.

The current generated Go file looks like this:

## Defaulter
```go
// +kubebuilder:webhook:path=/mutate-<my-type>mutating=true,failurePolicy=fail,sideEffects=None,groups=<my-group>,resources=<my-type>,verbs=create;update,versions=<my-version>,name=<my-crd>.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &<my-generated-struct>{}
```

## Validator
```go
var _ webhook.Validator = &<my-generated-struct>{}
```

---

# The challenge

Enabling the `defaulter` and `validator` to have access to the cluster data via the `client` means the user will have to move those files around and diverge substantially from the initial generated template - on top of reimplementing some of the default tests to pass.

### Generate a `webook.Validator` separate struct that embeds the original type `struct` but also receives the `client` and `scheme`

Go-like pseudo-code below

```go
type <my-kind>Validator struct {
    <my-generated-struct>{} # original struct generated in `api/<version>`
    Client client.Client # injected
    Scheme *runtime.Scheme # injected
}

var _ webhook.Validator = &<my-kind>Validator{}
```

This is my preferred way as it allows users to further inject more components to their `struct` if they need.

A similar approach is used in https://github.com/kubernetes-sigs/controller-runtime/blob/main/examples/builtins/mutatingwebhook.go

```go
// +kubebuilder:webhook:path=/mutate--v1-pod,mutating=true,failurePolicy=fail,groups="",resources=pods,verbs=create;update,versions=v1,name=mpod.kb.io

// podAnnotator annotates Pods
type podAnnotator struct{
    // note that this struct is not related to the underlying type (in this case pod)
    // this gives full control to the user to inject dependencies
}

func (a *podAnnotator) Default(ctx context.Context, obj runtime.Object) error {
	log := logf.FromContext(ctx)
	pod, ok := obj.(*corev1.Pod)
	if !ok {
		return fmt.Errorf("expected a Pod but got a %T", obj)
	}

	if pod.Annotations == nil {
		pod.Annotations = map[string]string{}
	}
	pod.Annotations["example-mutating-admission-webhook"] = "foo"
	log.Info("Annotated Pod")

	return nil
}
```

Note that `podAnnotator` is unrelated to the underlying kind it's trying to mutate. This makes it so the user has full control of what the `validator` struct can look like.

### Pass `client` and `scheme` to the `Validation*()` and `Default()` methods

This might require changes to `controller-runtime` (afaik) but could look like this:

```go
func (r *<my-type>) ValidateUpdate(client client.Client, scheme *runtime.Scheme, old runtime.Object) (admission.Warnings, error) {}
```

```go
func (r *<my-type>) Default(client client.Client, scheme *runtime.Scheme) () {}
```

I'm not totally sure if there are best practices that go against the idea of querying data from the cluster during adminssion/validation but I'd assume this is a somewhat common pattern for sligthly advanced controllers.

I'd be happy to give it a go on implementing one of these ideas if they're deemed valuable.

**Comment by camilamacedo86** [comment]
Hi @migueleliasweb,

Thank you for raising this issue.

Please note that we can no longer use `webhook.Validator` and `webhook.Defaulter`, as these **were removed from Controller-Runtime.** Without addressing these changes, the code will not build with controller-runtime v0.20.0.

- Please, see the updated examples under the testdata to see the default scaffold for the next kubebuilder release 
https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v4/internal/webhook/v1

- The `PodAnnotator` example you shared aligns with Kubebuilder’s current scaffold, see:
https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/internal/webhook/v1/admiral_webhook.go#L46C1-L69C2

- You can also reference the CronJob tutorial for struct usage:  
https://github.com/kubernetes-sigs/kubebuilder/blob/e451dfea39a29b399d10f69f9e2d2b88a59ea4a7/docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook.go#L81-L91

We do not address breaking changes in the plugins unless necessary due to dependencies, as in this case with controller-runtime or bug fixes. To allow users still using the old path we've added a `legacy` flag, allowing webhooks to be scaffolded under the old `api` path. However, this still uses custom interfaces instead of `webhook.Validator` and `webhook.Defaulter`.

If you have suggestions for changes in controller-runtime, please raise them there. For any suggestions regarding Kubebuilder’s scaffold, feel free to check the examples and let us know what should be changed and why.

**We will close this issue since it seems that you want to change the controller-runtime implementation. However, feel free to re-open it if there are specific changes you think Kubebuilder should make.**

Thank you for your attention and contributions.

**Comment by migueleliasweb** [comment]
Hi @camilamacedo86 , thanks again for the swift reply.

It seems like I'm a bit early to the party. I've had a better look and the the upcoming release of `kubebuilder` seems to address a good chunk of my needs. I'l looking forward to start using it once it's released!

Thanks!

**Comment by camilamacedo86** [comment]
Hi @migueleliasweb,

Thank you so much for your valuable input!

If you feel that any changes should or could be made in Kubebuilder, please feel free to re-open this issue and let us know what needs to be added or modified, where, and why. If something some change should be addressed in controller-runtime, please add your request via an issue at: https://github.com/kubernetes-sigs/controller-runtime

The collaboration of the community is incredibly important to us, and we appreciate your continued support.
