### ISSUE TITLE
(kustomize/v2) (conversion webhook) Add a way to customize the `conversionReviewVersions` field

### ISSUE THREAD

**Issue by damsien** [kubernetes-sigs/kubebuilder#4428]
### What do you want to happen?

Currently, we generate the conversion webhook of the CRD using `v1` as default `conversionReviewVersions`.
https://github.com/kubernetes-sigs/kubebuilder/blob/43ee3f6c7873777dabf7dc6157e121b917abc0d7/pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go#L65-L66

This is not a good practice. As describe in the [Kubernetes documentation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-request-and-response), we should specify the "ConversionReview versions that are understood/preferred by the webhook".

The goal of this issue is to open a discussion on "How can we implement a way of specifying the *understood/prefered* version?".

I see two ways of doing this
1. Create a marker ( e.g.`// +kubebuilder:preferedconversion`) that we can add in the types file at the `type` level. Each type that have this marker will get their version added to the list.

OR

2. Search for all types that does not have the `// +kubebuilder:unservedversion` marker and add their version to the list.

**Comment by camilamacedo86** [comment]
Hi @damsien,

Thank you for raising this one.

**Note that the only version currently supported is `v1`, which is why this field has a fixed value.**

Previously, both `v1` and `v1beta1` were supported via the `webhook-version` flag, but this flag was removed in Kubebuilder release 4.0.0. As the Kubernetes release notes documented, **`v1beta1` was deprecated in Kubernetes 1.16 and fully removed from the Kubernetes API in release 1.22.**

**Therefore, anyone using Kubernetes versions >= 1.22 has only one valid option here: `v1`.**

---

### Important Notes:
- **Kubebuilder scaffold does not support Kubernetes versions <= 1.21.**  
  Our testing and support policy only covers the latest 3 Kubernetes releases.  
  See more details here: [Kubebuilder Security Policy](https://github.com/kubernetes-sigs/kubebuilder/blob/master/.github/SECURITY.md?plain=1).

However, if you think this issue should be reopened or if you’d like to continue discussing it, please feel free to reopen the issue or reach out to me directly.

**Comment by damsien** [comment]
@camilamacedo86 Yes you're right thanks
