### ISSUE TITLE
Get client.Client in webhook admission

### ISSUE THREAD

**Issue by FillZpp** [kubernetes-sigs/kubebuilder#505]
Now i create webhook admission using `kubebuilder alpha webhook ...`, and then find the webhook 
handler generated like this:
```
type MyResourceCreateUpdateHandler struct {
	// Client  client.Client

	// Decoder decodes objects
	Decoder types.Decoder
}
```

The `Client` which i need in webhook validating or mutating has been commented.
How could i get client or informer in webhook admission?

**Comment by mengqiy** [comment]
This is a documentation issue. I will update it.

I will use the [test project](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/project/) as an example to show you how to use a client:
1. Define a client by uncommenting https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/project/pkg/webhook/default_server/frigate/validating/frigate_update_handler.go#L39
2. Enable the injection by uncommenting https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/project/pkg/webhook/default_server/frigate/validating/frigate_update_handler.go#L68-L74
3. Add `"sigs.k8s.io/controller-runtime/pkg/client"` in the import section.
4. If the [import path] for your API type is not in the default path, adjust it. This scenario happens when the API is defined out of tree.

**Comment by FillZpp** [comment]
Thanks a lot @mengqiy 
I never noticed (2) before.

**Comment by mohnishkodnani** [comment]
When I run the following command. 
```kubebuilder alpha webhook --group core --version v1 --kind Pod --type=mutating --operations=create,update```

I get the following error : 
```pkg/webhook/add_default_server.go:24:2: undefined: AddToManagerFuncs
make: *** [vet] Error 2```

**Comment by mengqiy** [comment]
> Seems like webhook.go was not generated

@mohnishkodnani I guess the project was created by an older kubebuilder that doesn't support scaffolding webhook. It currently assume `webhook.go` was generated at `kubebuilder init` step, which may not be always true.
