### ISSUE TITLE
What is the process for supporting new version of Kubernetes?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kubebuilder#507]
Kubernetes releases a new major client-go every 3 months. Usually every release has some breaking that needs updating any library that uses k8s.io packages to same release. We are interested in using kubebuilder. I would appreciate if you could answer the following questions:

- What are the usual technical steps for updating kubebuilder to support a new version of Kubernetes?

- Are there any plans to do this at the same time a version of kubernetes is released? (like client-go etc.)

Thanks. /cc: @pwittrock

**Comment by tamalsaha** [comment]
xref: https://github.com/kubernetes-sigs/cluster-api/issues/522#issuecomment-427553009

**Comment by tamalsaha** [comment]
Thanks @droot ! 

Regarding timing, do you accept contributions on upgrading the runtime and tools? Or, things just stay in review until other downstream projects are ready to update?

In other words, if we send prs to upgrade these repos, will those be merged?

**Comment by droot** [comment]
> Regarding timing, do you accept contributions on upgrading the runtime and tools? Or, things just stay in review until other downstream projects are ready to update?

Yes, We accept contributions on upgrading and We don't wait for downstream projects to update. We do coordinate updating the deps in controller-runtime/tools at the same time because kubebuilder projects can't have the mix of tools and runtime depend on different k8s releases.

For last couple of releases upgrading k8s didn't introduce any breaking changes to the controller-runtime/tools API, so it has been mostly straight forward, but if they do then then will require bumping up the revisions for runtime/or tools which may require some communication and impact analysis.

**Comment by mengqiy** [comment]
@tamalsaha You are welcome to contribute.
https://github.com/kubernetes-sigs/controller-runtime/pull/221 is an example of upgrading k8s dependencies. You can see that even though there are breaking changes in `client-go`, there are no breaking changes at `controller-runtime` surface.

**Comment by droot** [comment]
Closing this issue since there aren't any next steps.
