### ISSUE TITLE
What is the proper way to compare resource object?

### ISSUE THREAD

**Issue by chenwng** [kubernetes-sigs/kubebuilder#592]
In the generated code, reflect.DeepEqual is used to check if the resource is changed. I created a deployment then used reflect.DeepEqual to compare it with the one fetched from k8s. The issue is the one fetched from k8s was changed by deployment controller (I assume it is) by filling with default values and is different from the deployment I constructed. This will trigger a update to deployment. And it seems this will happen continuously. Is this something expected? Or I am missing something?

Thanks.

**Comment by Adirio** [comment]
/triage support
Only pass the `Deployment.Spec` to `reflect.DeepEqual`. `Deployment.Status` is expected to change.

**Comment by ChenDoRo** [comment]
Thanks for your reply. I did some further tests. It is like what you said the Deployment.Status was kept being updated.
I also dumped the deployment spec fetched from api server. It looks like it was updated by deployment controller to fill with default values, but that was not the reason for the update event.  I think I misunderstood the reason for those update events.
If Deployment.Status is something I don't care about, how can I ignore those update events?

**Comment by Adirio** [comment]
Just don't take any action.
You could probably use a predicate to filter those events too but that will make little difference.

**Comment by nrfox** [comment]
I have run into this issue as well. I think doing `reflect.DeepEqual(generatedSpec, existingSpec)` on the whole spec can be problematic for a couple reasons.

1. If the apiserver does any defaulting of the resource object then the generated spec from the controller needs to be filled out entirely to ensure that the generated spec matches the existing spec.
2. This check: `reflect.DeepEqual(generatedSpec, existingSpec)` will always fail for certain resource types. Services of type ClusterIP that do not have their ClusterIP field set will get a ClusterIP assigned to them by the apiserver (or something internally). The deepequal check will fail and the controller will try to `Update` the service spec with the empty ClusterIP field and get an error back since this field cannot be updated once it has been set.

Maybe it’d be better if the scaffolding only compared for changes for things that the controller should take action on or are part of the CRD abstraction e.g. the `Replicas` field on the deployment should be updated if it doesn’t match the `Replicas` field on the CRD instead of doing a blanket deepequal on the spec.

**Comment by schweikert** [comment]
It also bothered me that too many unnecessary updates were done because of the DeepEqual, so I implemented this approach:
- Use [hashstructure](https://github.com/mitchellh/hashstructure) to calculate a hash of the deployment that I want to have
- Store that hash under an annotation ("mydomain/last-applied-hash")
- In the reconcile function, compare the stored hash with the newly computed hash,  and only update if they differ

This way, I don't need to do a deep-compare each time the reconcile function is triggered, and I also push less changes to kubernetes.

**Comment by daxmc99** [comment]
https://github.com/banzaicloud/k8s-objectmatcher might be a possible solution to this?

**Comment by DirectXMan12** [comment]
Server-side apply is the ultimate solution, when it eventually lands as beta.

**Comment by pepov** [comment]
@DirectXMan12 will the server-side apply solution work without contacting the API server? Isn't a dry-run call against the API necessary in that case as well?

**Comment by pepov** [comment]
Ideally (for example with https://github.com/banzaicloud/k8s-objectmatcher and controller-runtime of course) we get some (or most) of our managed objects from the cache and we can decide whether there are any changes or not locally.

I understand server-side apply is more elegant, but if it involves a call to the API server then it's not exactly a solution to the above problem.

**Comment by DirectXMan12** [comment]
@pepov with server-side apply, you do need to contact the api server, but you don't need to compare objects.  Instead, you explicitly set *all* the fields you care about on an empty object (not one you've gotten from the cache) and then submit that to the API server.  The API server takes care of figuring out the difference.  That means that you always submit against the API server, but that the submission doesn't always change things, without having to care about local comparison.

**Comment by DirectXMan12** [comment]
(whoops, didn't mean to close)

**Comment by pepov** [comment]
@DirectXMan12 the issue in our case was that we hit the API server too hard with too much requests, also the overall time for an operator cycle increased because of this.

**Comment by ChenDoRo** [comment]
> @pepov with server-side apply, you do need to contact the api server, but you don't need to compare objects. Instead, you explicitly set _all_ the fields you care about on an empty object (not one you've gotten from the cache) and then submit that to the API server. The API server takes care of figuring out the difference. That means that you always submit against the API server, but that the submission doesn't always change things, without having to care about local comparison.

In this case, when should we make the submit? If we make the submit in every reconciliation, will that cause too much load for api server in worst case? 
Btw, is this server-side apply available now?

**Comment by DirectXMan12** [comment]
@ChenDoRo ideally, no, it should not cause too much load, but it depends on your usecase.  It's in alpha now, and will most likely be beta in the next kubernetes release

@pepov was it actually a server-side issue?  You can also hit client-side rate limiting pretty easy with the default values.  At any rate, I'd be curious to see your numbers on that.

**Comment by JeremyMarshall** [comment]
Maybe late to the party but I raised this in kubernetes and they pointed me at https://github.com/kubernetes/apimachinery/issues/75

> apiequality.Semantic.DeepEqual, see https://godoc.org/k8s.io/apimachinery/pkg/api/equality)

**Comment by caarlos0** [comment]
> apiequality.Semantic.DeepEqual, see https://godoc.org/k8s.io/apimachinery/pkg/api/equality)

this still won't work in some cases, like when the default for a field is not its zero-value.

I end up doing the same thing @schweikert recommended.

**Comment by feloy** [comment]
I also have the problem using reflect.DeepEqual or equality.Semantic.DeepEqual because some fields are set with default non-zero values by some controller (like ImagePullPolicy, RestartPolicy, and so on) if these fields are not set by the operator.

I found this utility function that makes the job for me: it compares only fields that are non-zero in the expected struct:

```go
import "k8s.io/apimachinery/pkg/api/equality"


if !equality.Semantic.DeepDerivative(expected.Spec, found.Spec) {
  // some field set by the operator has changed
}
```

**Comment by mjaow** [comment]
> I also have the problem using reflect.DeepEqual or equality.Semantic.DeepEqual because some fields are set with default non-zero values by some controller (like ImagePullPolicy, RestartPolicy, and so on) if these fields are not set by the operator.
> 
> I found this utility function that makes the job for me: it compares only fields that are non-zero in the expected struct:
> 
> ```go
> import "k8s.io/apimachinery/pkg/api/equality"
> 
> 
> if !equality.Semantic.DeepDerivative(expected.Spec, found.Spec) {
>   // some field set by the operator has changed
> }
> ```

It will ignore some update, maybe I'm trying to add a field to deployment, but it will ignore it

**Comment by devlifealways** [comment]
Same here, `Semantic.DeepDerivative` ignores a couple of fields, which causes the test to fail each time.

**Comment by rda3mon** [comment]
> It also bothered me that too many unnecessary updates were done because of the DeepEqual, so I implemented this approach:
> 
> * Use [hashstructure](https://github.com/mitchellh/hashstructure) to calculate a hash of the deployment that I want to have
> * Store that hash under an annotation ("mydomain/last-applied-hash")
> * In the reconcile function, compare the stored hash with the newly computed hash,  and only update if they differ
> 
> This way, I don't need to do a deep-compare each time the reconcile function is triggered, and I also push less changes to kubernetes.

You can use `crypto/sha256` instead of hashstructure on marshalled spec to get a hash. Here is an example 

```
var hashStore = make(map[string]string)
```

```
newSS := r.buildStatefulSet(m, d)
newSSMarshal, _ := json.Marshal(newSS)
```

```
else if asSha256(newSSMarshal) != hashStore[newSS.Name] {
  log.Info("Updating StatefulSet", "StatefulSet.Namespace", newSS.Namespace, "StatefulSet.Name", newSS.Name)
  err = r.Update(ctx, newSS)
  if err != nil {
    log.Error(err, "Failed to update StatefulSet", "StatefulSet.Namespace", newSS.Namespace, "StatefulSet.Name", newSS.Name)
    return ctrl.Result{}, err
  }
  hashStore[newSS.Name] = asSha256(newSSMarshal)
  return ctrl.Result{Requeue: true}, nil
}
```

**Comment by aweis89** [comment]
> It also bothered me that too many unnecessary updates were done because of the DeepEqual, so I implemented this approach:
> 
> * Use [hashstructure](https://github.com/mitchellh/hashstructure) to calculate a hash of the deployment that I want to have
> * Store that hash under an annotation ("mydomain/last-applied-hash")
> * In the reconcile function, compare the stored hash with the newly computed hash,  and only update if they differ
> 
> This way, I don't need to do a deep-compare each time the reconcile function is triggered, and I also push less changes to kubernetes.

One thing to be mindful about this approach is it doesn't eliminated configuration drift that originated outside the controller in-question. If someone updates the controlled object state, say using kubectl, the generated hash won't differ and the desired state won't match the actual state until another reconciliation is triggered. This is often not how controllers are meant to behave.

**Comment by Madongming** [comment]
> In the generated code, reflect.DeepEqual is used to check if the resource is changed. I created a deployment then used reflect.DeepEqual to compare it with the one fetched from k8s. The issue is the one fetched from k8s was changed by deployment controller (I assume it is) by filling with default values and is different from the deployment I constructed. This will trigger a update to deployment. And it seems this will happen continuously. Is this something expected? Or I am missing something?
> 
> Thanks.

I also encountered a similar problem. The solution is to update first, and use the client.DryRunAll parameter option, and then use reflect.DeepEqual to compare Spec to achieve the goal. Code reference
```
	if err := r.Client.Update(ctx, object, client.DryRunAll); err != nil { // client package is "sigs.k8s.io/controller-runtime/pkg/client"
		return err
	}

	if reflect.DeepEqual(curObjct.Spec, newObject.Spec) {
		logger.Info("Object is not changed, skip update")
		return nil
	}
        if err := r.Client.Update(ctx, object); err != nil {
		return err
	}
```
It‘s work now

**Comment by RafaelBroseghini** [comment]
If you are trying to prevent calls to the api server: I landed on ultimately using a combination of hashstructure and `metadata.generation` as an annotation (`hashstructure-generation`). Any drift to the underlying object will be corrected since the generation part of the annotation will not match. One downside is on creation you get at least one update call to persist the annotation.
