### ISSUE TITLE
Support custom ServiceAccount Name in rbac generating

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/kubebuilder#601]
Right now the role is bind to default, which make every pod in this namespace has the same permission. In some use cases, there is other pod in this namespace to co-work with controller-manager. Such pods should not have access of apiserver.

**Comment by Adirio** [comment]
I was going to open a new issue about this, will write out some thoughts:

- A single `ServiceAccount` needs to handle every controller of a project, as all the controllers are built into a single manager, right?
- `kube-system` controllers do have separate `ClusterRole`s per controller, following the same pattern makes sense, doesn't it?
- One `ServiceAccount` with many `ClusterRole` can be achieved. `ClusterRoleBinding` allows to assign a single `ClusterRole` to multiple `ServiceAccount`s but not the other way round, so a `ClusterRole` and a `ClusterRoleBinding` per controller with a single `ServiceAccount`.
- [kubernetes-sigs/controller-tools](https://github.com/kubernetes-sigs/controller-tools) walks `pkg` dir. This dir can be set as a flag. Should the one `ClusterRole` and one `ClusterRoleBinding` per controller be placed in controller-tools, directly in the Makefile, or in a new script. Removing kubebuilder specific code from controller-tools seems to be a sound idea. This would require to modify controller-tools to allow to specify output file names. This modification would enable using `pkg/controller/XXXX` and `pkg/webhook` as input dirs and thus avoid parsing `pkg/apis`, as each of the calls could specify a different output name. I don't think https://github.com/kubernetes-sigs/kustomize supports providing a dir of resources instead of the excat files, so either it should be added as a feature to kustomize ot the kustomization file should be updated each time manifests are generated.

/kind design
/sig api-machinery

**Comment by Adirio** [comment]
NOTE: https://github.com/kubernetes-sigs/kustomize mentions in their [eschewed features](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#globs-in-kustomization-files) that they will not support globs in kustomization files.

**Comment by Adirio** [comment]
The required characteristic (being able to specify file names) was already added to [kubernetes-sigs/controller-tools](https://github.com/kubernetes-sigs/controller-tools) in kubernetes-sigs/controller-tools#147, so using multiple `ClusterRole`s and `ClusterRoleBinding`s should be doable.

**Comment by jannickfahlbusch** [comment]
It seems like the option to specify the name of the ServiceAccount from https://github.com/kubernetes-sigs/controller-tools/pull/147 disappeared with https://github.com/kubernetes-sigs/controller-tools/commit/80c3f33947eae2256dd464e544eabfff4884e21b.

Is there currently a way to specify the name of the ServiceAccount?

**Comment by DirectXMan12** [comment]
> It seems like the option to specify the name of the ServiceAccount from kubernetes-sigs/controller-tools#147 disappeared with kubernetes-sigs/controller-tools@80c3f33.

That's because controller-gen is no longer responsible for generating the bindings -- it just generates the role itself.

**Comment by shashankram** [comment]
Why was this issue closed? Is there a way to specify the ServiceAccount name in the generated ClusterRoleBinding?
