### ISSUE TITLE
Is it possible to run test without real ETCD?

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/kubebuilder#605]
currently, it need `ETCD` and is hardcoded to  "/usr/local/kubebuilder/bin/etcd". I have to install kubebuilder in my CI using `root`. How to change this behavior? I have no root permission

**Comment by teddyking** [comment]
It’s possible to configure the tests to target an existing Kubernetes cluster rather than have them boot up a local control plane each time.
You can do this by modifying the generated `envtest.Environment` in the `*_suite_test.go` files to set [UseExistingCluster](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.1.10/pkg/envtest/server.go#L85-L88) to `true`. 

Although one thing to be aware of is that right now this option is not idempotent if you are also installing the CRDs (see https://github.com/kubernetes-sigs/controller-runtime/issues/342 for further info).

**Comment by DirectXMan12** [comment]
you can also set `KUBEBUILDER_ASSETS` to point elsewhere, and it'll look for etcd and the apiserver there.
