### ISSUE TITLE
Docs suggestion: Optimistic Concurrency

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#617]
Suggest adding following to KB docs.

@droot @akashrv

----

Sometimes a resource is updated while the controller is working on that resource.  For example, a user might modify the resource's spec while the controller is computing and updating its status.

Kubernetes implements Optimistic Concurrency on the server side, so if client sends an update with stale object (older resource version), the server will reject the request and client will return with an error.   KB handles this for you by requeuing the status update.  Your controller will likely recompute status using  latest copy of the object on the next invocation, and the update should succeed.

If you are using controller-runtime/client directly, then retrying is as simple as `return Result{Requeue: true}`.

**Comment by camilamacedo86** [comment]
This one would be a great fit for a FAQ section where we could do the same clarifications done in: https://sdk.operatorframework.io/docs/best-practices/common-recommendation/

We need to let users know that the goal is to:

> Develop idempotent reconciliation solutions
When developing operators, it is essential for the controller’s reconciliation loop to be idempotent. By following the [Operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) you will create [Controllers](https://kubernetes.io/docs/concepts/architecture/controller/) which provide a reconcile function responsible for synchronizing resources until the desired state is reached on the cluster. Breaking this recommendation goes against the design principles of [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) and may lead to unforeseen consequences such as resources becoming stuck and requiring manual intervention.

And that when in getting the resource in the reconciliation we store this data in a Golang structure so that before we use the client to update/change the resource would be recommended to get the latest version. Otherwise, we might face issues because the state of the resource on the cluster is no longer the same which should re-queue the reconciliation. 

Error example faced in the logs: `the object has been modified; please apply your changes to the latest version and try again`.

**Comment by camilamacedo86** [comment]
Since the above comment provides the description of what we need to do here, I think it is a good `good first issue`

**Comment by ashutosh887** [comment]
I would like to work on tis issue @camilamacedo86 
/assign

**Comment by ashutosh887** [comment]
@camilamacedo86 
Is this issue still relevant or should I drop this for now?

**Comment by camilamacedo86** [comment]
I think we can close this one. 
The best approach in this case is ensure that you fetch the resource before any update so that you will avoid this issue. However, @ashutosh887 if you or any person would like to doc this one it might be nice to be add it to  the FAQ: https://book.kubebuilder.io/faq

Something as the following example


#### How to avoid the error `"the object has been modified, please apply your changes to the latest version and try again`"? Why it occurs? 

See that when are developing operators, it is essential for the controller's reconciliation loop to be idempotent. By following the [Operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/)[1], we will create [Controllers](https://kubernetes.io/docs/concepts/architecture/controller/)[2] who provide a reconcile function responsible for synchronizing resources until the desired state is reached on the cluster. That means that the reconciliation is like a loop that will still be running until it can ensure the desired state on the cluster. 

The error `" the object has been modified; please apply your changes to the latest version and try again"` usually happens because we fetched the resource and stored it in a variable in our reconcile. Then after a while, we try to update this resource using the data stored in the variable/controller. However, the state of the resource on the cluster changed from when we fetched the data using the client until when we try to update it. 

An alternative solution for the proposed idea, to use the server-side, can be to ensure that you re-fetch the resource (client.GET) before any update (client.Update).


I am closing this one but feel free to contribute with the docs if you wish.

**Comment by RafalSkolasinski** [comment]
It would be great if there was better built-in handling for it. I find these errors extremely annoying. Just got it constantly when replacing quite simple but verbose logic with CreateOrUpdate


```go
	deploy := &appsv1.Deployment{ObjectMeta: metav1.ObjectMeta{Name: runtime.Name, Namespace: runtime.Namespace}}
	op, err := ctrl.CreateOrUpdate(ctx, r.Client, deploy, func() error {
		// Deployment selector is immutable so we set this value only if a new object is going to be created
		if deploy.ObjectMeta.CreationTimestamp.IsZero() {
			deploy.Spec.Selector = &metav1.LabelSelector{
				MatchLabels: sharedLabels(runtime),
			}
		}

		// Set number of replicas
		deploy.Spec.Replicas = &runtime.Spec.Replicas
		deploy.Spec.Template = r.podTemplate(runtime)

		// Set the ownerRef for the Deployment
		// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/
		if err := ctrl.SetControllerReference(runtime, deploy, r.Scheme); err != nil {
			return err
		}
		return nil
	})

        // <WILL INSERT HERE>

	if err != nil {
		log.Error(err, "Failed to reconcile the Deployment")
		return ctrl.Result{}, err
	}
```

whenever I was modifying deployment's replicas to force controller to reconcile I was getting the "the object has been modified errors...". I am absolutely puzzled why does it happen, the `CreateOrUpdate` should be getting the object before issuing update... could be that CreateOrUpdate is more efficient then my previous logic and something in the meantime is modifying the resource... 

anyway, inspired a little by `client.IgnoreNotFound(err)` wrapper I added before err checking in place of <will insert here> a following and it does seem to work perfectly

```go
	if status, ok := err.(apierrors.APIStatus); ok || errors.As(err, &status) {
		if status.Status().Reason == metav1.StatusReasonConflict {
			log.Info("requeuing due to resource conflict")
			return ctrl.Result{Requeue: true}, nil
		}
	}
```
