### ISSUE TITLE
Implement ComponentConfig by default & stop using (most) flags

### ISSUE THREAD

**Issue by luxas** [kubernetes-sigs/kubebuilder#722]
/kind feature
related KEPs here: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/wgs

cc @DirectXMan12 as per contributor summit discussion

**Comment by DirectXMan12** [comment]
Needs equivalent CR support, adding an issue there.

**Comment by stealthybox** [comment]
Related https://github.com/kubernetes-sigs/controller-runtime/issues/518

**Comment by christopherhein** [comment]
We've gotten the initial implementation done in https://github.com/kubernetes-sigs/controller-runtime/pull/891 using https://github.com/kubernetes-sigs/controller-runtime/issues/895 to track the progress. Do you think we're ready to do an initial implementation Kubebuilder @DirectXMan12 ? The changes as I see could be something like…

When you `kubebuilder init` you could pass `--component-config` which would add a couple of small changes to the `main.go` like adding `.AndFromOrDie(cfg.FromFile())` to the `ctrl.Options{}` passed into `ctrl.NewManager()` as well as configuring the  `config/manager/kustomization.yaml` to load a ConfigMap from a file and scaffold that file in `config/manager/config.yaml` this way out of the box you have a built-in configfile to configure how the controller manager is run if you want to use this and you could exclude `--component-config` if you didn't. 

An extended version of this could be `--component-config={CustomKind}` which could scaffold custom type similar to https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/configfile/custom/main.go#L49-L53 + https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/configfile/custom/v1alpha1/types.go, this would require automatically setting `multigroup: true` since configs are typically `config.{domain}` with a kind of `{Name}Configuration`.

What do you all think? _(My hesitation would be that it's defined as an alpha API and we don't have a versioning strategy in-place yet)_

**Comment by christopherhein** [comment]
Looks like #1746 should be done first which is involved in updating to the latest CR build.
