### ISSUE TITLE
Use Audit to RBAC or a meta type to generate RBAC YAML

### ISSUE THREAD

**Issue by luxas** [kubernetes-sigs/kubebuilder#723]
/kind feature
As discussed at the contrib summit.
Options discussed:
 - Use something like https://github.com/liggitt/audit2rbac together with a temporary API server with audit enabled
 - Use some kind of meta layer between using the Go client and executing API requests; so that that layer could be used for this purpose
 - Static code analysis

cc @DirectXMan12

**Comment by camilamacedo86** [comment]
Hi @luxas, 

This issue is open for a while. It seems hard for someone to get this one because I am not sure if I can follow the idea/proposal of this. 

Could you please let us know if it would still be a requirement?
If so, could you please clarify why that would be required? What are the motivations and problems that we would like to solve?

I am removing the lifecycle/frozen and adding needs-info. After your reply here we can try to triage this one in the meetings.

**Comment by camilamacedo86** [comment]
Removing the frozen since it is open for years without votes from the community.

**Comment by camilamacedo86** [comment]
Closing this one since it has no longer further info, engagement and is open for too long. 
Feel free to re-open if you see required.
