### ISSUE TITLE
Groups are no longer separated by package in v2.0.0-alpha.1 or v2.0.0-alpha2

### ISSUE THREAD

**Issue by ejweber** [kubernetes-sigs/kubebuilder#739]
KubeBuilder v1.0.8 would separate API groups into different packages (i.e. .../pkg/apis/group1/v1 and .../pkg/apis/group2/v1). With the new directory structure, it is not possible to make two different API groups that have the same version, as Kinds from both groups are generated in the same version folder (i.e. v1) and each version folder has only one groupversion_info.go file.

**Comment by ejweber** [comment]
I found the following [documentation](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/simplified-scaffolding.md#making-this-work-with-multiple-controllers-api-versions-api-groups-etc), which suggests KubeBuilder will help scaffold with a "hybrid approach", but I don't understand how that's supposed to work.

**Comment by DirectXMan12** [comment]
/kind bug

This is an oversight from on our part -- KB should be detecting or warning about this, and should be able to work with the more complex setups.

**Comment by DirectXMan12** [comment]
re-opening -- we only check this now, and don't support scaffolding multigroup, I believe

**Comment by joshiomkarj** [comment]
The directory structure that is generated by 
kubebuilder create api --group webapp --version v1 --kind Guestbook
is 
api/v1/guestbook_types.go

This breaks the code-generator because code-generator expects the directory api/webapp/v1/guestbook_types.go

I'm using code-generator to generate typed and versioned clients, listers and informers along with the controller generated by kubebuilder.

So could someone let me know if the change in directory structure is a design decision that was taken and unlikely to change or is it a bug?

**Comment by DirectXMan12** [comment]
It's a design decision.  We talk about it a bit in https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/simplified-scaffolding.md.

We're likely to eventually introduce multi-group support, however, which would most likely enable your usecase.

We don't technically support code-generator, but FWIW, I'd consider that a bug against code-generator.  It has enough information with the standard markers to figure out what the group name is w/o the path

**Comment by joshiomkarj** [comment]
@DirectXMan12 Thanks for the update. I have filed an issue on code-generator to get their perspective on this problem.
