### ISSUE TITLE
Consider removing ginkgo/gomega from generated tests

### ISSUE THREAD

**Issue by nstogner** [kubernetes-sigs/kubebuilder#822]
The [ginkgo](http://onsi.github.io/ginkgo/) & [gomega](http://onsi.github.io/gomega/) test libraries included in generated controller tests add another barrier to understanding the code produced by kubebuilder: first the developer must become familiar with an opinionated testing framework. The value-add from included them seems to be pretty low.

The generated test code does not seem to necessitate the dependency on these packages. Perhaps they could be removed and the choice of a test-framework could be left up to the controller developer if the need for one arises in a given project.

/kind feature

**Comment by DirectXMan12** [comment]
We've had some debate internally about this.

It basically boils down to this:

- People tend to not to have a good idea of how to test controllers, so any starting point is something
- People tend to write poorly structured Go tests, because there aren't good facilities for setup and teardown in vanilla Go testing frameworks
- I (and a couple of the other maintainers) find that Ginkgo & Gomega gently nudges towards cleaner tests (it's why we went/are going full-on Ginkgo in v2, and why we use Ginkgo & Gomega internally for unit & integration tests in controller-runtime itself).

That being said, we're cutting down on the number of test files that we scaffold out by default, and moving towards some optional test-scaffolding commands (cc @droot), but I'd still like to take an opinion on this.

On a personal note, I find the built-in Go unit testing framework wholly insufficient for writing readable tests -- lack of an assertion library, non-human-readable test names, no setup/teardown abstractions, etc, make the tests frustrating to read *and* write, especially as you start to write things that look like integration or e2e tests.

Closing this for bookkeeping purposes, but that isn't entirely intended to be a "conversation over" marker.
