### ISSUE TITLE
Support for old object access

### ISSUE THREAD

**Issue by bingosummer** [kubernetes-sigs/kubebuilder#877]
The scenario is:
I have a controller which is responsible for creating/updating/deleting external resource. These operations normally need some time to complete. So, the controller should re-queue it after sending the creating request to external components. When the controller gets the request again from queue, it should check the state of the external resource.

As https://book-v1.book.kubebuilder.io/basics/what_is_a_controller.html mentioned, the controller should be a level-based API. The Controller should immediately stop rolling out the old values and start the rollout for the new values.

Question 1: **Can I assume that the request in the `Reconcile` function is in order?** If not, there may be a problem.

For example, the controller is handling a request whose resourceVersion is `1`. At the same time, user is applying a new change in spec and a new request with a new resourceVersion `2` is put into the queue. Then, for some reason, the controller decides to re-queue the request (`resourceVersion: 1`). Then the controller will get the request (`resourceVersion: 2`) and the request (`resourceVersion: 1`). Without old object, I think, the controller can't tell which request is newer.

Question 2: How to differentiate between and react differently to added objects, updated objects?

See a similar feature request in https://github.com/kubernetes-sigs/kubebuilder/issues/37.

**Comment by DirectXMan12** [comment]
For question 1:

The controller will never see things going back in time, within a single resource -- resourceVersion for any individual resource will be monotonically increasing.

For question 2:

Don't do that.  Really, don't do that.  It leads to all sorts of weird bugs, especially since the underlying queue system sees a bunch of adds on controller-start, even if the object isn't new.  Add only means "this given pid hasn't seen this object yet".

**Comment by DirectXMan12** [comment]
(closing for now, feel free to continue to ask questions though)
