### ISSUE TITLE
Variable for the `kind`

### ISSUE THREAD

**Issue by ljdelight** [kubernetes-sigs/kubebuilder#878]
I'm looking at this code block of the [kubebuilder book](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go#L555) and it uses a hard-coded string for the kind:
```
if owner.APIVersion != apiGVStr || owner.Kind != "CronJob" {
	return nil
}
```

The `Group` and `Version` [can be accessed](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/api/v1/groupversion_info.go#L43) with variables, but I don't see a variable for the `Kind`. This feature request is to have a way to access the `Kind`. 

/kind feature

**Comment by DirectXMan12** [comment]
Correct, since group and version don't correspond directly to package name, but Kind always corresponds directly to type name in KubeBuilder-generated code.  It's possible for that to not be true, but you need to do some contortions.  For the sake of the book, this is clear enough, I think, and adding `var CronJobKind = "CronJob"` doesn't really make things much clearer.

**Comment by ljdelight** [comment]
I meant for the `Kind` to be made available in the scaffolding so that new projects would have access via a variable. So we have the `GV` but not the `K` which seemed like a miss. It's not necessary to add, just a thought as I was going through some code

**Comment by DirectXMan12** [comment]
ah, you meant having `CronJobGVK = api.GroupVersion.WithKind("CronJob")`?

**Comment by DirectXMan12** [comment]
for each kind in a group-version?

**Comment by ljdelight** [comment]
Uhmmm perhaps. I don't mean to waste your time, and I would love to say "why yes, that's what I meant, you read my mind!", but I must admit that I don't understand the context of your message since I'm not especially skilled at go, k8s, kubebuilder. 

As a quick rehash, a nice-to-have is a scaffolding-provided variable for the generated Kind so that this `owner.Kind != "CronJob"` can be replaced with, say, `owner.Kind != apiKind`.

More background:
I saw the GITK episode creating a k8s controller for minecraft and decided that I'd attempt my own using Factorio. I know, exciting! I stumbled around enough to get a basic thing working, but I especially wanted to experiment with how the field indexing in CronJob's `SetupWithManager` functioned. I boldly copied the method from [the CronJob demo](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go#L552) and I stared at the `owner.Kind != "CronJob"` (I had forgotten my Kind). 

Maybe it's a useful enhancement to the project scaffolding to identify the Kind, but I could easily miss any existing functionality. This is the [factorio 'kubetorio' project](https://github.com/ljdelight/kubetorio/blob/master/controllers/server_controller.go#L132) if you'd like to gander (PoC, broken "u idiot" bugs, etc).

**Comment by DirectXMan12** [comment]
> I'm not especially skilled at go, k8s, kubebuilder.

No worries -- just trying to understand the usecase.

> I boldly copied the method from the CronJob demo and I stared at the owner.Kind != "CronJob" (I had forgotten my Kind).

Ah!  Ok.  So, what I was suggesting was that the line

```
if owner.APIVersion != apiGVStr || owner.Kind != "Server" {
```

could maybe be replaced by

```go
if schema.FromAPIVersionAndKind(owner.APIVersion, owner.Kind) != myapi.ServerGVK
```

However, I wasn't really certain that was clearer, especially since your Go type name will always be your Kind, so if you have to type `ServerGVK` (or , you already "know" that your kind is `Server`, assuming familiarity with the subject matter, which is not guaranteed for newcomers.

Thus, I was kinda wondering if this was a docs issue (it wasn't clear what the value of Kind was, and we should make it clearer that kind is always type name), a convenience issue (comparing APIVersion & Kind to GVK is annoying), a "separation" issue (it's not clear that we're referring to ServerGVK, just split in two parts), some combination of the above, or some other issue.

Separately, I'm happy to hear people have started to play around with writing little controllers like this.  Please do let me know if there's anything else that was confusing or could use clearer docs.
