### ISSUE TITLE
Autoscaling CR pods with HPA is extremely confusing and not explained anywhere

### ISSUE THREAD

**Issue by ScottBerman** [kubernetes-sigs/kubebuilder#959]
The Kubebuilder documentation simply states that the HPA will be able to autoscale your custom resource.  How to do so is not documented anywhere and is a really confusing process. @DirectXMan12 

/kind documentation

**Comment by DirectXMan12** [comment]
additional context:

- it's not clear when and what needs to go in the various fields (status & spec replicas, label selector)
- it's not clear how to populate the string form of the label selector (`AsLabelSelector().String()`)
- it's not at all clear *why* these various bit need to be in place

**Comment by ScottBerman** [comment]
I wrote a walkthrough if anyone ends up here wondering how to do this: https://medium.com/@thescott111/autoscaling-kubernetes-custom-resource-using-the-hpa-957d00bb7993

**Comment by camilamacedo86** [comment]
Hi @ScottBerman, 

Is the doc that is not clear in the docs of this project or Kubernetes one? if is here, could you please add the link for the doc. If not, could you please raise it in the repo/project where the doc is?

**Comment by DirectXMan12** [comment]
@camilamacedo86 it's just a writeup that covers the steps if you're using KB, so it belongs here :-)

**Comment by vsoch** [comment]
@ScottBerman I found your medium article first, and it got me pretty far, but I got confused at the point you were referencing the `deployment.Spec.Selector` because we never added a "Selector" field to the Spec, we only added it to `Status`.

```console
selector, err := metav1.LabelSelectorAsSelector(deployment.Spec.Selector)
```
I tried using Status, but Status is a string (incorrect type, it wants ` *"k8s.io/apimachinery/pkg/apis/meta/v1".LabelSelector` so I'm in stage "browse internet like a lost soul until I find some insight!" :laughing:

**Comment by Bobby-Wan** [comment]
@vsoch FYI i believe the setup in the blog has a deployment dependent on the CR, I assume where the pods for the jobs are to be run. We get the selector from the deployment spec, not the CR spec.

**Comment by vsoch** [comment]
@Bobby-Wan that is this selector here?

![image](https://github.com/kubernetes-sigs/kubebuilder/assets/814322/eb356f2f-dc4c-4b79-a33d-2643758610aa)

It might be helpful to say that, because there is no mention in the article and for someone newer to Kubernetes, HPA, or anything else, it can be confusing (it was for me).

**Comment by Bobby-Wan** [comment]
This is how the selectors are gotten in the blogpost:
selector, err := metav1.LabelSelectorAsSelector(deployment.Spec.Selector)
He takes them from a deployment. There is no much mention of the deployment outside of that, but I assume it's an owned resource for the CR. When a CRUD operation is executed, it is also applied to the deployment . This can be done in other ways, I assume. After that, the CR status (the image you posted) is updated with this like:
mycr.Status.Selector = selector.String()
so he takes what's in the deployment spec.selector and updates the CR status.selector with it, which is what the HPA uses to know what pods to track.
