### ISSUE TITLE
Document alternatives to cert-manager

### ISSUE THREAD

**Issue by cliveseldon** [kubernetes-sigs/kubebuilder#969]
Its unclear the steps to create self-signed certs for the webhook server. One project our operator (built using kubebuilder v2) would be included in is kubeflow which [has moved away from cert-manager](https://github.com/kubeflow/kubeflow/issues/3079).

Having docs helping one to use alternatives and examples would be useful. 

If someone could explain the simple steps to use self-signed certificates and the updates needed to the kustomize config to use them instead of cert-manager I would be happy to help add to docs and kustomize config.

/kind feature

**Comment by DirectXMan12** [comment]
So, I'm happy to accept a documentation PR saying what certs to put where if you've generated them yourself.  That's fine.

/help

I (probably) won't accept other options for generating certs.  That gets to be a pain to maintain.  The expectation is that if you don't know what you're doing (or if you do, and like cert-manager, since it's an awesome project), you can use cert-manager.  If you don't want to use cert-manager, you should know how to generate certificates yourself.  I don't really want to be responsible for helping people debug their openssl workflows (having done that before, it's not easy).  Again, though, I'll happily have docs saying where to put the certs once you've generated them.

**Comment by olttwa** [comment]
Hello @DirectXMan12 @cliveseldon 👋
I'm a first time contributor to k8s-sigs.

Please confirm if my solution satisfies the requirements:

In section [1.9. Running and deploying the controller](https://book.kubebuilder.io/cronjob-tutorial/running.html), add a sub-section: `1.9.3 Installing self-managed certs` 
It will provide documentation/guidelines for:
  - Where to put certs data (ca.crt, tls.crt and tls.key)
  - Naming convention to follow when deploying webhooks
  - Necessary code changes, for example [trusting TLS in a cluster](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#trusting-tls-in-a-cluster)

Thanks!

**Comment by DirectXMan12** [comment]
There shouldn't be any code changes needed (item 3) -- that stuff gets done automatically by CR.  It should be mostly just item 1 -- where to put the cert data (the cert names you've listed, plus where to put the CA in the webhooks, etc).

**Comment by developerjinchun** [comment]
I also second this request. I'm currently working on an operator that, due to circumstances, cannot utilize `cert-manager`, requiring me to create a custom cert-manager container, but the lack of official doc on this could see improvement.

**Comment by DirectXMan12** [comment]
Considering that this has no movement in a while and my above comments, I'm gonna close this.  controller-runtime's godoc has more specific info on what certs go where now (https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager?tab=doc#Options), and otherwise KubeBuilder is supposed to be opinionated.
